### ISSUE TITLE
Update blue box test scripts for 19K example bundles

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#1005]
data-bundle-examples/bin/ has a number of out-of-date scripts that load 19,000 example bundles into the blue box. It has some drawbacks in that the metadata isn't validated, and it stuffs things straight into the blue box. But it is still a useful stress test for the blue box.

As a project leader I would like to see the DCP run stress tests on a regular basis (nightly?).

These stress tests should include uploading multiple bundles (100-1000 of bundles) that include bundles containing large files (100GB).

Completion would include automation for nightly test runs. It is ok to transfer files cloud to cloud. Performance of the run should be monitored and charted with past runs.

**Comment by Bento007** [comment]
This ticket should be combined into the current scale testing for blue.

**Comment by mweiden** [comment]
This is out of date with the current scale testing strategy. Closing this.
