### ISSUE TITLE
Support EBI in migrating onto centralized logging system

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/data-store#1019]
## Need (user story)
* As an operator of the ingest system or an operator of the DCP more generally
* I want an automated/reproducable deployment of the integration between the ingest system and the logging system
* so that I can view ingest logs.

**Comment by kozbo** [comment]
What is the definition of done for this issue?

**Comment by mweiden** [comment]
@kozbo That EBI has a reproducible/automated deployment of their logging integration. This will come as they migrate to EKS.

This ticket probably best belongs on the logging repo. Any objections to moving it there?

**Comment by kozbo** [comment]
Sounds good. Please go ahead and move it. Thanks!

**Comment by mweiden** [comment]
Moved to https://github.com/HumanCellAtlas/logs/issues/48
