### ISSUE TITLE
Notify when a bundle is tombstoned

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#1037]
**Story**: as a user I would like to know when a bundle ~~that matches my subscription~~ is tombstoned.

**Requirements:**
- [ ] Notification when a bundle ~~previously matching your subscription~~ is tombstoned.

**Definition of Done**
~~Create a subscriptions for a specific type of bundle. Index a bundle matching that subscription and verify notification. Tombstone a bundle matching that subscription and verify notification.~~
Create a subscription to the tombstone JSON. Delete a bundle. Show that notification was sent. 

[Edit: It is not possible to limit tombstone notifications to bundles matching a query. We can only support notification on any tombstone (@hannes_ucsc)]

**Comment by kislyuk** [comment]
> It is not possible to limit tombstone notifications to bundles matching a query.

I understand why it might not be possible to do this with ES, but if we end up with a query language/engine that is not ES-specific, this may still be possible.

Also same comment as in #1036: I think we should avoid using the jargon word "tombstone" in user-facing documentation. I suggest using "deletion events" instead.

**Comment by hannes-ucsc** [comment]
+1 on "deletion events"

**Comment by mweiden** [comment]
@xbrianh may have a solution to the ES issue.
