### ISSUE TITLE
Manifest handoff architecture

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#1041]
definition: manifest - a list of entities (bundles, projects, files, and processes) curated by the orange box.

*Story:* As a user I would like to use a manifest to bulk download data from the hca command line.

- Determine manifest data representation format and api. 
- Will require integration with the hca-cli.
- Related to the handoff mechanism with the redbox
- discern relationship with collections

*Requirements*
- Storing manifest
- bulk download of files in manifest.
- downloaded bundles must be zipped in a file with the uuid as the name.

*DOD*
- deliver example manifest.
- Make sure approved by @lauraclarke @TimothyTickle @caaespin 
- Demonstrate downloading a manifest using the HCA CLI.

**Comment by kozbo** [comment]
Closing. This is redundant to the collections Epic.
