### ISSUE TITLE
Design collections

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#1048]
We need to complete the design of how collections work.
*Story:* As a programmer developing the collections feature I would like to understand the important use cases and have direction on key developmental concerns so that I can begin implementation.

@briandoconnor to provide use cases
@kislyuk to provide design and implementation plan

**Comment by Bento007** [comment]
Doesn't this exist already [DRS for Blue Box: Data Release Service Functional Specification and Use Cases - DEVELOP](https://docs.google.com/document/d/10WXG2oh51RgigTBRdLpq8b48APEv8BhPkPTsM1DtpzA/edit?usp=sharing?)
