### ISSUE TITLE
Spec - Data Bundle SOP v0.2

### ISSUE THREAD

**Issue by briandoconnor** [HumanCellAtlas/data-store#106]
Need a new version based on feedback this week

**Comment by briandoconnor** [comment]
I got through about 2/3 of the open issues with this doc but need another blue-box call to finish these issues and release a v0.2

**Comment by kozbo** [comment]
More review was done of the spec in the Blue Box call on 7/21/17, but still not done. I owe some clarification comments to Laura and Jim.

**Comment by kozbo** [comment]
Brian released v0.2
