### ISSUE TITLE
Throttling Exception related to DescribeExecution in the checkout service

### ISSUE THREAD

**Issue by amork** [HumanCellAtlas/data-store#1061]
{
  "Error": "SwaggerAPIException",
  "Cause": "{\"errorMessage\": \"unhandled_exception: An error occurred (ThrottlingException) when calling the DescribeExecution operation (reached max retries: 4): Rate exceeded (HTTP 500). Details:\\nTraceback (most recent call last):\\n  File \\\"/var/task/chalicelib/dss/error.py\\\", line 26, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/var/task/chalicelib/dss/api/bundles/checkout.py\\\", line 30, in get\\n    response = stepfunctions.step_functions_describe_execution(STATE_MACHINE_NAME_TEMPLATE, checkout_job_id)\\n  File \\\"/var/task/chalicelib/dss/stepfunctions/__init__.py\\\", line 60, in step_functions_describe_execution\\n    resp = stepfunctions.describe_execution(executionArn=execution_arn)\\n  File \\\"/var/task/botocore/client.py\\\", line 314, in _api_call\\n    return self._make_api_call(operation_name, kwargs)\\n  File \\\"/var/task/botocore/client.py\\\", line 612, in _make_api_call\\n    raise error_class(parsed_response, operation_name)\\nbotocore.exceptions.ClientError: An error occurred (ThrottlingException) when calling the DescribeExecution operation (reached max retries: 4): Rate exceeded\\n\", \"errorType\": \"SwaggerAPIException\", \"stackTrace\": [[\"/var/task/domovoi/app.py\", 137, \"__call__\", \"result = handler(event, context)\"], [\"/var/task/domovoilib/dss/stepfunctions/generator/parser.py\", 79, \"<lambda>\", \"event, context, branch_id, *args, **kwargs))(state_machine_element, branch_id)\"], [\"/var/task/app.py\", 87, \"checkout_status\", \"checkout_output = get_client().get_bundles_checkout(checkout_job_id=job_id)\"], [\"/var/task/hca/util/__init__.py\", 149, \"__call__\", \"return self._consume_response(self._request(kwargs))\"], [\"/var/task/hca/util/__init__.py\", 137, \"_request\", \"raise SwaggerAPIException(response=res)\"]]}"
}

**Comment by kozbo** [comment]
This issue was moved to done, yet is not closed. Closing.
