### ISSUE TITLE
Add basic health check for system

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#1081]
As an administrator I would like to be able to run a simple ping to the system to make sure that it is running.

This equates to a level 1 health check on Rex's [DCP API Health checks proposal] 
[https://docs.google.com/document/d/15dGnWzMH3tpc5zCBLf0KiIvFh8lJvjGw9urT54XhFL4/edit#heading=h.xgjl2srtytjt]

There needs to be a /health endpoint that returns a 200 status if the system is up. Note that this is not meant to be an extensive multi-component  health check

Required for go-live

**Comment by mweiden** [comment]
@kozbo this is done. We should talk about how we can do a simple L2 health check. I think it's worth it in the near-term.
