### ISSUE TITLE
Need general documentation on the Data Store portion of the DCP

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#1085]
As a user I would like to be able to read documentation that informs me on what role the Data Store plays in the DCP

Documentation needed for the Go-Live

# Blue Box related Docs
- [x] Coordinate with OrangeBox to make sure that the content of this doc is properly onboarded in the OrangeBox portal
- [x] API docs - swagger embedded look at ICGC http://docs.icgc.org/portal/api-endpoints/#/PQL
- [x] API docs - Python client programmer guide from RTD
- [x] CLI - read docs from RTD
- [x] Vignettes and readmes as tutorials
- [x] Quick start guide (might link to vignettes)w
     intro - what is it
     how to get set up
     basic how to find data in the the browser
     get manifest
     download it with hca cli
     something to do with the data, ipydb
     links to vignettes

As a developer I would like to know how to build a portal
- [x] subscribe to events
- [x] build indexes
- [x] do analysis
- [x] application to share results

Orange:
- [x] Quick start guide on data browser - manifest example

Ops 
- [ ] Production SOP - how to run blue box production

**Comment by briandoconnor** [comment]
I think we should think about Vignettes as "Tutorials".  Other tutorials to think about:
* querying and event subscriptions via the API
* tutorial showing using Python Notebooks
* tutorial  showing using Spark

**Comment by kozbo** [comment]
Orange and Blue Quick Start Guide captured in this ticket:
https://app.zenhub.com/workspace/o/humancellatlas/data-portal-content/issues/51

API doc plan is to re-display the Read The Docs output. Captured in this issue:
https://app.zenhub.com/workspace/o/humancellatlas/data-portal-content/issues/75

Swagger docs will be pulled in too
https://app.zenhub.com/workspace/o/humancellatlas/data-portal-content/issues/75

CLI docs will be slurped in from the RTD pages
https://app.zenhub.com/workspace/o/humancellatlas/data-portal-content/issues/53

Quick start guide is in this issue, covered by the Orange Quick Start Guide
https://app.zenhub.com/workspace/o/humancellatlas/data-portal-content/issues/52

**Comment by kozbo** [comment]
Closed. This  issue was too broad. all the items have now been farmed out to other tickets as noted above.
