### ISSUE TITLE
Include metadata fields in notifications

### ISSUE THREAD

**Issue by dshiga** [HumanCellAtlas/data-store#1092]
As the secondary analysis service, we'd like it to be possible to include bundle metadata fields like project_json.project_shortname in notifications, so that we can more easily search and sort things for troubleshooting purposes.

When registering a subscription, we would like the ability to include an optional list of fields to be returned in each notification, along with the bundle id and version.

The subscription would work the same as before, except that each notification, in addition to including the bundle id and version, would also include the extra requested fields.

Having this information available in the notification would allow us to more easily and effectively search and sort queued up notifications and workflows in the secondary analysis service, which would be very helpful for monitoring and troubleshooting purposes.

**Comment by hannes-ucsc** [comment]
I think this is very useful. If this is urgent (next few weeks, or even before the 4/11 demo), we can break the implementation up by just hard-coding the inclusion of a predefined set of metadata fields and later add the ability to configure that set when registering a subscription registration.

**Comment by ttung** [comment]
Possibly related question: how does the notifications system deal with lambda timeout?

**Comment by dshiga** [comment]
The motivation for this feature request is to avoid having to make that extra request. We're trying hard to make sure very little processing is involved in receiving a notification in the secondary analysis service, for better throughput and reliability. Right now when we receive a notification, we immediately queue up a workflow run, which is very quick and cheap -- however, because the notification contains very little information about the bundle, it means we have no visibility into what data is sitting in our queue awaiting process (which projects, submitters, samples, etc). We could in theory make a request to the data store to get these additional metadata fields for each notification but we'd much prefer having a way to include this information in the notification itself, so we don't slow down our response and introduce another way for the hand-off to us could break.

**Comment by hannes-ucsc** [comment]
When we prepare the notification, we have the bundle right there in memory. Implementing this feature comes at virtually zero computational expense.

Lets start thinking about how a subscriber specifies the set of fields to be included in a subscription. Should it be restricted to fields of primitive types only so the payload stays small. Should we just include the entire bundle document? Something in between?

> Possibly related question: how does the notifications system deal with lambda timeout?

Currently it doesn't. The upcoming reliable notification PR enforces a timeout on the notification HTTP request and avoids notification attempts if there isn't sufficient time left in a lambda execution.

**Comment by ttung** [comment]
Why would the entire bundle be in memory?

**Comment by kozbo** [comment]
@dshiga   Are there two types of questions you are asking here?
1. What type of data is this - needed so that the correct run can be chosen or tailored to fit the data
2. What are the values of some of the fields - the run needs a short list of field values to get started
It seems like the first case could be solved by creating different subscriptions. 

Another question hinted at above from @hannes-ucsc: 
What do we do if the requested payload doesn't fit in our response?

**Comment by dshiga** [comment]
@kozbo we have different subscriptions for different data types, so that answers question 1 for us. This feature request is more for the sake of question 2. Currently, when notifications come in, we have very little information about what's in the bundle. We queue up the notifications on our end prior to actually running them and things could sit in that queue for a while. Including a few metadata fields in the notification itself would give us a much clearer picture of what's in our backlog to process.

This will help when submitters come to us and say, "Hey, I submitted 1000 cells of data yesterday and I don't have my results bundles yet, what's the status?" If we can't sort and filter our backlog of notifications by submitting lab, for example, it will be difficult for us to find out -- e.g. it's in our queue of stuff to process in secondary analysis vs we're currently running the secondary analysis on them vs results are already in blue box and they just weren't looking for it in the right place.

**Comment by hannes-ucsc** [comment]
> Why would the entire bundle be in memory?

**Comment by hannes-ucsc** [comment]
> Why would the entire bundle be in memory?

It just is. First, all metadata files are loaded from storage into memory, the index document is composed by combining the files into a single dictionary and the result is written to the index. The matching subscriptions are determined and notifications sent. All the while, the bundle metadata is held in memory.

**Comment by ttung** [comment]
Ahh, not the entire bundle, but the metadata files.  Got it.

**Comment by mweiden** [comment]
@dshiga @kbergin @hannes-ucsc Do we need to solve this problem yet? From an agile perspective, we should first solve this with existing primitives (get metadata from the existing ES endpoint) and then optimize when it becomes clear that we need to (add the metadata option). As @dshiga said, the metadata options are preferable. They would be necessary if you actually experience frequent failures or unacceptably increased latencies as a result of having to make the additional request.

**Comment by hannes-ucsc** [comment]
You are raising a good point, @mweiden. From the perspective of 'domestic tranquility', I think if we reject #1176 we should give in on this one.

**Comment by kbergin** [comment]
Was a decision made here? Last I had heard from @dshiga this was something we really needed in green

**Comment by dshiga** [comment]
In order for us to obtain this information about notifications as early as we need it, complexity has to be added somewhere. Adding it to blue box would make things easier for the green box and also help other clients who might want this feature.

**Comment by hannes-ucsc** [comment]
Let me know if you have any question on how to integrate with this new feature, @dshiga.

I'll deploy to `integration` this week.
