### ISSUE TITLE
Kibana/ES logs instance breaks query tokens on punctuation

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-store#1097]
Seaching by `cabe7031-3b80-4104-accb-23c08e561a51` results in matches that contain any of `cabe7031`, `3b80`, `4104`, `accb` or `23c08e561a51`. I would expect only matches containing exactly `cabe7031-3b80-4104-accb-23c08e561a51`. In a previous project that used SOLR (also based in Lucene) we had to modify the tokenizer and the query processor to break on whitespace only, not punctuation.

**Comment by Bento007** [comment]
Use either the es [pattern tokenizer](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/analysis-pattern-tokenizer.html) or the [keyword tokenizer](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/analysis-keyword-tokenizer.html).

**Comment by parthshahva** [comment]
@Bento007 I'm actually planning on using the whitespace tokenizer (https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-whitespace-tokenizer.html). This will become the default tokenizer in an index template (used for all future indices created after this template is set up. Unfortunately is not retroactive to existing indices). cc @mweiden

**Comment by parthshahva** [comment]
I'm also adding a default filter of lowercase. It should apply the whitespace tokenizer and lowercase filter both at indexing and at search time. Going forward, we can define specific tokenizers or filters at the mapping level, but I do not see the need for that at this time.

**Comment by parthshahva** [comment]
This is now resolved in the dev instance, if you search by a quoted UUID, getting rid of one of the middle portions in the dash-separated-string will no longer match any log events. @hannes-ucsc and @Bento007 please play around with this for user acceptance.

Solution: Manually created an index template that fixes the dash issue by using whitespace analyzer in a dynamic index template that matches on all string fields

Current Status: Trying to figure out best way to automated creation of this index template in production as not to not require any manual steps.

**Comment by hannes-ucsc** [comment]
https://logs.data.humancellatlas.org/_plugin/kibana/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now%2Fd,mode:quick,to:now%2Fd))&_a=(columns:!(_source),index:'*',interval:auto,query:(query_string:(query:bc514c99-2a98-42c2-8617-b46b083dfa8d)),sort:!('@timestamp',desc))

The first result is a partial match for `8617`:

<img width="1071" alt="screen shot 2018-03-28 at 6 52 31 pm" src="https://user-images.githubusercontent.com/5143256/38065668-4bef65a2-32b9-11e8-8569-e98d35c4088b.png">

**Comment by parthshahva** [comment]
@hannes-ucsc You have to wrap it in double quotes. I don't see a problem with allowing for dash separated searches unless someone wraps the string in quotes for an exact search. Is this different from your expectation?

**Comment by parthshahva** [comment]
Lol, I don't think my template actually did anything... I didn't even touch prod and double quoting works there as well. I'll want to discuss with you why this is not enough/ an issue.

**Comment by hannes-ucsc** [comment]
Ah yes, with quotes it works. 

I'd prefer without quotes but if it's excessively complicated to get that working, with quotes would be acceptable. On Google, for example, the quotes are needed, too.

I seem (!) to remember that I tried UUIDs wrapped in quotes weeks ago and it didn't work. So this is progress!

**Comment by hannes-ucsc** [comment]
A logs search for a bundle UUID doesn't match log records that list the FQID (uuid.version). For example, this search by FQID matches

https://logs.dev.data.humancellatlas.org/_plugin/kibana/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-24h,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'*',key:'@log_group',negate:!f,type:phrase,value:%2Faws%2Flambda%2Fdss-index-integration),query:(match:('@log_group':(query:%2Faws%2Flambda%2Fdss-index-integration,type:phrase))))),index:'*',interval:auto,query:(query_string:(query:%223bf64176-d7fd-494a-be85-e359bb7c2a43.2018-04-05T110612.631420Z%22)),sort:!('@timestamp',desc))

The corresponding search by UUID doesn't:

https://logs.dev.data.humancellatlas.org/_plugin/kibana/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-24h,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'*',key:'@log_group',negate:!f,type:phrase,value:%2Faws%2Flambda%2Fdss-index-integration),query:(match:('@log_group':(query:%2Faws%2Flambda%2Fdss-index-integration,type:phrase))))),index:'*',interval:auto,query:(query_string:(query:%223bf64176-d7fd-494a-be85-e359bb7c2a43%22)),sort:!('@timestamp',desc))

I think it might be an issue. Can we fine-tune the tokenizer to break on `.` and whitespace?

**Comment by hannes-ucsc** [comment]
Or break on whitespace and any punctuation except dash?

**Comment by hannes-ucsc** [comment]
This issue was moved to HumanCellAtlas/logs#45
