### ISSUE TITLE
Document get bundle API enhancements

### ISSUE THREAD

**Issue by amork** [HumanCellAtlas/data-store#1110]
Per my conversation with @briandoconnor:
augment get bundle API to initiate checkout behind the scene
so in your scenario you would not need to use checkout directly, instead you continue using get bundle API, instead of the repository URLs it would return location in the checkout bucket (edited)
what do you think?

think carefully about what triggers the checkout.  I can imagine the URL above would checkout the bundle since you asked for the URLs.  But I can also imagine that leaving off the directurls would just return the info about the bundle.  You want to find a balance where someone can quickly find out about the contents of a bundle without having to wait for a checkout.  Since people might want to just know what’s inside a bundle, get the UUIDs for the metadata files, then use the download of individual files to quickly pull back the metadata files.  If the large data files in this bundle are actually archived we wouldn’t want the user to wait for checkout of those files just to pull the metadata files.  Right?  Likewise, you can imaging I make the request on the bundle above (no direct URLs) and pull back the UUIDs of the data files (which have been archived).  I then make the individual file get requests to generate a signed URL.  So the first bundle metadata request would happen quickly whereas the individual file request I’m giving a check back later HTTP code while you checkout that file.  I think some flow like this works well.

**Comment by mweiden** [comment]
This ticket is now represented in https://github.com/HumanCellAtlas/data-store/issues/1203 and https://github.com/HumanCellAtlas/data-store/issues/1204
