### ISSUE TITLE
TooManyRequestsException when running scale test

### ISSUE THREAD

**Issue by amork** [HumanCellAtlas/data-store#1118]
While running scale test I'm seeing the following exceptions in dss-scalability-test SFN

Error
"Lambda.TooManyRequestsException"
Cause
"Rate Exceeded. (Service: AWSLambda; Status Code: 429; Error Code: TooManyRequestsException; Request ID: df10f912-3923-11e8-90e4-33aa472c10eb)"

Looks like we are running out of the 20K Lambda concurrency limit.

Consider the following:
1. Add a new key to config.json to daemon's ".chalice" dir to limit cocurrency on a per Lambda basis as percentage of the overall pool
2. Leverage DLQ-based reprocessing framework to reprocess failed invocations.

**Comment by kislyuk** [comment]
Per-function concurrency limits can be set in Domovoi starting with v1.5.6, by setting the `reserved_concurrent_executions` config key in `config.json`.

**Comment by mweiden** [comment]
@Bento007 and I haven't seen this in a while. I'm going to close it. We'll recreate it if we see the error again.
