### ISSUE TITLE
Use step functions to orchestrate sync'ing of entire bundles

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-store#1130]
Ensure that bundle manifest is copied last. Permanent fix for #1115.

Eliminate hack that repeatedly lists the parts in an ongoing multi-part file copy in order to determine if all parts have been copied.

**Comment by mweiden** [comment]
@kislyuk there were recent changes to the `dcplib` code for determining s3 multipart upload.
* The multipart upload chunk size is now determined by [this function](https://github.com/HumanCellAtlas/dcplib/blob/master/dcplib/s3_multipart.py#L14)
* The [`ChecksummingBufferedReader`](https://github.com/HumanCellAtlas/dcplib/commit/574640c8da685f290df7d546163876c1c811e91b) needs to be configured with that chunk size (see [example](https://github.com/HumanCellAtlas/dcp-cli/commit/c6ef9a948a36b2d6cf494e923b58662b448fb46d))
