### ISSUE TITLE
Verifying end to end checksumming

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#1144]
## Need (user story)
* As a user of the consumer API and CLI
* I expect my download to have its checksums verified as part of the process and have an error returned if they don't match
* so that I know the data is correct.

## Definition of Done
- [x] Confirm upload checksums are verified against local data (provided as an option in the CLI, check to see if this can be done in the API)
- [x] Confirm downloaded data is verified against data in the replica (provided as an option in CLI)
- [x] Confirm that data synced between the replicas have checksums matched

**Comment by kozbo** [comment]
Note: an end user requested access to the checksum values so that they could double check their downloads (they were given the "hca dss get_bundle" solution). It would have been nice to say that we had already checked the files as part of their download.

I have added this issue to the Pilot Phase release.

**Comment by ttung** [comment]
https://github.com/HumanCellAtlas/dcp-cli/commit/61270914a803230be4d9d3b667cd95a4c5cedec1

this checksums the data downloaded.

**Comment by kozbo** [comment]
This is already done, closing. We should open a separate ticket to document end to end integrity behavior.
