### ISSUE TITLE
Create data integrity and security doc

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#1167]
# Need

Regards threats and mitigations for data integrity control. We need to document and review the following.

1. IAM policy strategy (denying deletion access by default)
2. Deletion daemon architectural review
3. Consider enabling object versioning in s3 for integrity control
4. Sync daemon architecture review

# Definition of done

The document is created, reviewed by the team, and tickets resulting from the process are created.

**Comment by kozbo** [comment]
Describe our data protection strategy for the DCP

**Comment by Bento007** [comment]
This will tie heavily into meeting FedRAMP requirements.

**Comment by Bento007** [comment]
# Link to the doc 
https://docs.google.com/document/d/1MCtuisKaEswxgsbFKYx-sGQ6nl0HNi03AUzgwoK5dAo/edit?usp=sharing

**Comment by mweiden** [comment]
I've reviewed the doc and confirm that it covers the topics we need it to.

**Comment by Bento007** [comment]
The data integrity and security doc resulted in this epic #1672
