### ISSUE TITLE
error with Preview download script 

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#1168]
From end user:

Apr 17, 23:00 MST

Good day,

I tried to use the hca-download-melanoma script and was unsuccessful. When the department's server administrator tried it, he had no problems. Does the user running the script need to have administrator permissions? I have a custom install of Python in a directory I can write to and it's in my PATH variable.

My log file ends with the error message

OSError: [Errno 1] Operation not permitted: '/dskh/nobackup/biostat/software/Python/lib/python2.7/site-packages/six.pyc'

however, that file has read, write and execute permissions for the biostat users group

$ ls -l /dskh/nobackup/biostat/software/Python/lib/python2.7/site-packages/six.pyc
-rwxrwx--- 1 biostat biostat 30210 Apr 18 12:50 /dskh/nobackup/biostat/software/Python/lib/python2.7/site-packages/six.pyc

and I am a member of biostat group

$ groups
stgrad biostat

My colleague also tried this script. It worked the first time for her, but she stopped and tried to restart the download by running the script again. It failed the second time and she had to modify the code by commenting out the lines to install HCA and a couple of other changes to make it work. I hope that it will be possible to download the data without depending on dozens of Python packages in the future. Ideally, there would be a simple scp or rsync command that could be used or otherwise something graphical and interactive like the Genomic Data Commons Data Portal.

**Comment by hannes-ucsc** [comment]
This issue was moved to HumanCellAtlas/dcp-cli#118
