### ISSUE TITLE
Production Smoke Test

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/data-store#1199]
# User story (Why?)
As a DCP operator,
I want to know if the production deployment can process core API requests
to know if the service is truly available. This test should not generate any test data.

# DoD (What?)
A production smoke test is in place which performs the following operations
 - [x] Upload a bundle
 - [x] Delete a bundle
 - [x] Download a bundle
 - [x] Subscribe
- [x] Unsubscribe
- [ ] Receive notifications
 - [x] Find a bundle
 - [x] Checkout a bundle

**Comment by amarjandu** [comment]
## Notes 4/9/19 : 1:35 PM

### Complete
implemented most of the testing, with the exception of the notification system.
unable to test notifications without generating data; passive notification might be available, but might hold processes in a waiting state. 

### In Progress
NA, in review
### TODO

### Awaiting
Review from team
