### ISSUE TITLE
Create "Demo" deployment for Marcus

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#1236]
DoD - 
Marcus can easily ingest data into and run tests on a valid Data Store deployed to a Demo environment

**Comment by kislyuk** [comment]
I think to simplify things, we should ask Marcus to use the staging environment for this.

**Comment by kislyuk** [comment]
I spoke to Marcus, and he is fine with using staging for this (he has been using integration, but it's more liable to having its data cleared).

**Comment by xbrianh** [comment]
@mweiden Presumably the aws/google demo accounts are not needed any longer.
