### ISSUE TITLE
Generalize reaper to retry any lambda invocation

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/data-store#1264]
Until we create a mechanism for an ordered sync of files in a bundle, or at least a mechanism that guarantees that the manifest is copied last, the indexer would benefit from more than the three built-in retries by lambda. During the F2F we've seen a couple of cases where the manifest was synced, several minutes before the last metadata file was synced. The indexer invocation triggered by the bundle manifest failed due missing metadata files. The built-in retries were exhausted before the last metadata finally appeared in the replica.

Other daemons might benefit from more persistent retries as well: copy, sync and checkout come to mind.

Currently AFAICT, the reaper only retries StepFunction executions, and only those triggered by an SNS message formatted in a particular way. We should generalize the reaper to being able to retry regular Lambda invocations, like `dss-index` and `dss-sync` as well as extend it to step functions like `dss-gs-copy-sfn` and `dss-checkout`.

**Comment by kozbo** [comment]
@xbrianh is this still a concern? should we close this?

**Comment by melainalegaspi** [comment]
Closed by #1554
