### ISSUE TITLE
Add ability to select search and subscribe backends

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/data-store#1267]
## Need (user story)
As a user of the DSS API
I want to select my index backend of choice on the `POST /v1/search` and `PUT /v1/subscriptions` endpoints
so that I can query DSS data in the query language I prefer.

## Approach
Add a query parameter to the `POST /v1/search` and `PUT /v1/subscriptions` that selects an indexer from the possible index plugins.

**Comment by mweiden** [comment]
This is a duplicate. Closing it.

**Comment by hannes-ucsc** [comment]
Dupe of what ticket?

**Comment by mweiden** [comment]
@hannes-ucsc subtickets of this Epic. They may need some love https://github.com/HumanCellAtlas/data-store/issues/906

**Comment by hannes-ucsc** [comment]
This is a better description of that functionality. I closed #1011 in favor of this one.

**Comment by mweiden** [comment]
@hannes-ucsc sounds good. So long as there is only one

**Comment by mweiden** [comment]
Given that we are moving indexers out of DSS and into the query module this ticket is out of scope. Closing this.
