### ISSUE TITLE
Need to change describedBy to describedby

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#1271]
This change, proposed by @danielvaughan, is required to continue supporting the ingest of data into the Data-store from Ingest. 

## Definition of Done
- Support both `describedBy` and `describedby` for schema validation.
- Update unittest to test `describedby`
- Demonstrate the ingest of bundle using `describedby`

**Comment by hannes-ucsc** [comment]
I think we should have coverage for both spellings. OTOH, we shouldn't don't just duplicate a whole bunch of tests for both spellings. Maybe there is a way to sprinkle both spellings over the existing test base and call it a day.

**Comment by danielvaughan** [comment]
Yes, this is similar to a conversation we had:

- make the match case insensitive
- support both `describedby` and `describedBy`
- support only a`describedby`. 

My view is keeping a match with describeBy is safer but messier. We are currently going for `describedby` support alone so we catch everything.

**Comment by hannes-ucsc** [comment]
@daniwelter mentioned on `#hca-metadata` that this effort has been called off.

**Comment by kozbo** [comment]
closing
