### ISSUE TITLE
Support for new file-per-entity bundle structure

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-store#1284]
Example bundle here: https://github.com/HumanCellAtlas/data-bundle-examples/tree/bundle_proposal/version5/10x_v2/multifile_bundle/ischaemic-sensitivity/type_as_filename

Waiting for official RFC from @tburdett and @simonjupp.

From conversations with them this is what I think we'll end up needing to do.

**Comment by kozbo** [comment]
@hannes-ucsc can you review the tickets in this epic? I am wondering if they are required for supporting the new bundle structure, or maybe they have been completed via Brian's work.

**Comment by xbrianh** [comment]
Closed via #1469
