### ISSUE TITLE
Add CHANGELOG and RELEASE_NOTES

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-store#1287]
To aid the release manager and deputy release managers, we need to start maintaining 

- a change log that lists the changes and mentions any manual/non-standard steps to perform before or after deploying those changes to a stage and

- a file containing release notes that documents externally visible changes for our customers/users

A PR that introduces these two files will soon follow.

cc: @sampierson @kislyuk

**Comment by xbrianh** [comment]
This appears to be resolved. See, for example:
https://github.com/HumanCellAtlas/dcp/blob/integration/components.yml
