### ISSUE TITLE
Renew Checkouts to Managed Buckets

### ISSUE THREAD

**Issue by xbrianh** [HumanCellAtlas/data-store#1289]
Lifecycle rules are applied to managed buckets for the checkout service. Object lifecycle should be reset when data is re-checked-out.

**Comment by kozbo** [comment]
Does this qualify as a bug? If so then what are the ramifications if it is not fixed?

**Comment by kozbo** [comment]
@ttung is this fixed via your implementation?

**Comment by ttung** [comment]
will be.
