### ISSUE TITLE
Need test coverage for multipart sync across replicas.

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#1290]
connects to #1277

The following tests need to be completed to verify multiple sync copies work correctly.
https://github.com/HumanCellAtlas/data-store/blob/620980424352e92ad141416df4a9a4f57d95c664/tests/test_sync.py#L140-L148

**Comment by kozbo** [comment]
#1130

**Comment by xbrianh** [comment]
These tests appear covered in the new `sync` daemon. What remains is creating a scheduled GitLab job to run `test_sync_large_blob`.
