### ISSUE TITLE
Investigate API Gateway Timeouts during high loads

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#1300]
### AWS Support ticket:
https://console.aws.amazon.com/support/v1#/case/?displayId=5101082101&language=en

### Graph of the Spike
https://metrics.dev.data.humancellatlas.org/d/F9svZvSik/dss-dev-scale-test-spike?orgId=1 

### Xray traces
https://console.aws.amazon.com/xray/home?region=us-east-1#/service-map?timeRange=2018-05-30T14:00:00Z~2018-05-30T14:20:00Z

### Cloudwatch Logs
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logStream:group=/aws/lambda/dss-dev;prefix=2018/05/30;streamFilter=typeLogStreamPrefix

**Comment by Bento007** [comment]
In some cases the dss-dev lambda takes >30 seconds to complete. I couldn't find any traces that showed a request taking >30. We may need to add additional instrumentation to find out where the time being spent.

**Comment by Bento007** [comment]
This logged event took 50sec from an API-gateway call.
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/lambda/dss-dev;stream=2018/06/05/%5B$LATEST%5D03f860b929f84d5f84d7550c9bc70643;refid=34080487634069493873104016217204606658262760580274389138;reftime=1528221919522

**Comment by Bento007** [comment]
I suspect this is being cause by a lambda being cold started. The burst load produced by the load test caused additional lambdas to be spawned which need time to spawn. This causes requests to timeout until an additional lambda spawns.

The [graph](https://metrics.dev.data.humancellatlas.org/d/F9svZvSik/dss-dev-scale-test-spike?orgId=1&from=1528248614345&to=1528249199725&var-interval=5m) shows the load gradually increasing, and the latency increasing with it. The latency peaks and requests begin to timeout while another lambda is spawned. Once the additional lambda spawns the latency quickly drop back down.

**Comment by Bento007** [comment]
> We need to also look into the timeout logic of the chalice/app and ensure that it isn't exceeding 30sec (28 seconds to be safe)

The dss chalice app's timeout needs to be lowered down to 28 seconds. This will make the app timeout quicker and more lambdas will be spawned sooner. 

We need to also remove the retry logic from the chalice app.

**Comment by Bento007** [comment]
The dss with lambda timeout set to 28 seconds under load: [graph](https://metrics.dev.data.humancellatlas.org/d/F9svZvSik/dss-dev-scale-test-spike?orgId=1&from=1528251754084&to=1528253968156&tab=metrics&var-interval=5m)

**Comment by Bento007** [comment]
This xray trace shows that initialization took 43.7 seconds
https://console.aws.amazon.com/xray/home?region=us-east-1#/traces/1-5b1b0c85-7cd37c4ca653be44da3ea892

**Comment by Bento007** [comment]
I increased the memory for the dss-api lambda from 128mb to 512mb and the error appears to have vanished! This was after reading a post online, I'll find the link and post it later, saying the increasing the memory can resolve issues with lambdas starting.

**Comment by Bento007** [comment]
For the following test:
- xray traces enabled
- debug logs enabled

### Test 512mb 500 users 10per/sec
- Locust settings: 500 users, 10 users/second, download medium bundle.
- dss-api with 512MB memory
- [results](https://metrics.dev.data.humancellatlas.org/d/F9svZvSik/dss-dev-scale-test-spike?orgId=1&from=1528508739433&to=1528509409225&tab=display&var-interval=1m)
- requests per second = 38.4 max, 35.7 average

### Test 512mb 1000 users 10per/sec
- Locust settings: 1000 users, 10 users/second, download medium bundle.
- dss-api with 512MB memory
- [results](https://metrics.dev.data.humancellatlas.org/d/F9svZvSik/dss-dev-scale-test-spike?orgId=1&from=1528509569419&to=1528510245495&tab=display&var-interval=1m)
- per second = 52 max, 46.9 average

### Test 256mb 500 users 10per/sec
- Locust settings: 500 users, 10 users/second, download medium bundle.
- dss-api with 256MB memory
- [results](https://metrics.dev.data.humancellatlas.org/d/F9svZvSik/dss-dev-scale-test-spike?orgId=1&from=1528510498553&to=1528511282286&tab=display&var-interval=1m)
- requests per second = 36 max, 32.8 average

### Test 256mb 500 users 100per/sec
- Locust settings: 500 users, 100 users/second, download medium bundle.
- dss-api with 256MB memory
- [results](https://metrics.dev.data.humancellatlas.org/d/F9svZvSik/dss-dev-scale-test-spike?orgId=1&from=1528511262766&to=1528511829034&tab=display&var-interval=1m)
- requests per second = 44.8 max, 25.5 average

### Test 128mb 500 users 10per/sec
- Locust settings: 500 users, 10 users/second, download medium bundle.
- dss-api with 128MB memory
- [results](https://metrics.dev.data.humancellatlas.org/d/F9svZvSik/dss-dev-scale-test-spike?orgId=1&from=1528511665321&to=1528512565321&tab=display&refresh=5s&var-interval=1m)
- requests per second = 31.1 max, 23.2 average

**Comment by Bento007** [comment]
### Test 512MB 1000 Users 100 per/sec
- Locust settings: 100 users, 100 users/second, download medium bundle.
- dss-api with 512MB memory
- [results](https://metrics.dev.data.humancellatlas.org/d/F9svZvSik/dss-dev-scale-test-spike?orgId=1&from=1528728863383&to=1528729401916&tab=metrics&var-interval=1m)
- requests per second = 75 max, 50 average

**Comment by Bento007** [comment]
> This logged event took 50sec from an API-gateway call.
> https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/lambda/dss-dev;stream=2018/06/05/%5B$LATEST%5D0bf4059f16b341a98a6b5047bd2ac407;filter=%22dd6c5334-68ea-11e8-8b6b-83f5c2e96a90%22

An interesting point to note is that the request above only use 82MB of memory. So a lack of memory wasn't a problem.

> REPORT RequestId: dd6c5334-68ea-11e8-8b6b-83f5c2e96a90	Duration: 49553.78 ms	Billed Duration: 49600 ms Memory Size: 128 MB	Max Memory Used: 82 MB	

What this tells me is that increasing the memory of the lambda fixed the problem by providing more CPU not by providing more memory.

**Comment by Bento007** [comment]
cloudwatch filter to find long running lambdas ```[reportLabel="REPORT", requestIdLabel="RequestId:", reqid, dl, d, dms, bl="Billed", bdl, dur>10000, ...]```

**Comment by Bento007** [comment]
Current theory is the issues is cause by requests interrupting the initialization of the lambda. This could be cause by the timeout logic which delegates a request to a separate thread while the lambda is still finishing initialization. 

I have to solutions to try and fix and verify this:

1. Remove the timeout logic and run the scale test.
1. Move the initialization of dispatch to the bottom of `get_chalice_app`.

I will also be adding additional log messaged to the chalice app initialization.

**Comment by Bento007** [comment]
The api-gateway time out was ultimately cause by slow imports in the lambda when under loads. The libraries that where slow to import were `boto3`, `requests`, `dss`, and `flask`. The image bellow is from CloudWatch of a lambda performing slowly under load.

<img width="720" alt="screen shot 2018-06-13 at 2 01 03 pm" src="https://user-images.githubusercontent.com/1429913/41377890-52f94d32-6f12-11e8-8624-709afae15568.png">

You can see that the lambda start to initialize with some imports taking as long as 8 seconds. In total the lambda was given about 10 seconds to initialize before a request interrupted the initialization process. Once the request was received the initialization process started over based on the picture bellow.

<img width="691" alt="screen shot 2018-06-13 at 2 04 32 pm" src="https://user-images.githubusercontent.com/1429913/41378053-c48885b2-6f12-11e8-9d5c-d495c644e9c4.png">

The imports continued to take a significant amount of time. Once the app is ready the lambda does need to perform these steps again and all subsequent requests are fast. The image bellow shows that the request took rough 2 seconds to complete after the app was ready.

<img width="743" alt="screen shot 2018-06-13 at 2 07 02 pm" src="https://user-images.githubusercontent.com/1429913/41378252-5ddd1264-6f13-11e8-98b4-5ad414be442f.png">

Here is a summery of all of the requests handled by this lambda.

<img width="900" alt="screen shot 2018-06-13 at 2 11 36 pm" src="https://user-images.githubusercontent.com/1429913/41378374-bdedb2bc-6f13-11e8-86df-21c372d58e27.png">

The first one took the longest at 51700ms. The following request took at most 800ms.

**Solutions**
- Optimizing imports
- Increasing memory resources to lambda
- Add retry later logic to the cli.

**Comment by Bento007** [comment]
Increasing the memory resource will fix will speed up the initialization of the lambda but will also same all subsequent requests more expensive.

**Comment by Bento007** [comment]
Here is the request duration distribution of the dss-api lambda with a burst load. A search operation was performed with a peak qps of 66.8.

<img width="414" alt="screen shot 2018-06-14 at 5 01 03 pm" src="https://user-images.githubusercontent.com/1429913/41444102-b75825da-6ff5-11e8-8c93-fd829552224f.png">

These are the requests that succeeded

<img width="421" alt="screen shot 2018-06-14 at 5 01 55 pm" src="https://user-images.githubusercontent.com/1429913/41444126-d6e05922-6ff5-11e8-94ab-e1b98ffc9288.png">

These are the requests that timed out.

<img width="413" alt="screen shot 2018-06-14 at 5 02 17 pm" src="https://user-images.githubusercontent.com/1429913/41444134-e64c0b90-6ff5-11e8-860c-3bf01660e1b3.png">

**Comment by Bento007** [comment]
@mweiden I think the best solution is to do nothing, and at a later time refactor our imports to prevent this long start up. In the mean time users will experience a temporary timeout error if a burst load is encountered. We should also mention to power users to use retry logic in their code.

**Comment by mweiden** [comment]
@Bento007 OK fair enough. In this case, I would close this issue and the memory PR https://github.com/HumanCellAtlas/data-store/pull/1307#pullrequestreview-129003592.
