### ISSUE TITLE
`make deploy` does not detect missing wheels

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-store#1302]
When wheels are missing in vendor.in, for example if a new dependency with C code was added to requirements.txt, `make deploy` should fail on macOS. It does not and instead deploys a Lambda with some dependencies missing. The missing distributions are the wheel but also other, seemingly unrelated distributions from `requirements.txt`.

To reproduce on macOS, 

1) `rm -rf vendor.in/wrapt==1.10.11`
2)  `make -C daemons dss-admin`
3) `scripts/admin-cli.py index --replica=aws --prefix=42 verify`

Expected:

Step 2) should print an error message complaining about the missing wheel

Actual:

Step 2) does not print any warnings or errors. And step 3) fails with an import error in `app.py` occurring remotely during the invocation of the `dss-admin` lambda.

**Comment by melainalegaspi** [comment]
@amarjandu pls verify if this problem is addressed by layering

**Comment by amarjandu** [comment]
lambda layering address this by building out the correct dependencies through chalice, this ensures that we are using dependencies that supported by the container image that aws uses to run the lambda, but it also ensures we get the correct wheels into the layer no matter what OS the operator is using. 

Currently the DSS does not specify additional binaries in vendor.in, although we keep the folder around. 

see for more https://github.com/HumanCellAtlas/data-store/pull/2168

https://chalice.readthedocs.io/en/latest/topics/packaging.html
