### ISSUE TITLE
Fix subscription races leading to orphaned percolate queries

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-store#1303]
There are a number of races in the code handling the `/subscriptions` route that could lead to orphaned percolate queries, i.e. queries without a corresponding subscription. Thanks to @mikebaumann to pointing them out and proposing a strategy to fix them. 

1) For `PUT /subscription` add the subscription to the ES index first, then register queries. We currently write the query first. If a document is indexed concurrently, it could see the query but not the subscription, failing an assertion in `dss.index.es.backend.ElasticsearchIndexBackend#_notify_subscriber()`. Reversing the order avoids the orphaned query.

2) `DELETE /subscription` remains as it is now: delete query first then subscription. This is the opposite order as for PUT and therefore the right thing to do, again avoiding the orphan.

3) If concurrently to a `DELETE /subscription` request, a document is added that changes the mapping and therefore requires re-registration of all subscription queries (see `dss.index.es.refresh_percolate_queries`), a query already removed by `DELETE /subscription` may be added again, resulting in an orphaned query.  To address this race, we will eliminate the aforementioned assertion on the existence of the subscription `_notify_subscriber` and instead delete the orphaned query that triggered the now unnecessary notification.

If there are any other races we are currently unaware of, measure 3) will eventually remove all resulting orphans.

**Comment by melainalegaspi** [comment]
Not going to fix bc moving to different subscription architecture
