### ISSUE TITLE
Test and review Data Store CLI 

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#1305]
# Why?
As a user I would like to have confidence that the CLI is properly described in the help text and that it functions as described.

# DoD
Go through the basic functions in the Data Store CLI and verify that each command subclass is documented properly and functions as described.

Help pages
http://hca.readthedocs.io/en/latest/

 - [ ] login
 - [ ] logout
 - [ ] download
 - [ ] post-search
 - [ ] get-file
 - [ ] head-file
 - [ ] get-bundle
 - [ ] get-bundles-checkout
 - [ ] post-bundles-checkout
 - [ ] put-subscription
 - [ ] get-subscription
 - [ ] get-subscriptions
 - [ ] delete-subscription
 - [ ] delete-bundle
 - [ ] put-bundle
 - [ ] upload
 - [ ] put-file
 - [ ] any new functions added?

**Comment by kozbo** [comment]
@ogparra can you go through and check off the CLI commands that you have tried? Also, please paste in your general comments and questions to this issue.

**Comment by mweiden** [comment]
@kozbo will move this to the dcp cli repo
