### ISSUE TITLE
Minimal Auth with White list for upload

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#1308]
## Need (user-story)
As a DSS operator
we need a whitelist of users who are permitted to upload bundles in the DSS
so that only approved users can upload.

## Definition of Done
- [x] Collect a list of approved users for upload
- [x] Add whitelist support in the DSS

**Comment by Bento007** [comment]
Adding white list rules as middleware to auth0

**Comment by Bento007** [comment]
currently need to work on fusillade so it can be integrated into bluebox. In order to allow tests to continue to pass in blue box we must also implement service to service auth. This will also require token refresh.
