### ISSUE TITLE
Support Spark-like load demand on the consumer API

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#1322]
## Why
As a user I would like to be able to use a Spark cluster to do parallel access operations against the consumer API. For example I would like to run 100 parallel downloads 

## Definition of Done
The test will be conducted with @briandoconnor's [spark vignette](https://github.com/HumanCellAtlas/data-consumer-vignettes/tree/brian_spark/tasks/SPARK).
- [x] Confirm that there is retry logic in the client of Brian O's vignette
- [ ] ~Run the spark cluster at 100 nodes and record the results~
- [x] 40 node spark scale test

**Comment by mweiden** [comment]
@briandoconnor I ran this with 40 nodes and pretty confident given the dynamics of Lambda that it will scale horizontally.
