### ISSUE TITLE
The `PUT /bundle` response should include the manifest in the response

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-store#1331]
Old title: The `PUT /bundle` response should include the `indexed` property for every file

This would make testing in the CLI easier.

In fact, the response should be structurally identical to the manifest. I don't know why it isn't.

**Comment by kozbo** [comment]
This really means indexable, not indexed.

**Comment by kozbo** [comment]
Add the new field in parallel to the old, we can remove the old one later, depreciate it.

**Comment by Bento007** [comment]
currently `put bundle` only returns the version of the bundle added. We could change it to include the whole manifest, or a subset of the fields in manifest.
