### ISSUE TITLE
appropriate timeout for checkout bucket

### ISSUE THREAD

**Issue by ttung** [HumanCellAtlas/data-store#1346]

**Comment by kozbo** [comment]
Please clarify

**Comment by ttung** [comment]
https://github.com/HumanCellAtlas/data-store/blob/master/infra/buckets/s3_buckets.tf#L31

is 30 days the right number?

**Comment by mweiden** [comment]
@ttung this is currently 7 days. I think that profiling this will be subject to understanding our usage patterns post-pilot.

**Comment by ttung** [comment]
To make @calvinnhieu's optimizations useful, I think this likely has to be extended.  However, the advertised TTL being ~7 days is not unreasonable.
