### ISSUE TITLE
indexer spurious failure

### ISSUE THREAD

**Issue by ttung** [HumanCellAtlas/data-store#1370]
https://gist.github.com/ttung/54dbc60f8b56c3a3edc532d24ede6d0c

**Comment by Bento007** [comment]
Relates to #1357

**Comment by Bento007** [comment]
I think this is a problem unique to travis and it has to do with these messages right here https://gist.github.com/ttung/54dbc60f8b56c3a3edc532d24ede6d0c#file-gistfile1-txt-L818-L819.

@ttung let me know if you see these errors in circleCI tests.

**Comment by Bento007** [comment]
I'm going to try adding a check for the index before proceeding with a test based of what these users said https://github.com/travis-ci/travis-ci/issues/3181

**Comment by Bento007** [comment]
Here is the error https://gist.github.com/ttung/54dbc60f8b56c3a3edc532d24ede6d0c#file-gistfile1-txt-L1070-L1090
