### ISSUE TITLE
dss-gs-event-relay sends duplicate object creation events

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#1410]
## Software version (git hash, date, branch)
See for more details https://github.com/HumanCellAtlas/data-store/issues/1386

https://github.com/HumanCellAtlas/data-store/commit/3185753df486969461ac2bc9f629b8e2bf45af32

## Expected behavior
A single notification per matching subscription.

## Actual behavior
When a new bundle is added to the GCP bucket the `dss-gs-event-relay` send 3 notification to `dss-sync` for AWS and `dss-index` for AWS. The `dss-gs-event-relay` always sends 3 notifications to AWS even when notifications are successful. This results in multiple bundle AWS sync and indexing events which can result in multiple subscription notification being sent to subscribers.

In the following doc you will notice for every single bundle creation originating from google there are 3 separate invocations of the `dss-indexer` 
https://docs.google.com/spreadsheets/d/1Agr5GbI4j1tTQbzwHmxL-PS6UX2Nm5u24MbjLXvKIy8/edit?usp=sharing

## Steps to reproduce the behavior
upload a bundle to a GCP bucket. You will notice that 3 `dss-indexer` events are triggered.

**Comment by hannes-ucsc** [comment]
I wouldn't use the term *notification* here. The primary duplication seems to be that of the *object created event* for S3, coming in to the indexer via SNS notification in either replica. That it also causes a duplicate notification is secondary.

**Comment by Bento007** [comment]
- [ ] Look at google subscription bucket settings
- [ ] Look at gs-event-relay-lambda
- [ ] Look at aws sns for duplications.

**Comment by xbrianh** [comment]
AFAICT we should be prepared to deal with duplicate messages whether or not there's duplication bug in `dss-gs-event-relay`. AWS does not make any guarantees that a message will be delivered only once.

See `How many times will a subscriber receive each message?` here:
https://aws.amazon.com/sns/faqs/

**Comment by Bento007** [comment]
updated documentation instructing users to handle duplicate notifications #1622
