### ISSUE TITLE
Install requirements failed

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#1439]
## Software version (git hash, date, branch)
commit: https://github.com/HumanCellAtlas/data-store/commit/d4bff8babed9b74189441a48e166f0b5e5404464

Build: https://travis-ci.com/HumanCellAtlas/data-store/builds/79635411

## Expected behavior
If setup fails retry once more time.

## Actual behavior
If setup fails, the build fails.

## Steps to reproduce the behavior
This is an intermittent issues that can be resolved by implementing a retry if setup fails.

**Comment by Bento007** [comment]
this is an upstream issues. Boto happened to be updated at the same time as installing the requirements.

**Comment by hannes-ucsc** [comment]
On CircleCI the image is built once for each branch and then reused for every build until any of the image inputs are touched. This might decouple us from PyPI outages (which is what I think this is, not a race).
