### ISSUE TITLE
scale test for PUT /bundles

### ISSUE THREAD

**Issue by ttung** [HumanCellAtlas/data-store#1467]
PUT /bundles is a synchronous operation now.  That means there is probably a limit to the number of files that can be in a bundle.  This should be tested and quantified.  An internals redesign may be sufficient to raise the limit, but if that is not, then an API redesign (to be asynchronous) may be necessary.

**Comment by kozbo** [comment]
This has been established at ~1000 files. The API gateway times out at that point
