### ISSUE TITLE
post_search errors with output_format='raw' in integration and staging

### ISSUE THREAD

**Issue by jnkrupp** [HumanCellAtlas/data-store#1473]
## Software version (git hash, date, branch)
Latest commit [3c30447](https://github.com/HumanCellAtlas/dcp-cli/commit/c6ef9a948a36b2d6cf494e923b58662b448fb46d)  on Jun 30
## Expected behavior
Search for bundles with `raw` output format in integration or staging and get results as normal.
## Actual behavior
When the user attempts to execute `post_search` with `output_format='raw'` in integration or staging, it throws a SwaggerAPI Exception and returns no bundles. This exception can be avoided by adding a range to the Elasticsearch query, specifying `manifest.version` to be greater than or equal to `2018-07-12T100000.000000Z` for integration, or `2018-06-18T100000.000000Z` for staging. If the user adds this range to the query, bundles are returned as normal.
```
---------------------------------------------------------------------------
SwaggerAPIException                       Traceback (most recent call last)
<ipython-input-27-c231f5cffd73> in <module>()
      1 import json
      2 
----> 3 search_results = client.post_search(es_query={}, replica='aws', output_format='raw')
      4 print(search_results['total_hits'])

~\Anaconda3\lib\site-packages\hca\util\__init__.py in __call__(self, client, **kwargs)
    146 
    147     def __call__(self, client, **kwargs):
--> 148         return self._consume_response(self._request(kwargs))
    149 
    150     def _cli_call(self, cli_args):

~\Anaconda3\lib\site-packages\hca\util\__init__.py in _request(self, req_args, url, stream, headers)
    134                               timeout=self.client.timeout_policy)
    135         if res.status_code >= 400:
--> 136             raise SwaggerAPIException(response=res)
    137         return res
    138 

SwaggerAPIException: None: None (HTTP 502). Details:
{"message": "Internal server error"}
```
## Steps to reproduce the behavior
Execute a search with `output_format='raw'` in integration/staging for any bundles (even `es_query={}` throws the error).

**Comment by jnkrupp** [comment]
This might be fixed when the data store is cleaned out and the bundles with the old formatting are removed, since the cause could be due to bad bundles hiding somewhere.

**Comment by Bento007** [comment]
fixed! the issues was cause by trying to return to much data at once. This was fixed by limiting the results returned to 10 when outout_format=raw
