### ISSUE TITLE
Migrate DSS upload whitelist to Auth0

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/data-store#1480]
# Need

The upload whitelist described in https://github.com/HumanCellAtlas/data-store/issues/1308https://github.com/HumanCellAtlas/data-store/issues/1308 should be implemented using Fusillade and its Auth0 integration.

# Definition of done

- [x] Update the blue box to use JWT for authentication
- [x] Add support for jwt in connexion https://github.com/zalando/connexion/issues/607
- [x] Convert use of google auth token to JWT bearer token https://developers.google.com/identity/protocols/OAuth2ServiceAccount

**Comment by Bento007** [comment]
- [ ] update the security wiki readme with instructions on making service to service tokens
- [ ] update data-store readme with new environment variables
