### ISSUE TITLE
Create a Runbook for DSS in the BuidBox wiki

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/data-store#1481]
# User Story

* As an operator of the Data Storage Service
* I want a document that describes symptoms of common issues operating DSS and instructions on how to fix each
* So that I can keep the DSS available.

# Definition of Done
Create a Runbook on the BuildBox wiki for DSS. It should--at least--cover the following issues.

- [x] Reindexing
- [x] Deletion
- [x] Elasticsearch overflowing; upgrading elasticsearch
- [x] Using the big red button
- [x] Release procedure
- [x] Consistency check and recovery

Each should have a subsection for the following

1. Symptoms of the problem
2. A link to metrics or logs (if available) for diagnosing that problem
3. Remediation steps

**Comment by mweiden** [comment]
@xbrianh @Bento007 please review and send feedback on this [draft](https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/data-store/wikis/Runbook)

Please add anything you think is missing and indicate if you approve of this as Done.

**Comment by kozbo** [comment]
`# Set your AWS_PROFILE
source virtualenv/bin/activate`
Do we explicitly instruct the user to set up a virtual environment?

`./scripts/admin-cli.py`
Andrey suggested a rename in slack: "can we rename scripts/admin-cli to scripts/dss-ctl and roll this script (dss-start-stop) into dss-ctl?"

What if the index repair fails too? Is there a way to delete the index and rebuild it from scratch?

I expect that Brian and Trent will have more comments.

Thanks for putting this together!

**Comment by xbrianh** [comment]
This looks good to me.

**Comment by Bento007** [comment]
LGTM

**Comment by kozbo** [comment]
Please close once you have incorporated the changes requested.
