### ISSUE TITLE
Move DSS whitelist to AWS Secrets Manager or Auth0

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/data-store#1487]
# User Story

* As an operator of the DSS
* I would like the whitelist secrets to be stored in AWS Secrets Manager or Auth0
* so that no sensitive identifiers are stored in the repository and that others can deploy the code without inheriting vestigial configuration.

# Definition of done

- [x] Access to subscriptions are stored in `DSS_SUBSCRIPTION_AUTHORIZED_DOMAINS_ARRAY` are removed or stored in Secrets Manager (removal case depends on https://github.com/HumanCellAtlas/data-store/issues/1486)
- [ ] Admin user emails (`ADMIN_USER_EMAILS`) are stored in AWS Secrets Manager

**Comment by Bento007** [comment]
When deploying changes to auth0 import the whitelisted email domain and admin email  from secrets and add it to the rules.

**Comment by Bento007** [comment]
removed `DSS_SUBSCRIPTION_AUTHORIZED_DOMAINS_ARRAY` variable

**Comment by Bento007** [comment]
Where do we currently store `admin-emails`

**Comment by Bento007** [comment]
Change admin list to a group and store in auth0

**Comment by mweiden** [comment]
@Bento007 this is where it's used: https://github.com/HumanCellAtlas/data-store/blob/master/dss/api/bundles/__init__.py#L243-L244

**Comment by Bento007** [comment]
I need to check of this is actually need considering we have dcp-infra which maintains a whitelist of admin users.

**Comment by Bento007** [comment]
I need to close this and create new tickets to remove the admin operations from the API.

**Comment by Bento007** [comment]
See #1736
