### ISSUE TITLE
Add error messages to swagger

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#1491]
## User story
* As a use of the API
* i would like to know what errors to expect when using the API
* so that I can handle those errors.

@ttung 
> we need to write better documentation for our error responses.  Don’t dump all the error codes into `default`, and there are two error codes all endpoints must present as possible errors (`unhandled_exception` and `illegal_arguments`)
> 
> here’s an example of what I think we should be doing.  https://github.com/HumanCellAtlas/data-store/pull/1490/files

## Definition of done
- Update the swagger document to include expected error responses.

**Comment by mweiden** [comment]
@Bento007 has this already been completed? Close if so.
