### ISSUE TITLE
Review Python module dependancies - August

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#1492]
# Why
As a developer of the Data Store, I want to stay relatively up-to-date with the latest versions of the dependent Python modules, so I can pick up new features, security fixes, etc.  Upgrading a large number of dependencies by a lot of versions can create problems that are very difficult to pin down.  It is easier to continuously upgrade dependencies to minimize the pain.

As a user of the Data Store, I expect that the Data Store is secure.  That means it should use relatively recent versions of dependent Python modules.

# DoD
Review all pinned Python modules and see if we are out of date on any.
Then review the new module WRT to correctness and security
Update pinned versions as appropriate

**Comment by kozbo** [comment]
@ttung Does this capture your request? We can clone this each month.

**Comment by ttung** [comment]
I think it basically does.  I edited the motivation a bit.  Thanks so much!
