### ISSUE TITLE
date-time fields are not verified by jsonschema

### ISSUE THREAD

**Issue by ttung** [HumanCellAtlas/data-store#1493]
Fields typed `date-time` in the swagger spec are not validated by jsonschema.  The jsonschema python library has a soft dependency on the [strict_rfc3339 python module being installed](https://python-jsonschema.readthedocs.io/en/latest/validate/) to validate date-time fields.[1]

In any case, we don't really produce a valid rfc3339 timestamp (we remove a colon and substitute it with a different character), so we shouldn't rely on jsonschema checking the fields.  Instead, we should be validating them in code like in https://github.com/HumanCellAtlas/data-store/pull/1485.

[1] https://github.com/Julian/jsonschema/blob/5411305d82c7505c89b0d835b5c1aed59cb255c3/jsonschema/_format.py#L221

**Comment by Bento007** [comment]
replaced by #1548
