### ISSUE TITLE
Nuke Circle CI or Travis CI

### ISSUE THREAD

**Issue by xbrianh** [HumanCellAtlas/data-store#1509]
We have three CI environments: Travis, Circle CI, and the Build Box. Only one of the public-facing environments (Travis, Circle CI) should be retained.

**Comment by hannes-ucsc** [comment]
Circle CI has two main advantages. We can use a newer Ubuntu distro and eliminate most of the customizations we have to do on Travis which is still stuck on Trusty. Circle also lets you SSH into the build container for diagnostics.
