### ISSUE TITLE
Fill in November demo plan document and begin organizing Pilot Integration Testing meeting

### ISSUE THREAD

**Issue by briandoconnor** [HumanCellAtlas/data-store#1511]
See the script doc I've started:  https://docs.google.com/document/d/1EAulvcSrOrT1Z58lYquyZuz1Zg2iWqGo3qiD3zL7nBc/edit#

**Comment by kozbo** [comment]
This is well on it's way through work by Brian, Laura, Tim, and Trevor.
https://docs.google.com/document/d/1PV3XoDxYHXQvLU4i6gcbaLBVT0Blq_5TjbOTenfI2v8/edit#heading=h.te2nou6px7ig
I am not working directly on this, and it is not a Blue box task.

**Comment by kozbo** [comment]
Issue moved to [HumanCellAtlas/dcp #136](https://github.com/HumanCellAtlas/dcp/issues/136) via [**ZenHub**](https://www.zenhub.com/)
