### ISSUE TITLE
Fix GS bucket regions

### ISSUE THREAD

**Issue by xbrianh** [HumanCellAtlas/data-store#1518]
GS buckets have heterogenous regions and storage classes that the infra deploy system must accommodate. Buckets should be migrated to a consistent region.

dev bucket: Regional US-CENTRAL1
staging bucket: Multi-Regional  US
test bucket: Regional US-EAST1

**Comment by ttung** [comment]
Please verify that none of the existing tests depend on the buckets being in different regions. :)

**Comment by Bento007** [comment]
The buckets should all be multi-region US

**Comment by xbrianh** [comment]
This will require region migration, which involves:
1. Announce to effected parties
2. Shut down `stage`
3. Create a temp bucket
4. Copy data from `stage` bucket to temp bucket
5. Delete `stage` bucket
6. Create new `stage` bucket with correct configuration
7. Copy data from temp bucket to `stage` bucket
8. re-start `stage`

**Comment by Bento007** [comment]
How long do you think this will take, hours, days, weeks?
