### ISSUE TITLE
If the GCF is throttled, does sync fail?

### ISSUE THREAD

**Issue by xbrianh** [HumanCellAtlas/data-store#1521]
GCP -> AWS sync is driven by a Google Cloud Function (GCF), which reacts to object events on the Google bucket. For large rates of object events, throttling of the GCF has been observed. When this occurs, does sync fail?

**Comment by Bento007** [comment]
[GCP delivery_guarantees](https://cloud.google.com/storage/docs/pubsub-notifications#delivery_guarantees)
