### ISSUE TITLE
date-time validation in swagger is not useful

### ISSUE THREAD

**Issue by ttung** [HumanCellAtlas/data-store#1548]
1. should remove all instances of date-time in `dss-api.yml` and replace with str.
2. everywhere a parameter is expected to be date-time, we should parse the str into the logical timestamp, and then format it back to our normal version format using `dss.util.version.datetime_to_version_format`.  if the date-time doesn't match, then throw a bad_request.

**Comment by Bento007** [comment]
is this related to #1493

**Comment by ttung** [comment]
Let's close #1493.  It has a non-trivial logical gap in that the `iso8601` library will accept dates that do not match our version format.

**Comment by ttung** [comment]
Also, you are super awesome, @Bento007!  You always remember the issues that have been opened before and I always forget.  :(
