### ISSUE TITLE
Improve error logging on smoketests

### ISSUE THREAD

**Issue by calvinnhieu** [HumanCellAtlas/data-store#1557]
## User story
* As a developer
* I want to run `make smoketest`
* and see error stacktraces in the DSS logs if they occur

## Definition of done
Error stacktraces that occur during smoketests are visible in Cloudwatch and Kibana

**Comment by amarjandu** [comment]
pushed modification for working verbose smoketest in console, currently gitlab does not output data to cloudwatch or kibana for CI/CD testing.

**Comment by amarjandu** [comment]
Added support for header AWS-Request-ID which contains the lambda requestID which is returned in responses, this allows reference to the logs to search for failures.

There might want to be extra support added to present this information to the end user, so they can present that information in a support ticket. This information could be presented in the CLI with log_level:INFO

**Comment by amarjandu** [comment]
Moved to PR: #1845
