### ISSUE TITLE
Write documentation describing all environment variables

### ISSUE THREAD

**Issue by calvinnhieu** [HumanCellAtlas/data-store#1593]
## User story
* As a developer
* I want to have documentation
* that describes all environment variables in the data-store

## Definition of done
A Markdown document that describes all environment variables in the data-store

**Comment by Bento007** [comment]
Where is this document

**Comment by calvinnhieu** [comment]
Woops: https://github.com/HumanCellAtlas/data-store/tree/master/docs/environment
