### ISSUE TITLE
Update documentation that walks a user through configuring the HCA CLI with a local DSS API

### ISSUE THREAD

**Issue by calvinnhieu** [HumanCellAtlas/data-store#1594]
## User story
* As a developer
* I want to see up-to-date documentation
* that shows me how to set up the HCA CLI to work with a local DSS API

## Definition of done
* Documentation shows user how to configure the HCA CLI to work with a DSS API on localhost
* Documentation includes a troubleshooting section that cover issues such as SSL errors and managing cached config files

**Comment by kozbo** [comment]
I don't believe that we are missing any of this documentation now. closing.
