### ISSUE TITLE
dss login failure with out of sync swagger.json

### ISSUE THREAD

**Issue by diekhans** [HumanCellAtlas/data-store#1598]
## Software version (git hash, date, branch)
This happens with both
 - pip: hca 4.4.1 (CPython 3.6.6 Darwin-17.7.0-x86_64-i386-64bit) 
 - dcp-cli master checkout: commit d59c02e87f1fae64d37037036e6765ae7ec1e793

## Expected behavior
Open web browser window for login.
## Actual behavior
We browser opens with URL: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=803155065464-8hgbqc16nve9hm78lqrvfbcpv5oh275q.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=openid+email+offline_access&state=OGv6W1SRcUy2Q9bvnQ64oxPXv5wf6c&audience=https%3A%2F%2Fdss.dev.data.humancellatlas.org%2F&access_type=offline

and displays error:
`
400. That’s an error.

Error: invalid_scope

Some requested scopes were invalid. {valid=[https://www.googleapis.com/auth/plus.me, https://www.googleapis.com/auth/userinfo.email], invalid=[offline_access]}

Learn more

Request Details
response_type=code
client_id=803155065464-8hgbqc16nve9hm78lqrvfbcpv5oh275q.apps.googleusercontent.com
redirect_uri=http://localhost:8080/
scope=openid email offline_access
state=OGv6W1SRcUy2Q9bvnQ64oxPXv5wf6c
audience=https://dss.dev.data.humancellatlas.org/
access_type=offline
That’s all we know.
`

## Steps to reproduce the behavior

- install in python virtualenv on Mac with Chrome as default browser
- hca dss login

**Comment by diekhans** [comment]
Thanks.  I changed the title and will leave this open as a ticket to have the hca command validated whe swagger,json

**Comment by diekhans** [comment]
I protest the closing.  This is a user-hostile error message.   At the very least documentation or a message from hca dss login to suggest trying this on failure would be an improvement.

Why is it not possible to check for being out-of-sync?  This seems like a version check to the to my naive way of thinking.

**Comment by diekhans** [comment]
thanks, @hannes-ucsc.  Another common way is to do an http HEAD to get the last modified time.

However, the cached file is around 60K, this hardly seems worth having a cache for, let alone one doesn't behave in a reliable manner.  I would suggest just fetch the swagger.json each time.

**Comment by Bento007** [comment]
this has been fixed in the cli
