### ISSUE TITLE
Async file upload needs to expose state better

### ISSUE THREAD

**Issue by kislyuk** [HumanCellAtlas/data-store#1616]
When an async PUT file fails, the reason for the error is completely opaque. If the copy op fails, the error needs to be forwarded through the API front end.

**Comment by kislyuk** [comment]
cc @ttung

**Comment by Bento007** [comment]
Proposed solution:

- Put file should return 201 when file is copied sync.
- Put file should return 202 when file is copied async.

- rename the step functions to use the file name and version

Get file responses:
- for a file copied return the file link.
- for a file being copied return retry later.
- for a file that failed to be copied return error response from step function.
- for a file this does not exist return file missing.
