### ISSUE TITLE
Lambdas seem to have unnecessary, sweeping Get*/List* permissions.

### ISSUE THREAD

**Issue by DailyDreaming** [HumanCellAtlas/data-store#1623]
These were done for X-ray, however, this should only be necessary for EC2, not lambdas.

Documentation here: https://docs.aws.amazon.com/xray/latest/devguide/xray-permissions.html
AmazonS3ReadOnlyAccess **(Amazon EC2 only)** – Gives the instance permission to download the X-Ray daemon from Amazon S3.

Will be investigating this more and then updating.

**Comment by Bento007** [comment]
#1631 resolves this
