### ISSUE TITLE
Fix corrupt bundles from pancreas6decades test

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/data-store#1644]
At Kevin's request, I'm opening this ticket.
BrianH says you have a method now to fix corrupt GCP files/bundles.
Please fix the corrupt files in the following bundles:

```
Primary Bundle ID
61475608-9689-45ac-8e2e-d7546726f7c5
34495b51-7ae8-45c9-9ec7-a67cf3de20e2
238f3028-ed54-4c7c-9b23-e28ad06075b8
afccc467-c48c-4769-bd18-55c68498b781
```

**Comment by xbrianh** [comment]
The corrupt files have been repaired.
