### ISSUE TITLE
`POST /search?output_format=raw` broken on staging

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-store#1648]
```
$ http "https://dss.staging.data.humancellatlas.org/v1/search?output_format=raw&replica=aws&per_page=100" es_query:={}
HTTP/1.1 502 Bad Gateway
Connection: keep-alive
Content-Length: 36
Content-Type: application/json
Date: Fri, 19 Oct 2018 03:18:45 GMT
x-amz-apigw-id: O_j66Ec3IAMFqTw=
x-amzn-RequestId: ae646ec4-d34d-11e8-9411-43b0356feac9

{
    "message": "Internal server error"
}
```

`per_page=10` works, interestingly.

**Comment by xbrianh** [comment]
`dss-staging` is returning more data than API Gateway can handle:
"""(578440cb-d366-11e8-aaa0-b118a972298b) Lambda execution failed with status 200 due to customer function error: body size is too long. Lambda request id: 57852b5c-d366-11e8-a31b-a3a83baffc12""""

**Comment by Bento007** [comment]
We should add a note, that when outputting raw page size may need to be adjusted, or we could add a better error message for the user? Maybe both?

**Comment by Bento007** [comment]
create this ticket for future work #1675
