### ISSUE TITLE
rewrite the Preview scripts to use the new versions of the data in Production

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#1655]
@kozbo commented on [Tue Oct 23 2018](https://github.com/HumanCellAtlas/dcp/issues/183)

## User Story
As a user of the of the Preview.data.humancellatlas.org I would like  to be able to download the Preview data that uses the latest schemas, and directly from the production deployment.

## Definition of Done
Update each of the download scripts to use the new bundle ids
Update the preview site to use the new scripts
?? Other updates?

**Comment by kozbo** [comment]
Fixed by dcp-preview#34, dcp-preview#35 and dcp-preview#36 PR's

**Comment by Bento007** [comment]
fixed
