### ISSUE TITLE
Store subscriptions as an object in replica 

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#1661]
As an operator I would like to be able to rebuild the subscription database in the event elastic search fails.

# Definition of Done
* Subscriptions objects are stored as object in the data store replica when subscription/put is used.
* Subscription object are deleted when subscriptions/{uuid}/delete api is used
* Subscriptions objects can be used to rebuild the elasticsearch subscriptions index.

**Comment by kozbo** [comment]
Implementation: Snapshot Dynamo DB as a way of backing up the subscriptions to a bucket.
