### ISSUE TITLE
Define Reliability Goals

### ISSUE THREAD

**Issue by rhiananthony** [HumanCellAtlas/data-store#1682]
This ticket is for the purpose fo tracking the initial set of reliability goals for each component, reliability being defined as a combination of uptime and fault tolerance. Included would be tooling to track the state of each component and make measurements against the set goals.

**Comment by kozbo** [comment]
What documentation are you looking for @rhiananthony ?

**Comment by brainstorm** [comment]
Related with issue #1685, btw 👍 :)

**Comment by kozbo** [comment]
- [ ] Uptime is now being calculated via the health check.
 - [ ] Need to pay down the error rates from airbrake 
 - [ ] Need to make tests more reliable

**Comment by theathorn** [comment]
Parent Epic closed by @sampierson.
