### ISSUE TITLE
Minor Python 3.X versions not being detected by common.mk

### ISSUE THREAD

**Issue by brainstorm** [HumanCellAtlas/data-store#1684]
## Software version (git hash, date, branch)
commit 5190fe303bebb31b283aeecb2ca916da6c2a4216 (HEAD -> master, origin/master, origin/HEAD)
## Expected behavior
Deploy without issues inside a [(mini)conda environment](https://conda.io/miniconda.html).

## Actual behavior
```
(hca) ubuntu@ip-172-31-21-87:~/data-store$ make --dry-run
common.mk:20: *** Please run make commands from a Python 3.6 virtualenv.  Stop.
(hca) ubuntu@ip-172-31-21-87:~/data-store$ which python
/home/ubuntu/miniconda3/bin/python
```
## Steps to reproduce the behavior

1. Install Miniconda: https://conda.io/miniconda.html
2. `make --dry-run`

**Comment by brainstorm** [comment]
An neither from a plain python3-venv:

```
$ sudo apt-get install python3-venv
$ python3 -mvenv hca-venv
$ source hca-venv/bin/activate
(hca-venv)$ make --dry-run
common.mk:20: *** Please run make commands from a Python 3.6 virtualenv.  Stop.
```

**Comment by brainstorm** [comment]
Turned out that the findstring on the common.mk makefile strictly searches for 3.6... 3.7 seems to work so far.

**Comment by brainstorm** [comment]
Same goes for Chalice:

```
/home/ubuntu/hca-venv/lib/python3.7/site-packages/chalice/deploy/validate.py:24: UserWarning: You are currently running python3.7, but the closest supported version on AWS Lambda is python3.6
Please use python3.6, otherwise you may run into deployment issues.
  validate_python_version(config)
```

You might want to relax those Python 3.x checks? Not seeing any deploy issues during `make deploy` so far (fingers crossed) :-S

**Comment by brainstorm** [comment]
Double nope, AWS Lambda does support Python 3.7 right now:

<img width="1321" alt="skarmavbild 2018-11-22 kl 12 57 55" src="https://user-images.githubusercontent.com/175587/48877225-6d1cc400-ee56-11e8-8614-777b99a498cf.png">

**Comment by melainalegaspi** [comment]
We're not supporting other use cases

**Comment by brainstorm** [comment]
This is not "another use case" this is about your software being unnecessarily deprecated.

It's actually just a one line fix!

**Comment by brainstorm** [comment]
Related to https://github.com/HumanCellAtlas/data-store/pull/2346

**Comment by DailyDreaming** [comment]
@brainstorm The one-line safe-guard in `common.mk` is there to ensure a consistent python version between all developers.  We will upgrade to python3.7, but will most likely choose to remain with a mainline version of python rather than switch to miniconda.
