### ISSUE TITLE
Add API to allow enumeration of Collections

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-store#1701]
## User story
* As a browser or portal developer
* I want to list all the collections I have access to
* so that I (and other users) don't each have to maintain a database of Collection UUIDs

## Definition of done
* API that returns a list of Collection UUIDs to which the caller has access

**Comment by kozbo** [comment]
discuss in Architecture meeting. Where is the ownership tracked?

**Comment by theathorn** [comment]
See also #1269.

**Comment by kozbo** [comment]
this has been duplicated in #1932, closing
