### ISSUE TITLE
Environment variable `DSS_VERSION` is not set

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/data-store#1702]
## Software version (git hash, date, branch)

* Dev 582c3d40
* Integration 56da699c
* Staging 56da699c

## Expected behavior

`GET /version` endpoint returns a git SHA1 prefix or version tag

## Actual behavior

```json
{
    "version_info": {
        "version": null
    }
}
```

## Steps to reproduce the behavior

Example: https://dss.dev.data.humancellatlas.org/version

**Comment by mweiden** [comment]
Unfortunately, this seems to still be a problem.

**Comment by xbrianh** [comment]
Fix from @mweiden worked, but `scripts/populate_lambda_ssm_parameters.py` needed to be executed. This should be done each time `environment` or `environment.$DSS_DEPOYMENT_STAGE` is updated.
