### ISSUE TITLE
GCP storage buckets not created in the supplied region on the environment

### ISSUE THREAD

**Issue by brainstorm** [HumanCellAtlas/data-store#1715]
## Software version (git hash, date, branch)
81547e1
2018-11-14
master

## Expected behavior

Given the following regions specified in `environment.local`:

```bash
$ env | grep REGI
GCP_DEFAULT_REGION=australia-southeast1
AWS_DEFAULT_REGION=ap-southeast-2
```

The buckets created by `make deploy-infra` should be created into those regions.

## Actual behavior

Instead, those buckets are created in US region(s) on GCP:

<img width="1645" alt="skarmavbild 2018-11-14 kl 16 32 07" src="https://user-images.githubusercontent.com/175587/48462220-75a84580-e82b-11e8-8b2a-04232626fbe3.png">

## Steps to reproduce the behavior

Run `make deploy-infra`, type `yes` when terraform asks to apply the plan.

**Comment by brainstorm** [comment]
Looks like a simple fix: `buckets/gs.tf` should be parametrized in `variables.tf` so that the hardcoded `location = US` is picked up from `GCP_DEFAULT_REGION` instead.

**Comment by kozbo** [comment]
See comments in #1762. We are leaving this as is, closing.
