### ISSUE TITLE
README.md: "An AWS route53 zone must be available for your domain name"

### ISSUE THREAD

**Issue by brainstorm** [HumanCellAtlas/data-store#1718]
## Software version (git hash, date, branch)
81547e1
2018-11-14
master

## Expected behavior
`make deploy-infra` creating the required route53 zones or DNS resource records managed by terraform and defined in `environment.local`, for consistency.

The README should mention it will be created, but not assume it has to be created manually outside of the deployment routine.

Also the required policies/roles/permissions should be encoded on terraform, not assumed to be put in place by the user manually.

## Actual behavior
```
$ make deploy-infra
(...)
buckets domain elasticsearch gcp_service_account
cd domain; terraform apply
data.aws_caller_identity.current: Refreshing state...
data.aws_route53_zone.selected: Refreshing state...

Error: Error refreshing state: 1 error(s) occurred:

* data.aws_route53_zone.selected: 1 error(s) occurred:

* data.aws_route53_zone.selected: data.aws_route53_zone.selected: Error finding Route 53 Hosted Zone: AccessDenied: User: arn:aws:sts::ACCOUNT_ID:assumed-role/DSS_DEPLOY_ROLE/i-0fff715198f95c782 is not authorized to perform: route53:ListHostedZones
        status code: 403, request id: d4a4f6e7-e862-11e8-b1fb-13c43b8553d8


make[2]: *** [Makefile:37: apply] Error 1
make[2]: Leaving directory '/home/ubuntu/data-store/infra'
make[1]: *** [Makefile:17: apply-all] Error 1
make[1]: Leaving directory '/home/ubuntu/data-store/infra'
make: *** [Makefile:80: deploy-infra] Error 2
```
## Steps to reproduce the behavior

`make deploy-infra`

**Comment by xbrianh** [comment]
Some cloud infrastructure, such as certificates and route53 zones, are shared by components external to the DSS and have different management needs. Such infrastructure is assumed to exist as a dependency for DSS deployment.
