### ISSUE TITLE
remove bundle/delete

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#1737]
depends on #1736

## User story
* As a admin
* I want to only allow deletions through admin tools
* so that I limit admin actions to a single point of entry.

## Definition of done
* removed delete bundle from the swagger API.
* update tests to not use bundle/delete
* remove admin whitelist
* remove admin operations from the dss API

**Comment by xbrianh** [comment]
Bundles to be assigned owners, and owners granted tombstone privileges for their bundles.
