### ISSUE TITLE
dss-sync-sfn-staging throwing exceptions

### ISSUE THREAD

**Issue by parthshahva** [HumanCellAtlas/data-store#1749]
# Software version (git hash, date, branch)
Staging
# Expected behavior
dss-sync-sfn-staging does not throw exceptions
# Actual behavior
https://humancellatlas.airbrake.io/projects/179579/groups/2323375474859293000?tab=overview
```
Error: '/aws/lambda/dss-sync-sfn-staging No handler found for event {'Records': '
```
This error was seen 173k times in the past two months

**Comment by xbrianh** [comment]
These errors are artifacts of a low level operation in the DSS (switching staging buckets), and will cease once the operation is complete.
