### ISSUE TITLE
Support for Level 2 health checks

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#1756]
## User story
* As a system administrator
* I want to know when the DSS is down and why
* so that I can know what component needs repair

## Definition of done
The /health endpoint will roll up the status from all major components in the DSS into it's report
 - [ ] update Cloudwatch
 - [ ] event relay
 - [x] add dynamo-db
 - [x] add Elastic search
 - [x] swagger API service

**Comment by amarjandu** [comment]
reference for black-box monitoring 
https://github.com/HumanCellAtlas/dcp-community/blob/master/rfcs/text/0002-monitoring-for-production-systems.md

**Comment by amarjandu** [comment]
# Notes
https://github.com/HumanCellAtlas/data-store/tree/amar-l2
## In-Progress
Working Health check with ES ! :)

Currently need to bring up formatting for response body in the Tech-Arch meeting, Should we keep minimal information ```Ok``` vs having something that's more descriptive ``` {
"overall": "Healthy",
"es" : "{
 "cluster_name" : "testcluster",
 "status" : "yellow",
 "timed_out" : false,
 "number_of_nodes" : 1,
 "number_of_data_nodes" : 1,
 "active_primary_shards" : 5,
 "active_shards" : 5,
 "relocating_shards" : 0,
 "initializing_shards" : 0,
 "unassigned_shards" : 5,
 "delayed_unassigned_shards": 0,
 "number_of_pending_tasks" : 0,
 "number_of_in_flight_fetch": 0,
 "task_max_waiting_in_queue_millis": 0,
 "active_shards_percent_as_number": 50.0
}",
"etc": "{ other health stuff}"
} ``` 

### Changes Made
changed endpoint health function

**Comment by amarjandu** [comment]
## Tech Arch Discussion

only describe endpoints that are failing if requested, otherwise
{"overall":"Healthy"}

Andrey's input for Event Relay:
Propagate test bundle into the system, check for failures within the system.
May want amazon diagnostic API checks

**Comment by amarjandu** [comment]
# NOTES

## Changes
Working ES,DDB
## In-Progress
Working on solution for Event Relay
Need to get canary folder setup
#TODO
May need to tie into cloudwatch
