### ISSUE TITLE
'selfLink' keyError in dss-sync-sfn-prod

### ISSUE THREAD

**Issue by parthshahva** [HumanCellAtlas/data-store#1758]
# Environment
Production

# Function
dss-sync-sfn-prod

# Error
```
'/aws/lambda/dss-sync-sfn-prod 'selfLink': KeyError Traceback (most recent call last): File "/var/task/domovoi/app.py", line 203, in __call__ result = handler(event, context) File "/var/task/app.py", line 63, in launch_from_forwarded_event if message["selfLink"].startswith("https://www.googleapis.com/storage"): KeyError: 'selfLink' '@log_stream': 2018/11/30/[$LATEST]ed747d96e4c448bdb84ab592b65ce1d7
```
https://humancellatlas.airbrake.io/projects/179579/groups/2304980543648283982?tab=overview

seen 26.9k times in the last 2 months

**Comment by kozbo** [comment]
This seems to be noise, _possibly_ a false negative. Please qualify the severity of the problem and see if we can get the noise down.

**Comment by xbrianh** [comment]
This error appears resolved. Please reopen if it happens again.
