### ISSUE TITLE
Checkout to my own bucket failed silently

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/data-store#1760]
## Software version (git hash, date, branch)
hca 4.4.10 (CPython 3.7.0 Darwin-16.7.0-x86_64-i386-64bit)
DSS Prod GCP replica

## Expected behavior
I tried to run
`hca dss post-bundles-checkout --uuid be8b990d-2e74-4cbc-a3e1-b81ddaab9a57 --version 2018-11-13T004918.926902Z --replica gcp --destination  gs://my-google/kdegs/bucket/ --email myemail@broadinstitute.org` 
and it performed as expected in the terminal, giving me a checkout id. The checkout status endpoint returned that it was "running". A while later, it still hadn't completed and I was worried.

## Actual behavior
Talking to @mckinsel there were some airbrake errors around that time and he realized that it did not like that I had a trailing slash in my google bucket. 

The checkout IDS that were still returning "RUNNING" were these:
`hca dss get-bundles-checkout --checkout-job-id 08ee76b6-6f7f-44f6-8fd4-1b5184eeddb3 --replica gcp`
`hca dss get-bundles-checkout --checkout-job-id ca42ee38-a20a-4650-816e-b69e2dd4bb00 --replica gcp`

## Steps to reproduce the behavior
See above

**Comment by xbrianh** [comment]
Bucket must be specified without scheme or prefix, e.g. `--destination my_bucket`, NOT `--destination gs://my_bucket/my_path`

This endpoint should perform sanity checks before invoke the SFN.
Potentially use async state to propagate SFN failures to GET /bundles/checkout/

**Comment by kbergin** [comment]
Yea sounds like there’s a lot of checks and error messages that could help the user use this command properly. 

Shouldn’t it have failed though either way? A bit worried it still said running. Someone should check those jobs actually aborted at some point probably lol!

**Comment by xbrianh** [comment]
@kbergin I am that someone! Those jobs all failed safely. We need to understand why they're lying about their status.

**Comment by kbergin** [comment]
Perfect! Well, maybe the bug report can turn into tickets on looking into that and catching typos in the command if that’s helpful.

**Comment by DailyDreaming** [comment]
Just ran into this:
```
(venv) quokka@qcore:~/delete/data-store$ hca dss post-bundles-checkout --replica aws --uuid fff94e8e-6470-4330-9ba2-1cc2d822b67b --destination lon-dss-test
{
  "checkout_job_id": "45148616-f98e-4ad8-9a73-9f7ec4565957"
}
(venv) quokka@qcore:~/delete/data-store$ hca dss get-bundles-checkout --replica aws --checkout-job-id 45148616-f98e-4ad8-9a73-9f7ec4565957
{
  "status": "RUNNING"
}
(venv) quokka@qcore:~/delete/data-store$ hca dss get-bundles-checkout --replica aws --checkout-job-id 45148616-f98e-4ad8-9a73-9f7ec4565957
{
  "status": "RUNNING"
}
(venv) quokka@qcore:~/delete/data-store$ hca dss get-bundles-checkout --replica aws --checkout-job-id 45148616-f98e-4ad8-9a73-9f7ec4565957
{
  "status": "RUNNING"
}
(venv) quokka@qcore:~/delete/data-store$ hca dss get-bundles-checkout --replica aws --checkout-job-id 45148616-f98e-4ad8-9a73-9f7ec4565957
{
  "cause": "failure to complete work within allowed time interval",
  "status": "FAILED"
}
```

**Comment by kozbo** [comment]
Re-open if this occurs again
