### ISSUE TITLE
POST /search with default page size truncates results

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-store#1768]
```py
>>> from concurrent.futures import ThreadPoolExecutor
>>> from functools import partial
>>> from itertools import product
>>> import random
>>> from hca.dss import DSSClient
>>> dss = DSSClient(swagger_url='https://dss.staging.data.humancellatlas.org/v1/swagger.json')
>>> prefixes = list(map(''.join, product('0123456789abcdef', repeat=2)))
>>> prefixes
['00', '01', '02', '03', '04', '05', '06', '07', '08', '09', '0a', '0b', '0c', '0d', '0e', '0f', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '1a', '1b', '1c', '1d', '1e', '1f', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '2a', '2b', '2c', '2d', '2e', '2f', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '3a', '3b', '3c', '3d', '3e', '3f', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '4a', '4b', '4c', '4d', '4e', '4f', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '5a', '5b', '5c', '5d', '5e', '5f', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '6a', '6b', '6c', '6d', '6e', '6f', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '7a', '7b', '7c', '7d', '7e', '7f', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '8a', '8b', '8c', '8d', '8e', '8f', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '9a', '9b', '9c', '9d', '9e', '9f', 'a0', 'a1', 'a2', 'a3', 'a4', 'a5', 'a6', 'a7', 'a8', 'a9', 'aa', 'ab', 'ac', 'ad', 'ae', 'af', 'b0', 'b1', 'b2', 'b3', 'b4', 'b5', 'b6', 'b7', 'b8', 'b9', 'ba', 'bb', 'bc', 'bd', 'be', 'bf', 'c0', 'c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9', 'ca', 'cb', 'cc', 'cd', 'ce', 'cf', 'd0', 'd1', 'd2', 'd3', 'd4', 'd5', 'd6', 'd7', 'd8', 'd9', 'da', 'db', 'dc', 'dd', 'de', 'df', 'e0', 'e1', 'e2', 'e3', 'e4', 'e5', 'e6', 'e7', 'e8', 'e9', 'ea', 'eb', 'ec', 'ed', 'ee', 'ef', 'f0', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'fa', 'fb', 'fc', 'fd', 'fe', 'ff']
>>> prefixes_sample = random.sample(prefixes, 16)
>>> prefixes_sample
['bc', 'f1', 'ad', '66', '49', '03', '9b', 'de', '41', '48', '64', '75', '40', 'd6', 'ce', 'fe']
>>> tpe = ThreadPoolExecutor(max_workers=16)
>>> def query(per_page, prefix):
...     query = {'query': {'bool': {'must': [
...         {'exists': {'field': 'files.project_json'}},
...         {'prefix': {'uuid': prefix}}]
...     }}}
...     return prefix, len(list(dss.post_search.iterate(replica='aws', es_query=query, per_page=per_page)))
... 
```

Now lets run several `POST /search` requests in parallel, using a value of 10 for `per_page` which is also the default.

```
>>> dict(sorted(tpe.map(partial(query, 10), prefixes_sample)))
{'03': 607, '40': 188, '41': 597, '48': 525, '49': 579, '64': 597, '66': 571, '75': 581, '9b': 564, 'ad': 527, 'bc': 548, 'ce': 444, 'd6': 576, 'de': 537, 'f1': 583, 'fe': 570}
>>> dict(sorted(tpe.map(partial(query, 10), prefixes_sample)))
{'03': 601, '40': 595, '41': 593, '48': 519, '49': 607, '64': 608, '66': 597, '75': 568, '9b': 560, 'ad': 528, 'bc': 560, 'ce': 624, 'd6': 558, 'de': 502, 'f1': 563, 'fe': 546}
```

Oops, the second result is different from the first one. 

This does not happen if the page size is 500 but this might be coincidental because roughly 500 bundles fall into each prefix partition:

```
>>> dict(sorted(tpe.map(partial(query, 500), prefixes_sample)))
{'03': 630, '40': 632, '41': 606, '48': 552, '49': 631, '64': 633, '66': 613, '75': 605, '9b': 579, 'ad': 561, 'bc': 582, 'ce': 637, 'd6': 586, 'de': 545, 'f1': 608, 'fe': 585}
>>> dict(sorted(tpe.map(partial(query, 500), prefixes_sample)))
{'03': 630, '40': 632, '41': 606, '48': 552, '49': 631, '64': 633, '66': 613, '75': 605, '9b': 579, 'ad': 561, 'bc': 582, 'ce': 637, 'd6': 586, 'de': 545, 'f1': 608, 'fe': 585}
>>> dict(sorted(tpe.map(partial(query, 500), prefixes_sample)))
{'03': 630, '40': 632, '41': 606, '48': 552, '49': 631, '64': 633, '66': 613, '75': 605, '9b': 579, 'ad': 561, 'bc': 582, 'ce': 637, 'd6': 586, 'de': 545, 'f1': 608, 'fe': 585}
>>> dict(sorted(tpe.map(partial(query, 500), prefixes_sample)))
{'03': 630, '40': 632, '41': 606, '48': 552, '49': 631, '64': 633, '66': 613, '75': 605, '9b': 579, 'ad': 561, 'bc': 582, 'ce': 637, 'd6': 586, 'de': 545, 'f1': 608, 'fe': 585}
```

Same result every time.

**Comment by hannes-ucsc** [comment]
This also happens in an actual lambda that does NOT use threads so my first instinct was to believe that this does not have anything to do with thread-safety in DSSClient. However, AWS may pack different executions of the same lambda function into the same interpreter process. If there is process-wide shared state (like in class attributes of the DSSClient class) the cause may be in DSSClient, and not the DSS. I did look into `.iterate()` and didn't find any smoking guns, though.

**Comment by xbrianh** [comment]
There may be issues with the number of nodes in our ES cluster, the number of shards in our indices, and the highly parallelized usage of `search_after`. A shard may reject queries when overloaded, leading to partial results.

The rejected count in `search thread pool`, on the ES cluster monitoring page, ticks during highly parallel testing. It is quite high anyway, indicating our cluster is too small for our needs.

If this is the underlying cause, some potential remediations are:
* Increase the number of nodes in the cluster, and number of shards in our indices
* Ask users to reduce the parallelism of their queries
* Return an 4xx error when a shard failure is detected on the backend

We can test this theory further by logging detecting shard failures.

**Comment by hannes-ucsc** [comment]
> A shard may reject queries when overloaded, leading to partial results.

Assuming this hypothesis is true, shards being unavailable should result in degraded performance or an 500 error on the DSS endpoint, not partial results. `/search` is currently the only way to get a listing of bundles out of the DSS. If that endpoint is not deterministic, I'd have to bypass the DSS for reindexing. Azul cannot afford to serve partial results to its users.

I urge you to first make the necessary changes so this situation causes a 500 error rather than partial results. Then address the performance degradation in a second step.

**Comment by xbrianh** [comment]
@hannes-ucsc I agree with your prioritization, and agree that an error should be returned instead of partial results.

In the meantime, there may be a some remediation strategies on the client side, either through the CLI, or best practice recommendations for users:
* Use larger `per_page`, which will result in fewer queries. The DSS should consider increasing the default value.
* Make an initial count query first, and check that all results were returned during paging

**Comment by hannes-ucsc** [comment]
Page size of 10 is too small for the default output format, 500 (the current max) seems perfectly fine. For output format of `raw` 10 is appropriate, 50 would be, too, but 500 is not. 

I don't think count queries are currently possible with the DSS. Additionally, they might be affected by the same problem.

Isn't the easiest mitigation for clients to retry on the 500 error that currently isn't being raised? Potentially with exponential back-off? In fact, doesn't the client already implement that?

I can't stress enough that serving an error instead of partial results should be the number one priority. Before any other mitigations, documentation changes etc.

**Comment by xbrianh** [comment]
@diekhans We are planning on returning an error, see my comment above.

Note that it is possible to get an expected hit count for an ES query:
```expected_count = dss.post_search(replica='aws', es_query=q, per_page=per_page)['total_hits']```

**Comment by hannes-ucsc** [comment]
I'm going to use @xbrianh's workaround until a fix for #1170 lands. Thanks everyone for the quick response!

**Comment by Bento007** [comment]
#1770 fixes this.

**Comment by hannes-ucsc** [comment]
I would like to verify the fix in staging. Reopening and assigning to me.

**Comment by hannes-ucsc** [comment]
Still happens in staging

```
dict(sorted(tpe.map(partial(query, 10), prefixes_sample)))
{'1c': 700, '31': 575, '3b': 641, '48': 536, '6e': 573, '8d': 591, 'a6': 613, 'a9': 534, 'cf': 599, 'd4': 568, 'd6': 539, 'db': 565, 'e5': 566, 'f4': 569, 'f7': 627, 'fc': 607}
dict(sorted(tpe.map(partial(query, 10), prefixes_sample)))
{'1c': 675, '31': 572, '3b': 604, '48': 550, '6e': 3, '8d': 544, 'a6': 617, 'a9': 563, 'cf': 642, 'd4': 555, 'd6': 556, 'db': 586, 'e5': 565, 'f4': 547, 'f7': 565, 'fc': 564}
```

**Comment by hannes-ucsc** [comment]
But I don't think the fix made it to staging yet.

**Comment by hannes-ucsc** [comment]
I'll try again in two weeks.

**Comment by kozbo** [comment]
Fixed?

**Comment by hannes-ucsc** [comment]
Yes, I now get `dss.error.DSSException` raised referring to shard failures now. Not desirable, of course, but at least there is no silent truncation. I think in a newer version of the client, these shard failures are being retried but I don't have time to test this now and it is not what this bug is about.
