### ISSUE TITLE
Checkout should not be allowed to checkout tombstoned bundles

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#1774]
## Software version (git hash, date, branch)
a22a22d3bb8cb6992d301205cc63f23d1a2d730f

## Expected behavior
GET /bundle returns 404 if bundle has been tombstoned

## Actual behavior
The second GET in this sequence returns 200 with bundle manifest:
```
PUT /bundle
GET /bundle
DELETE /bundle
GET /bundle
```

Note  that this sequence, which does not perform checkout before tombstoning, produces the expected 404:
```
PUT /bundle
DELETE /bundle
GET /bundle
```

## Steps to reproduce the behavior
Create a bundle.
Get that bundle.
Delete that bundle.
Checkout that bundle.

**Comment by amarjandu** [comment]
Tested Bundle deletion using CLI,Deployment-DEV

```
hca dss upload --replica aws --staging-bucket amar-testing-dev --src-dir /Users/amar/Downloads/amar-cli-test 
hca dss download --bundle-uuid 17f1c067-4f7e-41bf-aa62-aee855c5bc28 --replica aws
hca dss delete-bundle --uuid 17f1c067-4f7e-41bf-aa62-aee855c5bc28 --replica aws --reason testing --version 2019-01-17T180927.452198Z
hca dss download --bundle-uuid 17f1c067-4f7e-41bf-aa62-aee855c5bc28 --replica aws
```
had to add `hca dss login` UCSC email to dss-dev lambda to be permitted to delete correctly

Bucket was uploaded, downloaded to local directory, deletion was confirmed, download produced a 404 error on second GET attempt
