### ISSUE TITLE
ADMIN_USER_EMAILS should be populated into AWS parameter store

### ISSUE THREAD

**Issue by xbrianh** [HumanCellAtlas/data-store#1775]
## Software version (git hash, date, branch)
c43b1ec0baa940170e4710f6b765bea8135503e9
## Expected behavior
Deployed Lambda env var ADMIN_USER_EMAILS contains at least the gcp service account
## Actual behavior'
ADMIN_USER_EMAILS is empty
## Steps to reproduce the behavior
Deploy and view `dds-dev` config on the AWS console and see that ADMIN_USER_EMAILS is empty.

scripts/populate_lambda_ssm_parameters.py should be modified to populate ADMIN_USER_EMAILS

**Comment by amarjandu** [comment]
ADMIN_USER_EMAILS populates correctly from ./scripts/populate_lambda_ssm_parameters.py  when ENV is set, confirmed working for single email // multiple emails.

ADMIN_USER_EMAILS=example1@ucsc.edu,example2@fastmail.com

**Comment by amarjandu** [comment]
Notes: spoke with BH regarding path for secret, SecretManager-> SSM -> Lambda makes the most sense, by issues with gitlab/laptop deployment might complicate process if going directly from SM->Lambda

Awaiting Approval for final submission
