### ISSUE TITLE
Simplify process for enabling audit logs.

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#1778]
## User story
* As an operator of the DSS
* I want to enable audit logs with a single `make deploy-infra`
* so that simplify the audit log deployment process.

## Definition of done
Users should no longer need successfully deploy the DSS once before enabling audit logs.

**Comment by melainalegaspi** [comment]
@Bento007 was this completed?

**Comment by Bento007** [comment]
incomplete, also I have no additional context into this issue.
