### ISSUE TITLE
File with content-type `application/json` is served as `binary/octet-stream`

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/data-store#1791]
Hi Bluebox

I would like to ask for your help in investigating this issue. This has been originally filed in ingest by @hannes-ucsc . I believe we're passing the correct header when we PUT files to the upload area. I am uncertain where to investigate further. The issue could be happening during the transfer of files from upload area to DSS which I believe is being triggered in blue box? If this is not the case, please let me know, then I could file a ticket to the upload service to help with the investigation too. 

The sample bundle files are in the issues linked here.

Many thanks!

## Expected behavior
File with content-type `application/json` is served as `application/json`

## Actual behavior
File with content-type `application/json` is served as `binary/octet-stream`

## Steps to reproduce the behavior
staging: https://app.zenhub.com/workspaces/dcp-backlogs-5ac7bcf9465cb172b77760d9/issues/humancellatlas/ingest-central/215
prod: https://app.zenhub.com/workspaces/dcp-backlogs-5ac7bcf9465cb172b77760d9/issues/humancellatlas/ingest-central/277

**Comment by Bento007** [comment]
@xbrianh did you say you had a fix for this?

**Comment by xbrianh** [comment]
Yep, we can update content-type manually via AWS and GCP consoles.
