### ISSUE TITLE
Review Metadata team's JSON 07 javascript validator

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#1794]
The metadata team announced that the metadata-schema repo has switched from using a python schema validator to using the javascript one that the ingestion service uses and that has support for draft-07 JSON. On our call, @Hannes mentioned that the DS does some schema validation, potentially using a python validator. I just wanted to share the metadata team’s update (https://github.com/HumanCellAtlas/metadata-schema/pull/631) in case the DS wanted to be aligned with what the metadata team and the ingestion service are using.

Do we want to keep our Python validator or move to theirs?

**Comment by Bento007** [comment]
Once ES moves out of the DSS we will no longer be using a json validator.
