### ISSUE TITLE
Tombstone/Delete 4 bundles from prod integration test run

### ISSUE THREAD

**Issue by parthshahva** [HumanCellAtlas/data-store#1795]
https://dss.data.humancellatlas.org/v1/bundles/6f6bd9ac-712f-4b16-980c-0b0c247941e4/?replica=aws
https://dss.data.humancellatlas.org/v1/bundles/56cd346d-1a26-40ee-9df7-10708488d2fa/?replica=aws
https://dss.data.humancellatlas.org/v1/bundles/b5f03259-3d21-4d62-b0d3-b47bc2c95c29/?replica=aws
https://dss.data.humancellatlas.org/v1/bundles/8bf6e22c-c9bf-4f0f-8ca8-9965d40cd646/?replica=aws

**Comment by hannes-ucsc** [comment]
I'd say only delete the specific versions. I put them into the CBeta spreadsheet, "Prod problem bundles" tab.

**Comment by xbrianh** [comment]
bundles tombstoned
