### ISSUE TITLE
SPIKE Research work required to meet FISMA moderate certification

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#1802]
Eventually we want the following user story:
## User story
* As an operator or member of the governing group
* I want to meet FISMA Moderate security requirements 
* so that I can ingest and manage data from controlled access government data sets in the DCP
## Definition of done
Passing an independent audit that certifies compliance.

 - [ ] SPIKE
produce a 1 page summary of 
What does it mean to the team to be FISMA moderate compliant / Fedramp / NIST 800-53
Where is the security perimeter?
What is the value to the team (ingest Lung Map and brain data
Resource required - how many people? Where?
Timeline rough scale of the complexity

Feb DCP F2F meeting to discuss
DoD - produce a short slide pack and short document to lay out some of the information accquired.
NOTE - This is probably a devSecOps task realy, because it cuts across all modules

**Comment by Bento007** [comment]
This may be a good candidate for topic at the DCP meeting in Feb
