### ISSUE TITLE
Add content disposition header to checked-out objects

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-store#1837]
The Data Browser offers a direct download feature which uses the DSS' `GET /files` to check out a file and then download it to the users disk. By default, most user agents treat URLs whose response has known content type like `image/jpeg`, `application/pdf`, `text/tab-separated-values` by opening them in a tab rather than just downloading and saving them to disk. That default user agent behavior can be overridden by including the `Content-Disposition: attachment` header in the response. A server can optionally suggest a file name for the downloaded file by specifying `Content-Disposition: attachment; filename="filename.jpg"`. Without the `filename` part, browsers default to the last component of the URL path as the suggested local file name. In case of signed URLs to files checked out by the DSS, this last component is the blob checksum. It is very long and meaningless to users of the Data Browser.

S3 can be coaxed into including this header in responses to requests for a signed URL to an object in two ways: the header can be persisted with the object as metadata during `PUT object` or the header can be incorporated into the signed URL.

Ideally, we would like to specify the file name, as in `Content-Disposition: attachment; filename="filename.jpg"`, but this would require adding an optional parameter to the DSS' `PUT /files` since blobs can have multiple files and each file can be assigned different names in bundle manifests. To allow for sharing a single checked-out blob between multiple files, the header should be incorporated in the signed URL instead of being persisted as object metadata.

**Comment by hannes-ucsc** [comment]
@kozbo, where is this on your list of priorities? We have a horrible hack in Azul to work around this.

**Comment by xbrianh** [comment]
It seems content disposition can be specified when creating signed GET urls for S3 and GS.

Perhaps the DSS can allow clients to indicate content-disposition with an optional parameter on GET /files.

**Comment by kislyuk** [comment]
I agree content-disposition should be accommodated in DSS to specify a fixed disposition (attachment?) and a filename. It's important to make sure this behavior is consistent between replicas (GS and S3, and whatever we end up using in the future). Unfortunately, I can't think of a clean solution to the filename ambiguity using our current facilities. I think it's time to allow specifying a "default" filename that's intrinsic to the file, as Hannes suggests.

One thing we need to thoroughly de-risk before we nail this down is how this impacts webapps that want to build on top of DSS. In other words I want to make sure the Content-Disposition header does not interfere with javascript-based apps that want to render DSS file contents in the browser.

**Comment by xbrianh** [comment]
The Content-Disposition header can be overridden dynamically when creating presigned urls for S3 and GS objects by using the `response-content-disposition` parameter. The DSS should take advantage of this feature to allow clients to specify Content-Disposition when consuming presigned urls.

There is one proviso: Content-Disposition cannot be overridden if it is present in the metadata of GS objects, and so will be unavailable to consumers of direct urls, e.g. `gs://foo`. However, such clients are unlikely to be browser based, and will have access to file and bundle metadata as needed.

**Comment by kislyuk** [comment]
I like this strategy @xbrianh, thanks for researching and de-risking it.
