### ISSUE TITLE
File with content-type `application/json` is served as `binary/octet-stream` in prod

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-store#1843]
Same issue as https://github.com/HumanCellAtlas/ingest-central/issues/215 but in production and for bundle `721fb7e9-9704-46c6-b85c-11472d3c6078` version `2018-11-06T212058.940839Z` and file `fa4b547d-6951-48da-981d-0371952f4e1c` version `2018-11-06T163457.425000Z`.

**Comment by justincc** [comment]
Transferred as per tech-arch discussion to data-store for further investigation.

**Comment by xbrianh** [comment]
The file metadata was correctly set:
```
{
  "format": "0.0.4",
  "creator_uid": 8008,
  "version": "2018-11-06T163457.425000Z",
  "content-type": "application/json; dcp-type=\"metadata/file\"",
  "size": 465,
  "crc32c": "2d984c4f",
  "s3-etag": "bbfa415345e1a0ff726ecad62b860d0f",
  "sha1": "53395ad67043cbeb0973092b17fa1021c030e3fb",
  "sha256": "ad3fa62bfd8b59f432bc547f5eaf9a1c14d2a3b89385f21e08d7fc7546e12bb6"
}

However the blob metadata was not:
```
aws s3api head-object --bucket org-hca-dss-prod --key blobs/ad3fa62bfd8b59f432bc547f5eaf9a1c14d2a3b89385f21e08d7fc7546e12bb6.53395ad67043cbeb0973092b17fa1021c030e3fb.bbfa415345e1a0ff726ecad62b860d0f.2d984c4f
{   
    "AcceptRanges": "bytes",
    "LastModified": "Tue, 06 Nov 2018 21:21:01 GMT",
    "ContentLength": 465,
    "ETag": "\"bbfa415345e1a0ff726ecad62b860d0f\"",
    "ContentType": "binary/octet-stream",
    "Metadata": {}
}
```

I don't understand how this happened, or how this could have happened. However, it's relatively straight forward to update the blob metadata, which I have down.

These files should now be served with the correct content type.

**Comment by xbrianh** [comment]
Raising #1844 and closing this.
