### ISSUE TITLE
PUT /file should verify that file metadata content type agrees with blob content type

### ISSUE THREAD

**Issue by xbrianh** [HumanCellAtlas/data-store#1844]
It appears possible that S3 does not always correctly copy metadata, so we need to verify.

See:
https://github.com/HumanCellAtlas/ingest-central/issues/215
https://github.com/HumanCellAtlas/data-store/issues/1843

**Comment by xbrianh** [comment]
content-type mismatches were caused by the sync daemon omitting some metadata on destination blobs. This has been repaired by #2074

**Comment by DailyDreaming** [comment]
Reopened, there was another mismatch that will be fixed by: #2258
