### ISSUE TITLE
Please tombstone some prod bundles

### ISSUE THREAD

**Issue by parthshahva** [HumanCellAtlas/data-store#1849]
Bundles to tombstone:
https://dss.data.humancellatlas.org/v1/bundles/ee7be39e-0bde-47fc-bb03-b093b7fa96cb/?replica=aws
https://dss.data.humancellatlas.org/v1/bundles/f2a13b5f-0254-4d79-82d5-ef83752983d2/?replica=aws
https://dss.data.humancellatlas.org/v1/bundles/f925b618-cfbb-4404-89ce-7c41cf19f58a/?replica=aws
https://dss.data.humancellatlas.org/v1/bundles/05e4943d-73a2-42aa-bdc7-44cebbabb104/?replica=aws
https://dss.data.humancellatlas.org/v1/bundles/a932367a-5216-4ff4-a853-63672ac07ee1/?replica=aws
https://dss.data.humancellatlas.org/v1/bundles/a0fcc5ec-7fcb-4325-9648-d4c33cdc7447/?replica=aws

**Comment by xbrianh** [comment]
tombstoned
