### ISSUE TITLE
Tombstone more bundles :) 

### ISSUE THREAD

**Issue by parthshahva** [HumanCellAtlas/data-store#1855]
Bundles to tombstone:
https://dss.data.humancellatlas.org/v1/bundles/33b8b7e0-8b13-4da4-9df7-29faa5a228a0/?replica=aws
https://dss.data.humancellatlas.org/v1/bundles/4e1d7031-726f-4455-a594-da4f1a6f2310/?replica=aws
https://dss.data.humancellatlas.org/v1/bundles/93b35523-96cc-45d4-8cd8-53ccb06085e0/?replica=aws
https://dss.data.humancellatlas.org/v1/bundles/a1fb4c39-9b48-4fc9-8d15-70970351123f/?replica=aws
https://dss.data.humancellatlas.org/v1/bundles/09263465-13dd-4880-8483-95deaf9f250e/?replica=aws
https://dss.data.humancellatlas.org/v1/bundles/08fcb405-9465-4d32-b775-98c94c82d6b5/?replica=aws

**Comment by rexwangcc** [comment]
Let me watch this @rexwangcc

**Comment by xbrianh** [comment]
These bundles have been tombstoned.
