### ISSUE TITLE
Spec - update query spec based on new use cases and prototype feedback

### ISSUE THREAD

**Issue by mikebaumann** [HumanCellAtlas/data-store#187]
New query-related use cases for various boxes is coming available, as is feedback on use of the current DSS system. This should be incorporated into the query specification and design.

**Comment by kozbo** [comment]
see https://docs.google.com/spreadsheets/d/1PBMrc0oql4gPpH_cQMqlf7ASNMwePRQZNCutxeSFze8/edit#gid=0

**Comment by briandoconnor** [comment]
* Look at query table and incorporate feedback into specs for indexing engine.
* updating query language

**Comment by kozbo** [comment]
There will be more queries once the other boxes complete their specs. This will be moved ahead as  the Red boxes start to come on line. That will be the proof of the consumer API.
Moving to Done for this sprint (9). Create a new issue for adding future queries.
