### ISSUE TITLE
M1.4: Provide availability monitoring and downtime alerting of data store

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-store#1877]
@morrisonnorman commented on [Tue Dec 11 2018](https://github.com/HumanCellAtlas/dcp/issues/240)

Relates to:
M1.4: Provide availability monitoring and downtime alerting of data store
[See DCP-General Availability Document](https://docs.google.com/document/d/14gVAMscd0d8KgWqOO11Y1kSp4ztVavZXA7zrtrhyiW0/edit#)

---

@morrisonnorman commented on [Tue Dec 11 2018](https://github.com/HumanCellAtlas/dcp/issues/240#issuecomment-446206216)

@kozbo  Please can you comment on the status of this epic and link any open issues from your team board. Thanks!

**Comment by sampierson** [comment]
Covered by HumanCellAtlas/dcp#281, HumanCellAtlas/dcp#282 and HumanCellAtlas/dcp#65
