### ISSUE TITLE
M3.4: Ensure good availability (95% uptime outside of planned maintenance) of the data store

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-store#1879]
@tburdett commented on [Tue Dec 04 2018](https://github.com/HumanCellAtlas/dcp/issues/212)

---

@brianraymor commented on [Fri Dec 21 2018](https://github.com/HumanCellAtlas/dcp/issues/212#issuecomment-449522808)

@tburdett - Discussed with @parthshahva - are there any actionable engineering tasks lurking here? It more that we're monitoring our health checks and being responsive to failures.

**Comment by sampierson** [comment]
I'm closing this epic tickets.  Availability is something you architect for up front, then measure in operation and correct as necessary.
