### ISSUE TITLE
M3.8: Ensure that the data store recovers from downtime responsively (to meet 95% uptime objective, and to avoid more than 24 hours constant downtime)

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-store#1880]
@tburdett commented on [Tue Dec 04 2018](https://github.com/HumanCellAtlas/dcp/issues/213)

---

@brianraymor commented on [Fri Dec 21 2018](https://github.com/HumanCellAtlas/dcp/issues/213#issuecomment-449522753)

@tburdett - Discussed with @parthshahva - are there any actionable engineering tasks lurking here? It more that we're monitoring our health checks and being responsive to failures.

**Comment by sampierson** [comment]
I'm closing this epic tickets.  Availability is something you architect for up front, then measure in operation and correct as necessary.
