### ISSUE TITLE
Download of small files is too slow

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-store#1897]
## User story
* As a Data Browser user I want to download small files quickly so that I don't have to wait 10+ seconds

## Definition of done
* Select a small (10KB) file for download from the Data Browser files menu should complete in 1-2 seconds the first time the download is attempted.

There's a 10s delay if checkout is required. Download is fast (1-2s) if checkout already happened.

**Comment by Bento007** [comment]
fixed by #1887
