### ISSUE TITLE
More prod bundles to tombstone

### ISSUE THREAD

**Issue by parthshahva** [HumanCellAtlas/data-store#1914]
1f9effb5-849f-46f9-9edc-2f77c6cf54e2
9bff654b-1178-424d-b141-c77c8b7aa57b
ab2c985e-1f92-43d4-b6cf-a7282ff9e52e
5aaa8afc-1d73-4e14-a671-115519875ac1

cc @xbrianh 
cc @hannes-ucsc since projects tab may go blank in prod after this is done

**Comment by xbrianh** [comment]
These bundles were successfully tombstone by the dcp-wide integration test.
