### ISSUE TITLE
Resolve design question on file/bundle updates/subresources

### ISSUE THREAD

**Issue by kislyuk** [HumanCellAtlas/data-store#192]
Two potential solutions:

1. keep the existing file and bundle UUID spaces, independent file+bundle operations.  renames will be supported and tracked, but most likely only mechanical renames (i.e., bulk renames done with a tool) will likely take the proper path to rename.  updating a bundle could be awkward (because of the need to download bundle manifests to match UUIDs), but could theoretically be papered over by tooling.

2. switch to file as a subresource of bundles.  renames will not be tracked, but theoretically someone could build a tool that infers renames from history.

**Comment by ttung** [comment]
Design questions resolved!
