### ISSUE TITLE
Google application credentials key filename hardcoded

### ISSUE THREAD

**Issue by natanlao** [HumanCellAtlas/data-store#1921]
I think this should refer to `$GOOGLE_APPLICATION_CREDENTIALS_SECRETS_NAME` instead.

https://github.com/HumanCellAtlas/data-store/blob/8e96a0d35f7925859e33b4648cba410dd4705c4e/dss/util/__init__.py#L125

**Comment by amarjandu** [comment]
addressed https://github.com/HumanCellAtlas/data-store/pull/1942

**Comment by natanlao** [comment]
Closed by #1942
