### ISSUE TITLE
Add Windows platform for dcp-cli CI

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#1922]
## User story
As a user of the HCS DSS CLI, I want the CLI to work correctly/reliably when run on Windows platforms

This is being done now in support of the concurrent work to 1) enable paths in bundle file names, and 2) improve dcp-cli download performance/efficiency, including through the use of hard links, etc.

## Definition of done
DCP CLI unit tests are automatically and successfully run on Windows, in addition to the existing Linux test platform, as part of continuous integration

**Comment by mikebaumann** [comment]
The current plan consists of the following:

- [ ] Move the current dcp-cli CI setup/execution from Travis to GitLab. The existing tests and CI test execution will remain the same, including testing of the four currently tested Python versions, etc.
- [ ] Enhance the pipeline above with additional job(s) to run the dcp-cli unit tests on a Docker image running Windows. This will at least be done for the latest version of Python, not sure if we want/need to test all versions of Python on both Linux and Windows. TBD, open to comment.
- [ ] Understand and resolve any new unit test failures that show-up on Windows.

**Comment by mikebaumann** [comment]
Issue moved to [HumanCellAtlas/dcp-cli #260](https://github.com/HumanCellAtlas/dcp-cli/issues/260) via [**ZenHub**](https://www.zenhub.com/)
