### ISSUE TITLE
git-secrets installed for all developers for each repo

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#1933]
Trent to review that team has git-secrets for each repo

# DoD
Check that everyone has installed and is using git-secrets on the DSS repo at least
- [x] @amarjandu 
- [x] @xbrianh 
- [x] @DailyDreaming 
- [x] @mikebaumann 
- [x] @Bento007 
- [x] @natanlao

**Comment by Bento007** [comment]
@kozbo I have personally verified that the above developers have git-secrets installed and functioning for the data-store repo. @amarjandu verified @Bento007

**Comment by kozbo** [comment]
Hi @Bento007 I just saw Andrey's comment about git-secrets needing more configuration in order to catch Google service account credential commits:
https://cloud.google.com/blog/products/gcp/help-keep-your-google-cloud-service-account-keys-safe

Did you check these when you surveyed everyone?

**Comment by Bento007** [comment]
Nope
