### ISSUE TITLE
A developer onboarding and offboarding process is followed

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/data-store#1945]
As a DCP stakeholder
I want an onboarding and off-boarding process to be followed for developers
so we maintain the integrity of the DCP source code when people leave the team.

We need to follow an onboarding and off-boarding process both:
- at the DCP level - that addresses things such as GitHub organization access and PaaS access
- and at the component/ team level, that addresses specific needs for that component

Onboarding and offboarding documents should be linked to from the [DCP Ops Wiki Home](https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/wikis/home)

**Comment by brianraymor** [comment]
Removed _General Availability_ as the Release. Is this intended to be Q3?

**Comment by kozbo** [comment]
@rhiananthony @amarjandu Please review my changes to on-boarding and off-boarding checklists
here: https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/wikis/home

**Comment by kozbo** [comment]
@rhiananthony provided a link to this doc:
https://docs.google.com/document/d/1JaPVqhqb9WmJLz-euZZBhjWoo7IeZzOPvXb9LS6V_IQ/edit?ts=5d38b8ea&pli=1#
this looks good to me.
