### ISSUE TITLE
Review HCA repositories and verify that the list of readers/writers is following principle of least access

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/data-store#1948]
The HumanCellAtlas GitHub teams have been restructured.
To ease the transition to this structured world, everyone is currently in a team called "HCA" that has WRITE access to all repos.  We want to move away from this.

Each component team lead needs to audit the GitHub teams that have access to their repos.
Ensure only appropriate teams (e.g. CZI, UCSC, etc) have write access to your component's repos.
Ensure that you approve of any collaborators.
Then remove access from team HCA.

**Comment by stahiri** [comment]
@Bento007 - are we on track to complete this during Q2?

**Comment by Bento007** [comment]
Yes this is complete

**Comment by brianraymor** [comment]
Updated release to match milestone.

**Comment by kozbo** [comment]
Found a couple more upon review. Fixed now.
