### ISSUE TITLE
Static/Dynamic Analysis w/Trufflehog.

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/data-store#1949]
As a dcp developer
I want to run static analysis tools on my code
to help not ship code with gaping security holes in it.

There has been talk of running `trufflehog`, a tool to find embedded secrets in code before it is pushed.
The DevSecOps team needs to decide what static analysis tools to encourage/mandate.
Then we update the tickets in the component repos with these instructions.

**Comment by DailyDreaming** [comment]
3 PRs merged.  This now checks the data-store and dcp-cli:
https://github.com/HumanCellAtlas/data-store/pull/1985
https://github.com/HumanCellAtlas/dcp-cli/pull/283
https://github.com/HumanCellAtlas/dcplib/pull/10

Follow-up ticket filed for DevSecOps:
https://github.com/HumanCellAtlas/dcp/issues/325
