### ISSUE TITLE
Tombstone duplicate analysis bundles

### ISSUE THREAD

**Issue by parthshahva** [HumanCellAtlas/data-store#1950]
82132ed4-d846-42aa-8ebd-2a764828552a.2019-02-01T204150.737971Z
438bd353-df06-4ffa-8ab9-fd1a757567c3.2019-02-01T234253.013693Z
59acd75d-2f59-414e-8266-7ebc50c5a115.2019-02-02T004534.387514Z

**Comment by parthshahva** [comment]
cc @xbrianh @hannes-ucsc

**Comment by xbrianh** [comment]
These bundles were tombstoned on 6-March
