### ISSUE TITLE
Sync daemon:  fault tolerance

### ISSUE THREAD

**Issue by kislyuk** [HumanCellAtlas/data-store#196]

**Comment by kislyuk** [comment]
Still working on this. Using DLQs for fault tolerance.

**Comment by kislyuk** [comment]
Implementation notes:

- Write a LambdaExecutor with the same API as concurrent.futures
- When running on a Lambda, Executor runs within a chained execution context (which relaunches itself before the Lambda times out) - cf. Tony's work
- Failures are sent to a DLQ SQS
- Cleanup daemon runs on a cron schedule
- What does cleanup logic look like?

**Comment by ttung** [comment]
will address as part of #592
