### ISSUE TITLE
Clarify, and fix, test expectations

### ISSUE THREAD

**Issue by xbrianh** [HumanCellAtlas/data-store#1966]
The DSS has two types of tests:
- "standalone tests" which should not depend on deployed components
- "integration tests" which depend upon deployed components

It's reasonable to expect standalone tests to pass independently of deployment. This expectation should be realized:
1. verifying that all standalone tests do not depend on deployed components
2. transforming standalone tests into integration tests when they do depend on deployed components
3. clarifying in the readme that standalone tests should pass before initial deployment

**Comment by natanlao** [comment]
> The tests in `tests/test_indexer.py` change behavior based on testmode: https://github.com/HumanCellAtlas/data-store/blob/0da3e3819abeccd84fb530e4d0b57640d2baa612/tests/test_indexer.py#L88

> The test decorator PR causes some tests to be changed from `standalone` to `integration`

> This may not be an obvious fix, so I propose we back out the PR for repairs.

> We can apply it again later when it’s fixed.
