### ISSUE TITLE
Error when exporting imaging bundle in dev environment

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/data-store#1972]
I submitted the first test imaging dataset in dev environment and got the following error after some delay.

Submission ID: 5c868cc87e0bec000812d029
The dataset has 1 bundle with 227 files. 

![Screenshot 2019-03-12 at 09 06 58](https://user-images.githubusercontent.com/38244059/54275408-6be8e180-4582-11e9-8265-43c74ef3b3dd.png)

**Comment by xbrianh** [comment]
Hi @zperova, dev can be a volatile environment. Can you try again and let us know if the problem persists?

**Comment by kozbo** [comment]
@zperova We will need more information on this to proceed

**Comment by zperova** [comment]
@kozbo @xbrianh I have since tried in integration and did not get the error. I am now waiting for dcp-diag tool to get fixed to check that the exported imaging bundle is correct (and has been indeed exported). If there is another way of checking I would appreciate your advice on this.

**Comment by kozbo** [comment]
Closing. Please reopen if the issue crops up again
