### ISSUE TITLE
Exclude deprecated prod dataset; include new version of dataset

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/data-store#1976]
I have recently re-ingested the meyer dataset in prod to remove redacted external accessions.

Could you please: 
- [x] exclude the old version of the dataset (submission ID: `5c07e2029460a300075019b1`; project UUID: `209e6402-d854-49ea-815f-421dae5e3f4d`)
- [x] include the new version of the dataset (submission ID: `5c863a8bcefdf1000731395f`; project UUID: `6ac9d7b5-f86d-4c23-82a9-485a6642b278`)

The new IDs have been updated in the CBeta spreadsheet. This issue is also listed in Azul https://github.com/DataBiosphere/azul/issues/786 . I was unsure in which repo the work needs to be done, but @parthshahva has indicated:

> Azul handles tombstone notifications now, so I think the best path here is to just tombstone the underlying bundles rather than depending on Azul exclusion list. Azul inclusion listing may still have to occur.

Thank you!

**Comment by hannes-ucsc** [comment]
Yes, I'd vote for deleting the bundles in 209e6402-d854-49ea-815f-421dae5e3f4d, too, as opposed to excluding the project from the data browser only.

**Comment by hannes-ucsc** [comment]
@malloryfreeberg, you you double check whether the inclusion is necessary? I see 6ac9d7b5-f86d-4c23-82a9-485a6642b278 already in the browser.

**Comment by malloryfreeberg** [comment]
> @malloryfreeberg, you you double check whether the inclusion is necessary? I see 6ac9d7b5-f86d-4c23-82a9-485a6642b278 already in the browser.

Ah yes, I see it now! Cool, I wasn't sure what the current process was for making sure that datasets we want in the prod DS are viewable in the browser. I tried to put the requirements in the ticket instead of the implementation. Looks like that point is satisfied.

**Comment by hannes-ucsc** [comment]
I've suppressed 209e6402-d854-49ea-815f-421dae5e3f4d for now but see https://github.com/HumanCellAtlas/dcp/issues/320.
