### ISSUE TITLE
Cost Explorer Analysis

### ISSUE THREAD

**Issue by amarjandu** [HumanCellAtlas/data-store#1980]
we want to be able to look at costs associated with the DSS + find better ways to track these costs. 

## User story
* As a system administrator
* I want to get an accurate cost accounting of the system 
* so that we can manage costs

## Definition of done
Note: work with Andrey on tag format, propose formats for DSS
 - [x]  Figure out how to use Terraform to tag such that the Cost Explorer can track work
 - [x]  Make sure every component is tagged
 - [x]  review usage to look for waste, build list for review by Brian before cleaning up
 - [x]  modify on-boarding docs for how to tag properly

https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/wikis/Setting%20up%20the%20AWS%20Console%20and%20AWS%20CLI%20to%20work%20with%20HCA%20DCP

**Comment by amarjandu** [comment]
## Notes

Ideally there should be a default tag that can be applied by anything that's created within the Terraform, this minimizes the code needed to maintain. 
perhaps something like https://github.com/hashicorp/terraform/issues/2283#issuecomment-373242151 is applicable.

**Comment by kozbo** [comment]
(from Andrey) standardize on common tag names
(and meanings)
We have to put that information out asap
even if tag names change, that’s not as big of a deal
because the important part is for team members to go into their IaaS code and put tags in place
in fact I already have this information from CZI infra
```tags = {
    managedBy = "terraform"
    Name      = "${var.project}-${var.env}-${var.service}"
    project   = "${var.project}"
    env       = "${var.env}"
    service   = "${var.service}"
    owner     = "${var.owner}" // where owner is an email
  }

**Comment by kozbo** [comment]
This task  `Make sure every component is tagged` will be moved to the next sprint in a new issue

**Comment by kozbo** [comment]
#1997 covers the resource tagging
