### ISSUE TITLE
Exclude production Meyer dataset

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/data-store#1981]
I have re-ingested the meyer dataset in prod with a fix that will allow the pipelines to run.

Could you please: 
- [ ] exclude the old version of the dataset (submission ID: `5c863a8bcefdf1000731395f`; project UUID: `6ac9d7b5-f86d-4c23-82a9-485a6642b278`)

The new version of the dataset (submission ID: `5c8acacd53367400073122db`; project UUID: `5dfe932f-159d-4cab-8039-d32f22ffbbc2`) has already appeared in the Browser 👍 

The new IDs have been updated in the CBeta spreadsheet. Thank you!

**Comment by kozbo** [comment]
@hannes-ucsc @theathorn Can this be handled in the browser or do you need the old data deleted?

**Comment by malloryfreeberg** [comment]
Speaking with @hannes-ucsc, I should have made this in Azul's repo. Closing this ticket here and making a new one in Azul (can't move because Azul is not in HCA organization).
