### ISSUE TITLE
In Production delete the Cell Ranger data once the Optimus Prime secondary analysis workflow Is deployed

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-store#1982]
## User Story
There are 8 projects in Prod with "Library Construction Method" = "10x v2 sequencing".

Tim says “We are not in production. These will be reprocessed with Optimus Prime and the Cell Ranger output will be deleted.”

## Definition of done
Verify in the Data Browser that there are no projects run by the cell ranger pipeline.

**Comment by amarjandu** [comment]
@theathorn has this been resolved?

**Comment by theathorn** [comment]
I think so. Prod looks OK to me.
