### ISSUE TITLE
Deletion of 4 duplicate bundles in Tabula Muris dataset in production

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/data-store#1986]
Hi Blue box!

Some duplicate bundles were created for Tabula Muris in production. (See ticket for more details: https://app.zenhub.com/workspaces/dcp-backlogs-5ac7bcf9465cb172b77760d9/issues/humancellatlas/ingest-central/343)

Requesting deletion of the following duplicate bundles in Tabula Muris dataset in production.

```
80ccaf4e-5284-4a94-8cd4-bba8975b1dd8:2019-02-27T210613.175220Z
ca96fdee-ec34-410b-a4ec-fcd2e45ea2aa:2019-02-27T124054.618798Z
7db2a517-4a2a-40f2-bfcf-4ff3164472ff:2019-02-27T131454.896835Z
fba487be-4c3b-4d52-bb4b-311f4715ab26:2019-02-27T023445.174104Z
```

Thanks!

**Comment by xbrianh** [comment]
This has been addressed over the course of re-ingeston.
