### ISSUE TITLE
Bundles from Tabula Muris project are not indexed, no notifications sent

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-store#1990]
I was wondering today why the Tabula Muris project isn't displayed in the Data Browser on `prod`. The reason is that Azul didn't get any notifications for any of the bundles in that project. Why did it not get any notifications? Because the bundles in that data set are not indexed into DSS' Elasticsearch index. They all have an empty dictionary under `files` and a `shape_descriptor` of `"None"`.

```
curl -X POST "https://dss.data.humancellatlas.org/v1/search?output_format=raw&replica=aws&per_page=10" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{ \"es_query\": { \"query\": { \"bool\": { \"must\": [ { \"range\": { \"manifest.version\": { \"gte\": \"2019-03-21\" } } } ], \"must_not\": [ { \"exists\": { \"field\": \"files.project_json\" } }, { \"term\": { \"admin_deleted\": true } } ] } } } }"
```

Gives

```
{
  "es_query": {
    "query": {
      "bool": {
        "must": [
          {
            "range": {
              "manifest.version": {
                "gte": "2019-03-21"
              }
            }
          }
        ],
        "must_not": [
          {
            "exists": {
              "field": "files.project_json"
            }
          },
          {
            "term": {
              "admin_deleted": true
            }
          }
        ]
      }
    }
  },
  "results": [
    {
      "bundle_fqid": "fef17981-b033-45c1-8773-187295541369.2019-03-21T130451.298280Z",
      "bundle_url": "https://dss.data.humancellatlas.org/v1/bundles/fef17981-b033-45c1-8773-187295541369?version=2019-03-21T130451.298280Z&replica=aws",
      "metadata": {
        "files": {},
        "manifest": {
          "creator_uid": 8008,
          "files": [
            {
              "content-type": "application/json; dcp-type=\"metadata/biomaterial\"",
              "crc32c": "56227e58",
              "indexed": false,
              "name": "cell_suspension_0.json",
              "s3-etag": "ef727ab87f1c8776427edefe8ccbc428",
              "sha1": "b0c486c12338f82484c350cf03d1eb7c0bb56887",

>8 SNIP 8<


              "sha1": "5929e6fecd672ee866230b6e2d12880d5938c036",
              "sha256": "5962fa54fd7ededeb65c57083dac4b4309c54651175f67e6840e6b0bcb357630",
              "size": 20457237,
              "uuid": "0336cbfb-938b-4a25-9426-81062de24fbe",
              "version": "2019-03-21T131517.067851Z"
            }
          ],
          "format": "0.0.1",
          "version": "2019-03-21T131519.123515Z"
        },
        "shape_descriptor": "None",
        "state": "new",
        "uuid": "f78846b7-152b-414e-9707-74efbc1232c1"
      },
      "search_score": null
    }
  ],
  "total_hits": 349
}
```

The Azul subscription query requires that at least `files.project_json` is present.

**Comment by xbrianh** [comment]
After some digging, It looks like every file in the bundle returned by the above query is marked `indexed: false`. This would prevent metadata from being indexed. If this is the case, it's unlikely this bug is in the DSS.

My script:
```
from hca.dss import DSSClient

client = DSSClient(swagger_url="https://dss.data.humancellatlas.org/v1/swagger.json")
replica = "aws"

q = {
    "query": {
      "bool": {
        "must": [
          { 
            "range": {
              "manifest.version": {
                "gte": "2019-03-21"
              }
            }
          }
        ],
        "must_not": [
          { 
            "term": {
              "admin_deleted": True
            }
          }
        ]
      }
    }
}

for bundle_fqid in [hit['bundle_fqid'] for hit in client.post_search.iterate(replica=replica, es_query=q)]:
    uuid, version = bundle_fqid.split(".", 1)
    manifest = client.get_bundle(uuid=uuid, version=version, replica=replica)
    indexed_files = [f"{md['uuid']}.{md['version']}" for md in manifest['bundle']['files']
                     if md['indexed'] == True]
    print(bundle_fqid)
    for file_fqid in indexed_files:
        print("\t", "indexed file:", file_fqid)
```

**Comment by aaclan-ebi** [comment]
It might be that the flag to not indexed bundles is ticked in the Ingest UI when this dataset was submitted  :-(  This has happened before and @xbrianh created this script https://gist.github.com/xbrianh/b7a0a31dd1db2a0f909f0aba4115332b

After discussing with the team, we decided to do similar approach to recreate the 99,840 bundles with same bundle uuid, but new version. Then we'll keep track of the old versions to be deleted later. We'll coordinate the  list of 99,840 old bundle versions later to you guys.

**Comment by rolando-ebi** [comment]
Will be running a script today to index all the metadata Files in these bundles. Will track the old uuid+versions to be tombstoned and will post here

**Comment by rolando-ebi** [comment]
@hannes-ucsc @xbrianh the first pass of the script failed halfway through due to service token timeout. I ran it again and got the same error after a certain point. Just realised as well that this may have caused lots of unnecessary indexing attempts. I'm going to rewrite the script to re-init the DSSClient per request to ensure a fresh token. Hopefully the next attempt works. @hannes-ucsc if possible, can you disable notifications until this script is successful?

**Comment by hannes-ucsc** [comment]
@rolando-ebi, I wouldn't worry about the notifications. This is a good test of bundle versioning in Azul. Even if we disabled the notifications, Azul is still going to see all the intermediate versions (those from the failed attempts) when it's reindexing.

It would have been nice to make the script idempotent, so that it doesn't create a new bundle version if the existing bundle version already has the correct value in `indexed` for all metadata files.

**Comment by rolando-ebi** [comment]
@hannes-ucsc @xbrianh this is completed now. Brian, I'll send a json file in slack detailing the 99,840 bundle UUIDs and the version we want to keep. All other versions of the bundles should be tombstoned

**Comment by xbrianh** [comment]
What are the consequences of not tombstoning the old versions?

**Comment by rolando-ebi** [comment]
The old versions are dupes from a content perspective, thought we wanted production to be really clean in that sense. Due to errors when running the script there are old versions of these bundles that are indexed. If there's no need for this then it's ok to not tombstone/delete from my point of view.

**Comment by xbrianh** [comment]
Closing this as the underlying issue has been resolved by re-versioning Tabula Muris bundles. 

Tombstoning track via https://github.com/HumanCellAtlas/data-store/issues/2004
