### ISSUE TITLE
Tombstone old Tabula Muris bundles

### ISSUE THREAD

**Issue by xbrianh** [HumanCellAtlas/data-store#2004]
This issue tracks tombstoning related to https://github.com/HumanCellAtlas/data-store/issues/1990

**Comment by xbrianh** [comment]
@hannes-ucsc Do old versions need to be tombstoned to prevent visibility in the browser?

**Comment by rolando-ebi** [comment]
@xbrianh @hannes-ucsc I have a list(300k+) of old bundle FQIDs for Tabula Muris. The script used is here: https://github.com/HumanCellAtlas/ingest-central/blob/master/scripts/submission-index/src/app.py Please verify and delete as necessary. I will post the output of the script to data-store slack channel

**Comment by hannes-ucsc** [comment]
@hannes-ucsc Do old versions need to be tombstoned to prevent visibility in the browser?

No. But large amounts of of completely redundant bundle versions (as in "version was created in error") should be removed for our users and out own sanity. Redundant bundle version have a cost associated with them, for both computations and storage. That cost is only justified if the obsolete version has any value or had any value at all for anyone, developers or external users.

Note how I distinguish between redundant and obsolete. A redundant bundle version has zero value. and never did have any value. An obsolete bundle version did at some point in time.

**Comment by hannes-ucsc** [comment]
@rolando-ebi 

> I will post the output of the script to data-store slack channel

I reviewed and approved it. Thank you.

**Comment by kozbo** [comment]
These bundles are properly versioned so no need to delete. Closing
