### ISSUE TITLE
spike on working with Broad on MVP GCP DSS

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#2005]
## User story
* As a Broad developer
* I want to understand how the group development effort will function
* so that we can produce the end result

## Definition of done
Set of tickets prepared for the next sprint

**Comment by kozbo** [comment]
#2030 created, so closing this ticket

**Comment by amarjandu** [comment]
https://github.com/ucsc-cgp/team-redwood/issues/16
