### ISSUE TITLE
Spike - how to share a collection

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#2008]

**Comment by DailyDreaming** [comment]
This was discussed in stand-up and I believe an agreement was reached to simply use a new field associated with the collection to hold a list of users with read-permission.  The owner field will remain unchanged.  The special username "public" to be used to indicate that anyone has read-access.

**Comment by Bento007** [comment]
We need a way to modify the permission of the collection without creating a new version.
