### ISSUE TITLE
review results of Beta 2 and verify that this objective is met

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#2028]
Beta 1 failed in that data consumers could not easily get access to the most important metadata from one specific project in a digestible format. 

Demonstrate that Beta 2 users do not have the same problem and this issue is closed

**Comment by theathorn** [comment]
What is "this objective"?

**Comment by kozbo** [comment]
This is really an AC for the main Epic, MVP for improved metadata access for the end user. Closing.
