### ISSUE TITLE
Capture appropriate alerts and audit trails so we can handle detected attacks and understand the consequences of emergent threats and breaches

### ISSUE THREAD

**Issue by stahiri** [HumanCellAtlas/data-store#2037]
As specified in the [Q2 Roadmap] (https://docs.google.com/spreadsheets/d/1iAL2JR3ndgMmYwojUU0kU8Pm7B7ycRLt_973seREd3M/edit#gid=1107068822&range=C10).

We need appropriate alerts and audit trails so we can learn about and appropriately handle detected attacks and understand the consequences of emergent threats and breaches. This includes being able to know when an attack is taking place and being able to see in the logs what the attack entailed (what attacker accessed, changed, etc.).

__Deliverable__:
Ensure each component captures audit logs for the following types of events (as appropriate):
 - [ ] Server alerts and error messages
 - [ ] User log-on and log-off (successful or unsuccessful)
 - [ ] System administration activities
 - [ ] Modification of privileges and access
 - [ ] Modifications to the application
 - [ ] Application alerts and error messages
 - [ ] Configuration changes
 - [ ] Account creation, modification, or deletion

**Comment by stahiri** [comment]
@kislyuk @Bento007 @parthshahva @xbrianh - what would you expect the cost of this task to be (using the t-shirt sizing guidelines)?

**Comment by stahiri** [comment]
@Bento007 + @kozbo - is this still on track for Q2 completion?

**Comment by Bento007** [comment]
I believe it's complete but I'm uncertain how to test this. Can you help
clarify the definition of dobe.?

**Comment by stahiri** [comment]
In this case, I'd expect that logs from above which are relevant to data store would be collected by or pushed to something like Cloud Watch or Stackdriver where they are stored and can be referenced. Regarding events, I would expect to see:
* Server alerts and error messages (more relevant to the APIs)
* System administration activities (e.g., creating or removing buckets, changing bucket configurations, creating or removing APIs, API server configs)
* Modification of privileges and access (applicable to internal privileged users)
* Modifications to the application (APIs)
* Application alerts and error messages (APIs)
* Configuration changes
* Account creation, modification, or deletion (IAM capture for AWS or GCP account roles)

**Comment by Bento007** [comment]
In that case this has been done for a long time.

**Comment by stahiri** [comment]
Great, thanks. Closing!
