### ISSUE TITLE
Provide public access to HCA DSS checkout buckets

### ISSUE THREAD

**Issue by mikebaumann** [HumanCellAtlas/data-store#2055]
## User story
* As a researcher (end user running analysis on HCA data) 
* I want to get cloud native file URLs and be able to access the data (in the checkout bucket)
* so that I can successfully run my analysis.

This change would make the existing `GET /bundles/{uuid}` (with `directurls=true`) generally/broadly useful (beyond the current small whitelist on the checkout bucket) and is required for #2045 to be generally useful.

It is understood that this change may have limited duration, depending on the design and timing of DSS changes to support controlled access data.

This request is motived by the current HCA Data Browser handoff to Terra effort.

## Definition of done
The checkout buckets of all replicas for all HCA DSS deployments are publicly accessible.

**Comment by kislyuk** [comment]
I think this should not be done. See the discussion in https://github.com/HumanCellAtlas/data-store/issues/2045. Alternatively, the "bring your own bucket" checkout service functionality (planned but not implemented) could be implemented.
