### ISSUE TITLE
Create an enumeration endpoint for the DSS

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#2066]
## User story
* As a user of the DCP (possibly a tertiary portal developer)
* I want to be able to iterate through all the bundles in the DSS
* so that I can build my own index without using Elastic search to list the contents

## Definition of done
 
Document implementation within ticket; keep discussion here

**Comment by DailyDreaming** [comment]
Closing, as this is a duplicate of #2292.
