### ISSUE TITLE
Provide a meaningful indication of data retrieval/access duration

### ISSUE THREAD

**Issue by mikebaumann** [HumanCellAtlas/data-store#2101]
As an external workflow service provider (or researcher using an external workflow service),
I want a meaningful indicator of the duration required to retrieve/access HCA data, 
so that long durations/delays can be handled appropriately.

This issue stems from collaboration with the Broad on the "HCA handoff to Terra".
Currently, the HCA file checkout process typically completes within a few minutes, even for large files. When support/use of cold storage is added, delays may be much longer.
If the data access (including the checkout process) is performed during workflow execution, costly resources may be tied-up/wasted while waiting for the checkout.
Consequently, it is important to be able to identify if data retrieval/access times are going to be (excessively) long, so they may be handled accordingly.

Currently, for `GET /bundles` and `GET /files` the 301 response `Retry-After` value is hard-coded to 10 seconds. This is not helpful/appropriate if the retrieval (e.g. from cold storage) could take many minutes, hours or days.

I don't know what indications of estimated retrieval time the various cold storage mechanisms (or other potential sources of delay) currently provide, or may provide in the future. Whatever information is available and relevant should be used to provide a more meaningful value in the `Retry-After` header.

Additionally, it may be useful to provide an indication of the current storage type (online, nearline, etc.), perhaps in the header values returned by `HEAD /files` and the manifest returned by `GET /bundles`.

**Comment by kozbo** [comment]
addressed by TTFB #2206 
Closing in favor of that issue
