### ISSUE TITLE
Expose sync status in DSS health endpoint

### ISSUE THREAD

**Issue by xbrianh** [HumanCellAtlas/data-store#2102]

**Comment by amarjandu** [comment]
Showing status with a lvl3 health check would be problematic as a endpoint that would have to be polled. Placing a cloudwatch alert + an alert to the #data-store-eng slack channel would provide much better visibility to failures.

**Comment by amarjandu** [comment]
https://github.com/HumanCellAtlas/dcp-monitoring/pull/27
