### ISSUE TITLE
Impact of expiration/removal from checkout bucket on current users

### ISSUE THREAD

**Issue by mikebaumann** [HumanCellAtlas/data-store#2105]
It seems automatically expiring/removing files from the checkout bucket will negatively impact current users of (presigned or cloud native) URLs to the checkout bucket.
This is especially a concern when when the URLs are being used for longer-running workflows or other analysis. I was told (but have not verified) that files are expired/removed based on the time the file was created in the checkout bucket, rather than the most recent time the file was accessed or a presigned URL for it was generated, etc.

Therefore, it seems there is a significant risk of users suddenly and unexpectedly getting a 404 (not found) when accessing files via URLs to the DSS-managed checkout bucket. This may be especially true when accessing popular files, those that are already checked out due another users request, and for which their current `GET /files` request may be close to the expiration/removal of the file.
If this were to occur, it would be frustrating to users whose workflow/analysis just failed for this reason, and not clear to them why they need to `GET` their file again and wait while it is checked out again.

Does the DSS currently provide handling of this case, or is there a plan to do so?

Related to #2100, #2045

**Comment by xbrianh** [comment]
The DSS does not handle the case of presigned URL lifetimes overlapping checkout cache expiration. I think this should be regarded as a bug, and the DSS should either:
  1. Extend the lifetime of expired objects, or
  2. if 1 is not possible, check out the file again.

**Comment by ttung** [comment]
IIRC, checkouts have a publicly advertised TTL and an internal TTL.  The internal TTL is intentionally longer to make it work for this scenario.  You should just make the internal TTL longer than (publicly advertise TTL + presigned URL lifetime).

**Comment by mikebaumann** [comment]
Thanks, @ttung. That helps, yet I think there is still a problem with the DSS as currently configured, when multiple requests for data (e.g. by different end-users) are made over time.

The current values in use by the DSS appear to be:
https://github.com/HumanCellAtlas/data-store/blob/56b59d7a3a478a417df65db575b5760e38bdfe51/environment#L80-L81

And with the logic used by `GET /files` here:
https://github.com/HumanCellAtlas/data-store/blob/120859043315535397633596e7f7622cfebc1c75/dss/api/files.py#L138-L144

It seems that if, for example, a second user were to request a `GET /file` operation > 3 days and < 4 days after the creation date of the checkout file, the file could still end-up being removed from the checkout bucket before the public TTL of 4 days for the second user expired. This would be a problem for cloud native URLs (directurl(s)) or longer lived (multiday) presigned URLs, if support is added for those, that are expected to be good for the full public TTL.

It seems this specific case could be mitigated/eliminated increasing the internal TTL such that:
```
DSS_BLOB_PUBLIC_TTL_DAYS > (2 * DSS_BLOB_PUBLIC_TTL_DAYS)
```

**Comment by ttung** [comment]
Yes the private TTL - public TTL must be greater or equal to the private TTL.
