### ISSUE TITLE
Provide multiple search output options

### ISSUE THREAD

**Issue by mikebaumann** [HumanCellAtlas/data-store#212]
Currently DSS search always formats results as a list of bundles.
Other output formats should be supported, including:

- A format that includes the matched index document
- A (relatively) "raw" format that could return the results of queries such:

> Please give me a list of all the contact emails and titles for all the projects, and how many samples and files each has.

and other queries specifically written to return a subset of the available data

**Comment by Bento007** [comment]
I need more information on how we want the output format and the different options we want to support. @mikebaumann @sampierson @briandoconnor @dshiga

**Comment by kislyuk** [comment]
Update from sprint review: Began work on an optional parameter to include raw indexed metadata from the search hit.
