### ISSUE TITLE
extend checkout caching to more types of files

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#2128]
## User story
* As a developer
* I want to get a copy of some of the source data files without waiting for them to copy to the4 checkout bucket
* so that my performance is better

## Definition of done
-->

**Comment by kozbo** [comment]
@kislyuk I think that you mentioned that we should consider this. Which types of files were you thinking about doing this with?

**Comment by xbrianh** [comment]
Closing this until the DSS is informed of a specific need to increase the scope of checkout caching.
