### ISSUE TITLE
The format of the bundle url returned by dss search is incorrect

### ISSUE THREAD

**Issue by mikebaumann** [HumanCellAtlas/data-store#213]
A dss search currently returns a list of bundles, and that list includes a url with the following format:

 "bundle_url": "https://hca-dss3.ucsc-cgp.org/v1/bundles/5f312ab8-2a4d-46f0-8451-865f753849a3.2017-07-07T010028.722578Z"

Instead, it should be formatted as:

 "bundle_url": https://hca-dss3.ucsc-cgp.org/v1/bundles/5f312ab8-2a4d-46f0-8451-865f753849a3?version=2017-07-07T010028.722578Z&replica=aws

In order for it to successfully access the bundle manifest.

**Comment by Bento007** [comment]
Fixed in #374
