### ISSUE TITLE
tombstone old projects in Prod

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#2139]
Obsolete DCP submissions are being tracked [here](https://github.com/DataBiosphere/azul/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+exclude) using the "exclude" keyword. The following  projects should be tombstoned (showing submission id and project uuid):
  - [ ] _ neuron_diff 1_: `5cb75991d96dad0008532bdb` `b6dc9b93-929a-45d0-beb2-5cf8e64872fe`
  - [ ] _ neuron_diff 2_:  `5bf53a6a9460a300074dc824` `f8880be0-210c-4aa3-9348-f5a423e07421`
  - [ ] _bone marrow (ido_amit)_: `5cb8e061d96dad000854f36e` `e1f2a0e4-1ec8-431e-a6df-c975b3a1131f`
  - [ ] _cardiomyocytes_basu (basu)_ `5c06a9cf9460a300074fc183` `c765e3f9-7cfc-4501-8832-79e5f7abd321`
  - [ ] _kidney_biopsy_scRNA-seq (humphreys)_ `5c06c6ad9460a300074fc27f` `34ec62a2-9643-430d-b41a-1e342bd615fc`
  - [ ] _mouse melanoma_: `5cadbf5ad96dad0008504a58` `ccd8370a-84b8-464d-a87e-e688ac3e4f62`
  - [ ] _tissue sensitivity_: `5c8acacd53367400073122db` `5dfe932f-159d-4cab-8039-d32f22ffbbc2`
  - [ ] _cerebral organoid_: `5c2dfb101603f500078b28de` `d96c2451-6e22-441f-a3e6-70fd0878bb1b`
  - [ ] _EMTAB5061_: `5c054a529460a300074f5007` `1a0f98b8-746a-489d-8af9-d5c657482aab`
  - [ ] _pancreas6decades 1_: `5cd5973ed96dad00085668cb` `5e6c0ede-5648-4b0e-83ce-4644c437b4c0`
  - [ ] _pancreas6decades 2_: `5cd4445cd96dad000855adba` `dadbdb31-5f69-485b-85f3-b244b74123f1`
  - [ ] _pancreas6decades 3_: `5bdc209b9460a300074b7e67` `e8642221-4c2c-4fd7-b926-a68bce363c88`
  - [ ] _BM_PC_: `5bfe4d3a9460a300074eebc8` `1f9a699a-262c-40a0-8b2c-7ba960ca388c`
  - [ ] _CD4+ lymphocytes_: `5c055aca9460a300074f87da `  `0ec2b05f-ddbe-4e5a-b30f-e81f4b1e330c`

**Comment by xbrianh** [comment]
To tombstone a project in prod:
  1. Install the [DCP diagnostic tooling](https://github.com/HumanCellAtlas/dcp-diag) with `pip install dcp-diag`.
  1. Aquire the project submission id
  3. use the `analyze-submission` command to find primary and secondary bundles.
  4. Follow the instruction in the [tombstoning script](https://github.com/HumanCellAtlas/data-store/blob/master/scripts/tombstone_bundles.py). Note that this script requires bundle fqids, _not_ uuids.

**Comment by amarjandu** [comment]
What stage should we be reviewing with others in #dcp-ops(?), would that be at stage4 when we supply the populated fqid's into the script, before pressing the button?

**Comment by kozbo** [comment]
Please be sure not to delete the last copy of a project from Prod. Only delete the extra copies.

**Comment by parthshahva** [comment]
Can we ensure no projects are deleted before we confirm the results are complete for the new projects? As it stands, a lot of the new projects are missing bundles due to failed workflows and the such. We should avoid deleting complete, old projects until these are rectified

**Comment by kozbo** [comment]
OK, we will not delete any projects without clearance from all downstream components, including Brian's demo at the HCA meeting. We will proceed very conservatively. This will result in extra projects continuing to exist in the Data Store for a while longer. Azul will continue to blacklist these extra projects so they will not be visible from the browser.

Note that we will proceed with cleaning up the test data. see #2147

**Comment by hannes-ucsc** [comment]
Both the explict list of project UUIDs in the OT as well as the list of Azul issues linked from there are incomplete. The authoritative source of what should be removed is the blacklist in Azul's. Right now that list is a whitelist (https://github.com/DataBiosphere/azul/blob/cc04d30479e9c9b52e42ac72b62b600374100aa7/src/azul/project/hca/__init__.py#L85) but it will be reverted to to a blacklist (https://github.com/DataBiosphere/azul/blob/e98e0e34aabf3c814923a8e8ee249b9f7f0609a7/src/azul/project/hca/__init__.py#L85) again in one week after the Japan demo. 

The above links will be out of date by then. Please use the latest version of the linked file on the prod branch or ask me to provide an up-to-date link.

**Comment by kozbo** [comment]
List provided by Trevor. We will need downstream approval on these
BM_PC (4/18/19): e1f2a0e4-1ec8-431e-a6df-c975b3a1131f
HPSI human cerebral organoids (10/30/18): 2a0faf83-e342-4b1c-bb9b-cf1d1147f3bb
Human Hematopoietic Profiling (11/20/18): fd1d163d-d6a7-41cd-b3bc-9d77ba9a36fe
Kidney biopsy scRNA-seq (11/28/18): 1630e3dc-5501-4faf-9726-2e2c0b4da6d7
Mouse Melanoma (4/10/19): ccd8370a-84b8-464d-a87e-e688ac3e4f62
neuron diff (4/17/19): b6dc9b93-929a-45d0-beb2-5cf8e64872fe
neuron diff (5/10/19): 4129d036-67b9-4981-9d6d-3aaa235236d5
Single cell transcriptome analysis of human pancreas (5/9/19): dadbdb31-5f69-485b-85f3-b244b74123f1
Single cell transcriptome analysis of human pancreas (5/10/19): 5e6c0ede-5648-4b0e-83ce-4644c437b4c0 
Tissue stability (11/12/18): cf8439db-fcc9-44a8-b66f-8ffbf729bffa
Tissue stability  (3/11/19):  6ac9d7b5-f86d-4c23-82a9-485a6642b278
 Tissue stability (3/27/18): 6ec8e247-2eb0-42d1-823f-75facd03988d

**Comment by hannes-ucsc** [comment]
This is starting to get old. Please use the authoritative list in [Azul](https://github.com/DataBiosphere/azul/blob/prod/src/azul/project/hca/__init__.py#L85). If you disagree, state so explicitly and I will shut up and silently watch you delete the wrong projects. The only projects that are not mentioned on that Azul list are the test left-overs but those should be easy to spot?
