### ISSUE TITLE
Checkout Performance tuning

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#2141]
## User story
* As a user with a keyboard who is using the DCP 
* I want to run compute against the data directly in the cloud using compute environments such as Terra
* so that I don't have to maintain my own local cloud environment and compute infrastructure.

Users are confused by the long delays that can be incurred while accessing files that should be "local" in the cloud. They don't understand the need to make a copy to the checkout bucket. They don't understand the need to handle the "retry after" response. Their compute cluster and compute routines are not tuned to handle an in-determinant delay, and they don't want compute spinning while they wait for the data.

## Definition of done
Provide an API that will not return a retry-after unless the data is actually in cold storage

**Comment by ttung** [comment]
I think improving checkout perf is a great thing, and is something we should actively pursue.  If users' complaints is about having to handle the retry-after header rather than just checkout perf, then I would be concerned that there might not be the right abstractions in place.
