### ISSUE TITLE
For GS checkout caching, use `STANDARD` instead of `DURABLE_REDUCED_AVAILABILITY`

### ISSUE THREAD

**Issue by xbrianh** [HumanCellAtlas/data-store#2145]
Background information:
  - A test was performed using a Google bucket lifecycle policy set to delete all objects with storage class `STANDARD` in a multi-regional bucket. It was not obvious this would work since Google’s (often misleading) documentation indicated that `STANDARD` is an alias for `MULTI_REGIONAL`
  - However, it _did_ work: `STANDARD` objects were deleted while `MULTI_REGIONAL` objects remain
  - This is relevant for our meta-data checkout caching strategy, which uses GS bucket lifecycle rules for cache expiration.
  - This sort of storage class change, `MULTI_REGIONAL` -> `STANDARD`, makes GS bucket-to-bucket copies fast.

Related to #2124

**Comment by mikebaumann** [comment]
Any hope of achieving similar checkout performance gains on AWS?
It seems large file checkouts on AWS currently take ~30 seconds.

**Comment by xbrianh** [comment]
@mikebaumann I am not aware of S3 capabilities analogous to the apparent copy by reference behavior observed on GS. Unfortunately, unless new information comes to light, current S3 checkout performance is unlikely to be improved in the foreseeable future.

**Comment by mikebaumann** [comment]
I am confident in the data from @xbrianh that this will resolve the problem.
All the same, I am willing/available to rerun my simple checkout performance test script that produced the data reported in #2124 and provide updated results. If interested, please ping me when this change reaches the DSS `integration` deployment.

**Comment by xbrianh** [comment]
@mikebaumann We would be remiss to not verify our GS copy results. We'll ping you when this lands.

**Comment by xbrianh** [comment]
@mikebaumann This change has landed in the DSS integration deployment.
