### ISSUE TITLE
Tombstone test data in Prod

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#2147]
This list of bundles was generated with [bundle_roundup.py](https://gist.github.com/xbrianh/d9c5eaf557b3cf10957e110b34583533)

 - [ ] f738d2ba-e4de-446e-a59e-4c3920df2393.2019-05-16T150258.133000Z
 - [ ] f4151752-478a-4742-8977-dd44fe027bfb.2019-01-08T223501.790366Z
 - [ ] d2f09410-84d7-4db5-8d9f-a33bc6c362e5.2019-05-15T162516.124000Z
 - [ ] bab7b05c-818e-4fdd-9746-c64e9d394b88.2019-05-15T162439.120000Z
 - [ ] a3e76900-0903-4be7-bab3-50e2c74952e3.2019-05-15T174113.934000Z
 - [ ] 8b764b9a-d779-400f-82db-fe0ecbd3d84c.2019-05-16T130502.944000Z
 - [ ] 8a90a1f5-4383-4ae9-b0e0-efdba8001d97.2019-05-07T120332.046000Z
 - [ ] 71ee4b5e-3e81-42ab-8e93-2e5eedbafd93.2019-05-14T122844.491000Z
 - [ ] 5ccb4f5b-6193-493b-966f-9acc925b0812.2019-05-15T120436.413000Z
 - [ ] 52eaf933-2d2a-41f9-8d83-974b2e3e389e.2019-05-08T163641.020000Z
 - [ ] 3811cc61-66cd-4909-83fb-1cca18598136.2019-05-01T174816.216000Z
 - [ ] 35326897-8589-4b41-a6ae-dcd9b0aba733.2019-05-16T045418.419000Z
 - [ ] 2b584008-fcd2-43ad-8ad1-ab8a51a7ec3d.2019-05-15T120336.387000Z
 - [ ] 165f31b5-42fa-4498-8ba4-88b20487b11d.2019-05-08T152435.884000Z
 - [ ] 0bf23784-06e4-4208-97ac-e2652efe71f4.2019-05-14T122838.456000Z
 - [ ] 04d0c43b-9087-4162-aa5f-3a4f26778624.2019-05-08T152435.893000Z

text version:
f738d2ba-e4de-446e-a59e-4c3920df2393.2019-05-16T150258.133000Z
f4151752-478a-4742-8977-dd44fe027bfb.2019-01-08T223501.790366Z
d2f09410-84d7-4db5-8d9f-a33bc6c362e5.2019-05-15T162516.124000Z
bab7b05c-818e-4fdd-9746-c64e9d394b88.2019-05-15T162439.120000Z
a3e76900-0903-4be7-bab3-50e2c74952e3.2019-05-15T174113.934000Z
8b764b9a-d779-400f-82db-fe0ecbd3d84c.2019-05-16T130502.944000Z
8a90a1f5-4383-4ae9-b0e0-efdba8001d97.2019-05-07T120332.046000Z
71ee4b5e-3e81-42ab-8e93-2e5eedbafd93.2019-05-14T122844.491000Z
5ccb4f5b-6193-493b-966f-9acc925b0812.2019-05-15T120436.413000Z
52eaf933-2d2a-41f9-8d83-974b2e3e389e.2019-05-08T163641.020000Z
3811cc61-66cd-4909-83fb-1cca18598136.2019-05-01T174816.216000Z
35326897-8589-4b41-a6ae-dcd9b0aba733.2019-05-16T045418.419000Z
2b584008-fcd2-43ad-8ad1-ab8a51a7ec3d.2019-05-15T120336.387000Z
165f31b5-42fa-4498-8ba4-88b20487b11d.2019-05-08T152435.884000Z
0bf23784-06e4-4208-97ac-e2652efe71f4.2019-05-14T122838.456000Z
04d0c43b-9087-4162-aa5f-3a4f26778624.2019-05-08T152435.893000Z

**Comment by kozbo** [comment]
more integration test leftovers:

f7152c47-4ba7-4b29-9dbe-bf4dbc9faccb
ee777bd0-b70d-46ea-8488-3c635c0680a0
d90ca86f-6461-4db7-9e44-fd7c15f93947
4a6976fc-1add-4538-a410-4b8ecfd6d26d
ef2a1708-773c-4077-ae87-14c9c16fbdfe
6ccf02fe-7284-4e22-8f13-34cee293d003
24dce12d-c6d5-402d-b864-dbd4ac5bdf29

**Comment by xbrianh** [comment]
This will be handled during the resolution of #2139
