### ISSUE TITLE
Deletion Locking

### ISSUE THREAD

**Issue by xbrianh** [HumanCellAtlas/data-store#2153]
Entity deletions may not occur at precisely the same moment. To preserve replication consistency during deletion, UUIDs or FQIDs, including tombstones UUIds and FQIDs, should be locked.

Perhaps the DSS should consider returning 204 "no content" for GET requests on locked objects, and 409 "conflict" for PUT requests on locked objects.

**Comment by xbrianh** [comment]
@kislyuk @hannes-ucsc your input would be helpful.

**Comment by hannes-ucsc** [comment]
I think I need more context, @xbrianh.

Generally, I've never seen locking work well in combination with the eventually-only consistency guarantees that cloud-based object stores provide.

**Comment by xbrianh** [comment]
Race conditions exist when deleting objects from the main buckets, including tombstones, which may lead to replication inconsistencies. However, the risk seems small enough that locking logic is unwarranted. The DSS should periodically conduct replica consistency scans, perhaps once a quarter.
