### ISSUE TITLE
Can GCP checkouts be performed synchronously?

### ISSUE THREAD

**Issue by xbrianh** [HumanCellAtlas/data-store#2166]
bucket to bucket copies on GCP are fast when storage type is kept constant, and copy times do not appear to depend on file size. Some evidence is provided below.

Given this data, it seems reasonable to consider:
  1. Performing all GCP checkouts synchronously during GET /file, and
  2. Turning off checkout caching for GCP, which would simplify the DSS backend.

These are copy durations for bucket to bucket copies of two files. The script that produces this output is shown below.
```
{"size": 466, "duration": 1.7062091827392578}
{"size": 466, "duration": 0.6924893856048584}
{"size": 466, "duration": 0.7356328964233398}
{"size": 35218876396, "duration": 1.1874048709869385}
{"size": 35218876396, "duration": 0.9472086429595947}
{"size": 35218876396, "duration": 0.7123963832855225}
```

script:
```
import os
import time
import json
from concurrent.futures import ThreadPoolExecutor, as_completed

from google.cloud.storage import Client

gs = Client.from_service_account_json(os.environ['GOOGLE_APPLICATION_CREDENTIALS'])

def rewrite(src_bucket_name, dst_bucket_name, src_key, dst_key, storage_class="STANDARD"):
    """
    This impliments and times bucket to bucket copy via Google client libraries `rewrite` method
    """
    src_blob = gs.bucket(src_bucket_name).blob(src_key)
    dst_blob = gs.bucket(dst_bucket_name).blob(dst_key)
    if storage_class is not None:
        dst_blob._patch_property('storageClass', storage_class)
    token = None
    while True:
        token, rewritten, size = dst_blob.rewrite(src_blob, token=token)
        if token is None:
            break
    src_blob.reload()
    dst_blob.reload()
    assert src_blob.size == dst_blob.size

src_bucket_name="org-humancellatlas-dss-integration"
dst_bucket_name="bhannafi-dst"
source_keys = [
    "blobs/004a6f1824d8f79b4e087e9d2137313ccf31e2865e0ae9b27dd5b51338d4b4e1.5383c12875f166e599b5b74d8e8a4bb15e8b2820.d912d569b1cb646ceade126ecaa062af.13e5cbb8",
    "blobs/dedde43b055f5b0d7922bc744eee96d8d7a0028eaf4baa108c2f766ccf300cb3.0ed50e0e8556daadfe1a0494dac5280b2d9d0c0c.89ec6c22f21a24317564b3f8b81edfbb-525.4ef36cf2",
]
dst_key="test_gs_rewrite"

for src_key in source_keys:
    for _ in range(3):
        start_time = time.time()
        size = gs.bucket(src_bucket_name).get_blob(src_key).size
        rewrite(src_bucket_name, dst_bucket_name, src_key, dst_key)
        print(json.dumps(dict(size=size, duration=time.time() - start_time)))
```

**Comment by mikebaumann** [comment]
I think the copy time when the object in the main bucket is in cold storage needs to be understood before making this change. Google claims to provide fast response times for data in their cold storage services, yet I question whether the full object transfer time from the main bucket to the checkout bucket would be as fast as the times shown above. If it is, great! Yet, I am concerned about making a replica-specific optimization now that may need to be undone to utilize Google cold storage in the future.

**Comment by xbrianh** [comment]
@mikebaumann I agree that it is important to preserve current functionality for cold storage retrieval, and that this functionality should not be removed from the DSS.

With that being said, we can currently accomplish synchronous GCP checkouts the vast majority of the time while preserving current cold storage capabilities. In fact, it would only be cold storage checkouts that would respond asynchronously, although we may wish to occasionally force asynchronous responses so our clients don't forget how to handle them.
