### ISSUE TITLE
Quarterly Integration deployment data cleanup operations

### ISSUE THREAD

**Issue by xbrianh** [HumanCellAtlas/data-store#2167]
The DSS will periodically clean up test data in the integration deployment environment to remove out-of-date test data and reduce storage costs. Before beginning cleanup operations, the DSS will request downstream services to provide Exclusion Lists. An Exclusion List is a list of DSS entities that should _not_ be deleted.

Exclusion Lists should be provided by replying to this ticket, and updated by editing the reply. Components should indicate that their exclusion list is up to date using the checklist provided below.

The DSS will begin a cleanup operation by clearing the checklist, sending an email request to component leads, and pinging on the #dcp-ops Slack channel with "@channel". After every component has verified their Exclusion List, the DSS will ping the #dcp-ops Slack channel with "@channel," and begin the deletion operation after 1 hour.

Completed Exclusion Lists:
  - [ ] Ingest
  - [ ] DSS
  - [ ] Secondary Analysis
  - [ ] Azul/Data Portal
  - [ ] Matrix Service

**Comment by calvinnhieu** [comment]
SS2:
`5cb665f4-97bb-4176-8ec2-1b83b95c1bc0.2019-02-11T171739.925160Z`
`ff7ef351-f46f-4c39-b4c3-c8b33423a4c9.2019-02-11T124842.494942Z`
`aa8262c2-7a0e-49fd-bac1-d41a4019bd87.2019-02-10T234926.510991Z`
`0ef88e4a-a779-4588-8677-953d65ca6d9a.2019-02-10T124405.139571Z`
`c881020e-9f53-4f7e-9c49-d9dbd9e8f280.2019-02-09T124912.755814Z`
`343dbc5f-bfe8-4f51-b493-a508d017125c.2019-05-24T185218.516000Z`
`762fc144-a21b-4e57-bd1a-303f784b5209.2019-05-27T225255.145000Z`
`5593455b-c29b-4e89-ad61-df0662475560.2019-05-27T115454.035000Z`
`4831c57c-eba1-47bc-99f0-c0f1f4dd404a.2019-05-26T230420.837000Z`
`52aa29f7-5c71-4474-a01e-0e47111bb7dc.2019-05-26T120528.501000Z`

Optimus:
`2241e283-5d74-4623-85c1-74c1d4dd49bc.2019-05-24T200530.026000Z`
`1045bdbb-b44b-4106-9adc-e033ce017c19.2019-05-28T000505.539000Z`
`16363a98-cbd0-4826-ba8c-1ffa3b8e5ed8.2019-05-27T130928.590000Z`
`5f3a1fee-7079-4be4-9f87-5b473f18a18e.2019-05-27T001108.219000Z`
`34c03279-0c53-4564-a460-d4e0b4ad77ad.2019-05-26T130306.188000Z`

**Comment by amarjandu** [comment]
Closing this issue, q4 cleanups require new issues
