### ISSUE TITLE
Design support for bundle types in the DSS

### ISSUE THREAD

**Issue by xbrianh** [HumanCellAtlas/data-store#2173]
How should bundle endpoints accommodate type?  We may consider communicating type via `Content-Type` header on bundles objects, as well as including type in the bundle manifest.

See DCP Media types:
https://docs.google.com/document/d/1TqihrgXjct9aDmTJO52_gE2WlpFysB1OkG9C8exmWTw/edit

**Comment by kozbo** [comment]
Closing this. We will open issues in direct response to the bundle type RFC.
