### ISSUE TITLE
Complex Usage Notifications

### ISSUE THREAD

**Issue by amarjandu** [HumanCellAtlas/data-store#2177]
- [x] Number of bundles ingested over past 24 hours
  - [x] Number of bundles tombstoned over past 24 hours
  - [x] Number of bundles deleted over past 24 hours
  - [x] Data consumption in main and checkout buckets (is this easy to do?)

**Comment by amarjandu** [comment]
@xbrianh i have the Data Consumption working at the bucket level; but there is an issue with configuring the s3 bucket in Terraform and enabling the AWS S3 CloudWatch Metrics on the bucket. I dont see a way to perform this action in Terraform; It would have to be manually turned on by the DSS-Operator.

I can update with how to perform the required changes to the buckets within the `README.MD/#DSS-Monitor` section; the added benefit that the change **should** not cause collisions with `infra/buckets` changes.

**Comment by amarjandu** [comment]
@xbrianh Need to discuss differences between tombstone and deletions at API level.

**Comment by kozbo** [comment]
Need @lon for his prod credentials
