### ISSUE TITLE
Unhelpful Error Message Following Beginner Tutorial

### ISSUE THREAD

**Issue by jeffrey856** [HumanCellAtlas/data-store#2241]
While trying to run this command `hca dss upload --replica aws --staging-bucket staging_bucket_name --src-dir ${DSS_HOME}/tests/fixtures/datafiles/example_bundle` under "**Using the HCA Data Store CLI Client**"

I am getting this error:
```
`    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='dss.data.humancellatlas.org', port=443): Max retries exceeded with url: /v1/files/f5f4d516-c001-4745-b319-0b8a2664edc5?version=2019-07-10T191838.880240Z (Caused by ResponseError('too many 500 error responses',))
```

I have verified that the contents have been uploaded to the staging bucket on aws.

`

**Comment by kozbo** [comment]
pretty sure this is an auth error, which should return a 4xx level error
