### ISSUE TITLE
Document subscription delivery guarantees

### ISSUE THREAD

**Issue by kislyuk** [HumanCellAtlas/data-store#2253]
The Swagger API definition should document how long the v1 and v2 subscription/notification APIs try to deliver for.

**Comment by diekhans** [comment]
It should also make clear the requirements on the client if the message isn't handled.

**Comment by kislyuk** [comment]
> It should also make clear the requirements on the client if the message isn't handled.

@diekhans can you please elaborate what you mean by "message isn't handled"?

**Comment by diekhans** [comment]
"message isn't handled"  means whatever processing is required by the client in response to the message has not been completed when the DSS delivery guarantee expires.

**Comment by diekhans** [comment]
also, according to a conversation with @xbrianh , there are cases were messages will not be delivered due to lack of guarantees by underlying system (AWS).

**Comment by kislyuk** [comment]
Got it, so a clearer way to put it is "requirements on the client in case it is unreachable for a period of time that exceeds the delivery guarantee timeframe, and needs to re-synchronize state with DSS".

> there are cases were messages will not be delivered due to lack of guarantees by underlying system (AWS).

I think that concern is about as relevant in practice as worrying about an AWS region going offline. Yes, in extraordinary circumstances it is possible that the underlying system will temporarily stop working, and that manual intervention will be required. In case of the DSS, that intervention consists of re-running an internal consistency check that will requeue the relevant notifications when the DSS internal S3-SNS-SQS bus fails. The DSS delivery guarantee will **not** be violated in that case.

**Comment by xbrianh** [comment]
> also, according to a conversation with @xbrianh , there are cases were messages will not be delivered due to lack of guarantees by underlying system (AWS).

@diekhans This is an internal DSS issue that will be addressed.
