### ISSUE TITLE
Tombstone old Human Hematopoietic Profiling dataset in prod

### ISSUE THREAD

**Issue by willrockout** [HumanCellAtlas/data-store#2266]
The Human Hematopoietic Profiling (Pe'er, Profiling of CD34+ cells from human bone marrow to understand hematopoiesis) project has been re-ingested in prod.

Could the older version of the dataset (submission ID: 5c06cf339460a30007501909; project UUID: 29f53b7e-071b-44b5-998a-0ae70d0229a4) be tombstoned.

The new version of the dataset (submission ID: 5d30e0c49be88c0008a9b236; project UUID: 091cf39b-01bc-42e5-9437-f419a66c8a45) is exported.

**Comment by parthshahva** [comment]
Hi @kozbo @xbrianh do we know when we can get to this? This is currently one of the two remaining duplicated projects in prod DSS.

**Comment by xbrianh** [comment]
The following list of bundles will be tombstoned during this operation.

@parthshahva Can you verify?

[
  "c4252864-a0be-493f-a6a6-2e88c3ceecb2.2018-12-05T172226.170225Z",
  "ba060e18-e892-4dd2-bad2-c6b155479bde.2018-12-05T172228.493461Z",
  "b8ef9d90-b146-4758-90f8-5c8a663e3a19.2018-12-05T172227.731593Z",
  "afeea92f-74da-4743-ba01-fad56d73428c.2018-12-05T172231.390312Z",
  "a5cff2a4-50c2-4a72-b45e-0da39954206e.2018-12-05T172228.799174Z",
  "751536de-44ed-42f8-85a6-84670278f4e6.2018-12-05T172228.775288Z",
  "4f026ece-1622-4c32-909b-7961bf79871e.2018-12-05T172229.110571Z",
  "45c5f6cd-0536-4196-9ce5-23dd07eb9b81.2018-12-05T172229.846298Z",
  "188a356b-8c16-4aed-9053-5aa8bd8cceb1.2018-12-05T172229.725877Z",
  "129563ba-f698-412a-b94f-eadc4dd788e3.2018-12-05T172225.867650Z",
  "11be0dbd-ad77-49b9-8c46-ebb455e88eea.2018-12-05T172232.264458Z",
  "10984938-60ba-4e83-89cc-5af3c567e03d.2018-12-05T172229.940689Z",
  "0607f9e1-448b-4cdf-be84-dfc779001051.2018-12-05T172228.223558Z",
  "02aff667-9eba-4137-9de7-370c45577e35.2018-12-05T172228.216467Z"
]

**Comment by parthshahva** [comment]
This looks right to me

**Comment by xbrianh** [comment]
Done.
