### ISSUE TITLE
Tombstone Tabula muris dataset

### ISSUE THREAD

**Issue by jahilton** [HumanCellAtlas/data-store#2268]
project_uuid:f306435b-4e60-4a79-83a1-159bda5a2c79
Needs to be tombstoned/deleted prior to GA (deadline:July 31) even if the updated version has not been fully re-ingested by that time

**Comment by jahilton** [comment]
this is a duplicate of https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/databiosphere/azul/1128

**Comment by kozbo** [comment]
Tabula Muris bundles are being tombstoned, started 7/31

**Comment by xbrianh** [comment]
This is done.
