### ISSUE TITLE
DSS cleanup in integration

### ISSUE THREAD

**Issue by xbrianh** [HumanCellAtlas/data-store#2294]
DSS cleanup operations should be performed in the integration environment according to the DSS periodic cleanup SOP: https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/wikis/Periodic%20Cleanup%20of%20DSS%20Deployments

**Comment by kozbo** [comment]
Add Charles
Use Kharon

**Comment by amarjandu** [comment]
This is a DSS cleanup operation of the **Integration** stage of the DSS, scheduled for **08/12/2019.** Please add your Exclusion List (list of DSS bundles that should
not be deleted) by replying to this ticket. Mark your component off in the checklist
below to indicate that the operation may proceed.

This operation will not commence until the checklist is complete.

  - [ ] Ingest
  - [ ] DSS
  - [ ] Secondary Analysis
  - [ ] Azul/Data Portal
  - [ ] Matrix Service

**Comment by mckinsel** [comment]
Matrix service would like to keep
```
5cb665f4-97bb-4176-8ec2-1b83b95c1bc0
ff7ef351-f46f-4c39-b4c3-c8b33423a4c9
aa8262c2-7a0e-49fd-bac1-d41a4019bd87
0ef88e4a-a779-4588-8677-953d65ca6d9a
c881020e-9f53-4f7e-9c49-d9dbd9e8f280
343dbc5f-bfe8-4f51-b493-a508d017125c
```

**Comment by amarjandu** [comment]
Query Service does not rely on integration, no bundles requested.

**Comment by amarjandu** [comment]
Azul does not have bundles to save.

**Comment by amarjandu** [comment]
Data Portal does not have bundles to save.

**Comment by samanehsan** [comment]
Secondary analysis would like to keep the following bundles for internal integration testing:
- `bab542a6-7625-49ad-bef5-954e11419cf1.2019-02-05T230536.536155Z`
- `ca6ea399-7ddf-46e6-a904-4d5f02025231.2019-02-22T222251.233303`

**Comment by samanehsan** [comment]
@rexwangcc @ApChagi we also have integration bundles for mouse data right? Do you have the bundle uuids?

**Comment by ApChagi** [comment]
Yes. Thanks @samanehsan these are the mouse analysis and primary bundles we want to stick around!
`51d8eda8-bbd9-48ab-9ffc-00cf1cdef087.2019-08-05T141528.848170Z`
`c6cb322a-3d63-4a0b-8440-533da4febc63.2019-08-02T202139.757537Z`

**Comment by amarjandu** [comment]
ingest wranglers do not have bundles to save.

**Comment by amarjandu** [comment]
bundle whitelist:
```
5cb665f4-97bb-4176-8ec2-1b83b95c1bc0
ff7ef351-f46f-4c39-b4c3-c8b33423a4c9
aa8262c2-7a0e-49fd-bac1-d41a4019bd87
0ef88e4a-a779-4588-8677-953d65ca6d9a
c881020e-9f53-4f7e-9c49-d9dbd9e8f280
343dbc5f-bfe8-4f51-b493-a508d017125c
bab542a6-7625-49ad-bef5-954e11419cf1.2019-02-05T230536.536155Z
ca6ea399-7ddf-46e6-a904-4d5f02025231.2019-02-22T222251.233303Z
51d8eda8-bbd9-48ab-9ffc-00cf1cdef087.2019-08-05T141528.848170Z
c6cb322a-3d63-4a0b-8440-533da4febc63.2019-08-02T202139.757537Z
```

**Comment by amarjandu** [comment]
Cleanup has been completed in integration
