### ISSUE TITLE
Move secrets handling into dss/operations

### ISSUE THREAD

**Issue by xbrianh** [HumanCellAtlas/data-store#2296]
The secrets handling scripts `scripts/set_secret.py` and `fetch_secret.sh` should be moved into a new operational framework `dss/operations/secrets.py`.

This work should result in three commands:
  - [x] `scripts/dss-ops.py secrets list-secrets`
  - [x] `scripts/dss-ops.py secrets get-secret --secret-name`
  - [x] `scripts/dss-ops.py secrets set-secret --secret-name`. This should accept data from stdin

**Comment by kozbo** [comment]
add Charles

**Comment by chmreid** [comment]
The get-secret and set-secret functionality has been implemented; there are still a few open questions about the list-secrets functionality and about a test strategy, discussion happening in the pull request thread #2325 here: https://github.com/HumanCellAtlas/data-store/pull/2325/files#issuecomment-518739332
