### ISSUE TITLE
DSS Cleanup in Staging

### ISSUE THREAD

**Issue by xbrianh** [HumanCellAtlas/data-store#2300]
DSS cleanup operations should be performed in the integration environment according to the DSS periodic cleanup SOP: https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/wikis/Periodic%20Cleanup%20of%20DSS%20Deployments

**Comment by amarjandu** [comment]
This is a DSS cleanup operation of the **Staging** stage of the DSS, scheduled for **08/12/2019.** Please add your Exclusion List (list of DSS bundles that should
not be deleted) by replying to this ticket. Mark your component off in the checklist
below to indicate that the operation may proceed.

This operation will not commence until the checklist is complete.

  - [ ] Ingest
  - [ ] DSS
  - [ ] Secondary Analysis
  - [ ] Azul/Data Portal
  - [ ] Matrix Service

**Comment by mckinsel** [comment]
Matrix service would like to keep
```
d30147bb-5fa2-4444-ad62-398308e4f8d3
d9c742f0-b131-4e06-86d6-990f940c98a2
d63e36c0-ac2d-484d-9fd9-a111ebf8231a
9c8c5ba1-27fb-496f-9dfe-b605a9aa9658
7ba67071-6fb3-43f8-ada8-ed5993195e2b
119f6f39-d111-4c33-a3d5-224a67655b07
bffa26df-b1d4-439b-bb82-2d0a271ad0ef
```

**Comment by samanehsan** [comment]
Secondary analysis would like to keep "ea16ade3-15a8-4093-8f2a-60b6a483c7f4.2018-10-09T161711.201461Z". Are there any others @rexwangcc @ApChagi?

**Comment by amarjandu** [comment]
Ingest has commented "we don't care about no stinking bundles :)" 
Wranglers have a meeting Tomorrow 8-9am about the need to retain bundles, @willrockout states that there should be no need to retain any bundles, but will double check with the wrangler team at EBI.
Azul/Data Portal have expressed that they dont need to retain anything.

**Comment by amarjandu** [comment]
@ApChagi has expressed no need for other bundles to be saved in `staging`

**Comment by amarjandu** [comment]
Staging Inclusion List : 
[staging-inclusionlist.txt](https://github.com/HumanCellAtlas/data-store/files/3612321/staging-inclusionlist.txt)
