### ISSUE TITLE
Onboard Charles

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#2301]
Github user id? chmreid

**Comment by chmreid** [comment]
Is there an onboarding checklist somewhere? If not, I've kept some notes on what I've done for onboarding. Happy to share if it would be useful.

**Comment by kozbo** [comment]
see https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/wikis/Onboarding/Onboarding
for the checklist. (You should be able to see this link now, or that is item 0!)
