### ISSUE TITLE
Tombstone incorrect analysis bundles

### ISSUE THREAD

**Issue by samanehsan** [HumanCellAtlas/data-store#2314]
I accidentally ran the Optimus pipeline on some Smart-Seq2 bundles in the `HumanColonicMesenchymeIBD` dataset in production, and they successfully created analysis bundles in the data store 🙀 We should tombstone these results bundles because they were not produced with the correct pipeline:

```
"9ef93bd1-5291-4362-86b3-b6aae9db1db1.2019-07-31T211219.344327Z"
"c9bc8332-3480-4ba5-8f73-86c7c2576939.2019-07-31T211643.658583Z"
"4be8d392-1883-4072-9081-9770f272b9d3.2019-07-31T211218.348846Z"
"20f6a297-f30b-4982-ac6f-05eec65316b0.2019-07-31T211123.022873Z"
"a648a9d0-9220-4833-9e21-3d6cdf4ad42f.2019-07-31T211253.458864Z"
"2d0196af-146c-4b77-a471-4b32c3d8e0b5.2019-07-31T211746.684179Z"
"d92eef81-d1a8-40bc-bd8f-e1264f3a9195.2019-07-31T211622.596322Z"
```

**Comment by amarjandu** [comment]
@samanehsan just want to confirm that these were in prod?

**Comment by samanehsan** [comment]
@amarjandu, yes these were in production!

**Comment by amarjandu** [comment]
Complete. :) https://gist.github.com/amarjandu/895c3fe04ab7bcd32d7e77d82b558954
