### ISSUE TITLE
Infra: Ops Ec2/Compute Terraform Scripts

### ISSUE THREAD

**Issue by amarjandu** [HumanCellAtlas/data-store#2315]
as a DSS Operator, i would like to perform long-running tasks on an ec2 instance.
It would be cost-effective to be able to spin up ec2/google compute resources as needed.
These resources should be tracked with resource tagging so we can see the cost (per service) of these operations.

Creating Terraform Scripts that can manage this for us enables quick management of these resources, and provides the team with clean environments to perform these long-running tasks.

**Comment by natanlao** [comment]
I spoke with @amarjandu about this in person, and we concurred that Terraform likely isn't the best way to go about this, for a few reasons:
* Using Terraform would restrict the amount of EC2 instances available to be deployed for this purpose to one without some finagling.
* Having a Terraform resource that is only supposed to be deployed some of the time is weird.
* It's easy enough to use the `aws` CLI, something like:

```
$ aws ec2 run-instances --image-id (ami-to-dss-runbox) --count 1 --instance-type t3.micro ...`
```

As such, I'm adding such a command to the Kharon and DSS runbooks on Allspark and closing this ticket.

**Comment by amarjandu** [comment]
please see https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/wikis/DSS%20Runbook#deletions for information about a long-term ec2 instances.
