### ISSUE TITLE
Spec - First release of query overview doc

### ISSUE THREAD

**Issue by briandoconnor** [HumanCellAtlas/data-store#233]
See Kevin's doc:

https://docs.google.com/spreadsheets/d/1PBMrc0oql4gPpH_cQMqlf7ASNMwePRQZNCutxeSFze8/edit#gid=0

We need to get an initial version of this doc released after feedback from Purple, Red, Blue, and Green teams.  We need to triage and focus on the queries that are absolutely critical for the blue box to support for it's HCA deployment and what's needed for the Sept demo.

**Comment by ttung** [comment]
I think it would be worth understanding how sensitive these queries are to delays -- i.e., can they operate on secondary indices computed with a delay.
