### ISSUE TITLE
API gateway times out too quickly

### ISSUE THREAD

**Issue by ttung** [HumanCellAtlas/data-store#234]
API gateway has a very short timeout.

**Comment by ttung** [comment]
@briandoconnor Did you try the workaround?  Is this a high priority?

**Comment by kozbo** [comment]
Is there a pull request in process to fix this?

**Comment by ttung** [comment]
There's a lot of PRs for this particular issue.  I'm working on the one that ties most of them together.

**Comment by ttung** [comment]
#337, #343, #344, #345, #346, #347 pending.

**Comment by kozbo** [comment]
The above PRs are all merged now. Are there more pending?

**Comment by ttung** [comment]
No, there's still work to be done for google sync.
