### ISSUE TITLE
Define the Public user policy

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#2341]
## User story
* As an unauthenticated user
* I want to access open data from the DSS
* so that I may run analysis with it.

## Definition of done
* Define an access policy for public users. Specifically what endpoints  an unauthenticated users has access.
* Use this policy to authorized unauthenticated user with fusillade.

**Comment by xbrianh** [comment]
Is there a documented decision about anonymous access to HCA data? We could provide open access while requiring authentication.

**Comment by Bento007** [comment]
@xbrianh look at the section on `/user/public` here https://github.com/HumanCellAtlas/fusillade#using-fusillade-as-a-service

**Comment by DailyDreaming** [comment]
This should be done: https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/dcp-fusillade/tree/master/config
