### ISSUE TITLE
Capture core blue box queries in spreadsheet

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#237]
and drive other teams to include their queries.

**Comment by kozbo** [comment]
Blue box queries have been updated from what I know. We do not have the cases from the Purple box yet so while this task is complete for Sprint 4, the ticket should remain open for later integration of PB queries.

**Comment by kislyuk** [comment]
Who is responsible for the task of filling out the actual query syntax for those queries that are implemented?

**Comment by kozbo** [comment]
@mikebaumann can you do that? I don't know the ES syntax for the queries.

Here is the [doc ](https://docs.google.com/spreadsheets/d/1PBMrc0oql4gPpH_cQMqlf7ASNMwePRQZNCutxeSFze8/edit#gid=0)for your reference

**Comment by kozbo** [comment]
Adding Mike to help with filling in query syntax.

**Comment by kozbo** [comment]
I have updated the main use case document. The rest of this work is not a high priority for this sprint.

**Comment by kozbo** [comment]
Collect other use cases to see if there are more queries that are required

**Comment by kozbo** [comment]
I have added in more queries that come from the Purple box use cases. Handing this task off to Mike as I cannot fill in the ES query semantics needed to complete this table

**Comment by mikebaumann** [comment]
Planning to work with Brian on key Q3 demo queries on 9/26/17.

**Comment by kozbo** [comment]
clearing milestone and closing this task. This task is  too large. Instead we will create individual tasks with shorter term goals that can be achieved within a sprint.
