### ISSUE TITLE
Add AuthZ (access control) to the endpoints we want

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#2378]

**Comment by chmreid** [comment]
Closing this issue, for two reasons:
- work is completed - authz has been added to multiple endpoints and those changes are being propagated through integration/staging/prod for the data store
- the ticket doesn't specify what definition of "done" is and doesn't have specific work/issues attached

If this issue should be re-opened, please feel free to do so, but please update the description to specify what needs to be done.

**Comment by kozbo** [comment]
@chmreid Agreed that the issue was not fully defined. Supporting the endpoints we "want" is unspecific and we should not have accepted this task as specified. Let's try to clarify issues like this in the future. In the meantime, I agree that this can probably be closed but it would be good to document the endpoints we "wanted" and those we see as less important. Can you please list those out for posterity? :-)
