### ISSUE TITLE
Bump httpie from 1.0.2 to 1.0.3.

### ISSUE THREAD

**Issue by DailyDreaming** [HumanCellAtlas/data-store#2404]
This was merged: #2397

Found to break tests: https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/data-store/-/jobs/44213

And reverted: #2401

This should be added as soon as the failures are addressed.

**Comment by natanlao** [comment]
I think that these tests were broken by #2324, I'll open a PR.
