### ISSUE TITLE
[SPIKE] presigned url RFC and prototype

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#2418]
Author RFC on signed URL access to data in the DSS:
- DSS will stop supplying could native URLs to most users
- Checkout service will be removed (except for BYOB checkouts)
- BYOB checkout will require authorized access (can apply to the DSS team for access)
- Work with Secondary Analysis to migrate to BYOB checkout

**Comment by chmreid** [comment]
Note: this came up during the 10/23/19 afternoon AUDR session at the HCA Face to Face. The context was when discussing how Analysis will handle inconsequential updates to bundles. Analysis does not want to re-run a workflow if it does not need to. To do that, Analysis will need a fast way to check out/access metadata to calculate a hash.

**Comment by kozbo** [comment]
already have the option for presigned URLs in get file
BYOB checkout works already, but provisioning the bucket is challenging for end users, but we can work with the Mint team to set this up
