### ISSUE TITLE
Remediate High httpie vulnerability

### ISSUE THREAD

**Issue by Lilalamar** [HumanCellAtlas/data-store#2468]
GitHub reports the following **High** severity vulnerability in HumanCellAtlas/data-store. Please remediate by the end of Q4 Milestone 1.

**Description**
httpie

**Suggested Remediation**
Upgrade httpie to version 1.0.3 or later.

**Details**
All versions of the HTTPie package prior to version 1.0.3 are vulnerable to Open Redirect that allows an attacker to write an arbitrary file with supplied filename and content to the current directory, by redirecting a request from HTTP to a crafted URL pointing to a server in his or hers control.

**Comment by DailyDreaming** [comment]
This is done already in the `data-store`: https://github.com/HumanCellAtlas/data-store/blob/master/requirements-dev.txt#L48

**Comment by DailyDreaming** [comment]
@Lilalamar You need to put your real name in your github account.  I have no idea who you are.

**Comment by Lilalamar** [comment]
@DailyDreaming re: Slack, all set.
