### ISSUE TITLE
Instabilities causes CLI tests to fail

### ISSUE THREAD

**Issue by jessebrennan** [HumanCellAtlas/data-store#2489]
The build log is here:
https://api.travis-ci.org/v3/job/593641055/log.txt

This is happening on all branches and master https://travis-ci.org/HumanCellAtlas/dcp-cli/builds/590635889

This is blocking all work on the DCP CLI.

**Comment by amarjandu** [comment]
Restarted Builds in dcp-cli, testing might have occurred during a bad deployment, closing issue for now. 
Master Passes in `allspark`

**Comment by jessebrennan** [comment]
Can we verify that that's actually what was happening? Before we close this, it would be great to have some proof in the logs or something that explains this behavior.

**Comment by jessebrennan** [comment]
I reopened this because I feel that the cause is not certain.

**Comment by jessebrennan** [comment]
This is happening again. Here's the failing re-run on master https://api.travis-ci.org/v3/job/590635892/log.txt

It seems the cause is different this time.

**Comment by amarjandu** [comment]
@jessebrennan yeah the current issue is with the switch to the new authorization service, its effecting other things too, i dont think its related to the original issue.

**Comment by jessebrennan** [comment]
This is happening again. This time on https://github.com/HumanCellAtlas/dcp-cli/pull/460 

https://api.travis-ci.org/v3/job/598267541/log.txt

**Comment by jessebrennan** [comment]
Before you close this, can you link to some sort of fix at least, or give a description of how this is resolved? If no code changed, there's no guarantee that this won't happen again.

**Comment by amarjandu** [comment]
see https://github.com/HumanCellAtlas/data-store/issues/2489#issuecomment-540142181
Issue was propagated from 
https://github.com/HumanCellAtlas/fusillade/commit/58a72d4733bc9c1b6fc5f17180d5a43caedc6f9b
due to dropped auth configurations, which was effecting dss-dev, which was effecting dcp-cli. 

Close this as needed, i'm going to un-assign myself.

**Comment by kozbo** [comment]
@jessebrennan can we close this?

**Comment by jessebrennan** [comment]
Yes I think so. I haven't seen this issue since.
