### ISSUE TITLE
JMESPath queries for v2 subscriptions are undocumented

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-store#2508]
I'm trying to switch to v2 subscriptions and am having difficulties writing even a basic JMESPath query by just looking at the documentation.

Two crucial bits of information seem to be missing from the docs:

1) The structure of the document the query is evaluated against

https://github.com/HumanCellAtlas/data-store/blob/23d38f7ded20f0581ee822cecaeb0a69006093a2/dss/events/__init__.py#L109

2) The expected return value of a query that causes the DSS to consider that query a match for a given document:

https://github.com/HumanCellAtlas/data-store/blob/9b2304f8832f47b651919e9c017730df4bfb0bda/dss/events/handlers/notify_v2.py#L40

This is not as trivial as it may sound. If the query returns an empty string because the a field matches but its value is `""`. `0`, `False`, `[]` or `{}`, the DSS would still consider that a mismatch. All of this needs to be documented.

**Comment by hannes-ucsc** [comment]
Just found this: https://github.com/HumanCellAtlas/data-store/blob/64ee18020238d5eeadd5f8adbe69c7ce25af8ef1/daemons/dss-notify-v2/Readme.md
which is helpful but kinda buried. Most of the information there should be in the Swagger Spec.

**Comment by hannes-ucsc** [comment]
Also, I think the above documentation is inaccurate:

 https://github.com/HumanCellAtlas/data-store/pull/2510

**Comment by xbrianh** [comment]
Thank you for your feedback, we'll work to improve the documentation.

The bundle metadata document can currently be retrieved from the DSS in two ways, which can facilitate JMESPath filter tests. These currently work on the dev and integration deployments:

API
```
hca dss get-event --replica aws --uuid  fad463a3-d4bc-4f78-8417-832025700bc9 --version 2019-10-16T173316.834981Z
or
http "https://dss.dev.data.humancellatlas.org/v1/events/fad463a3-d4bc-4f78-8417-832025700bc9?replica=aws&version=2019-10-16T173316.834981Z"
```

from the `data-store` repo:
```
scripts/dss-ops.py events bundle-metadata-document --replica aws --keys bundles/fad463a3-d4bc-4f78-8417-832025700bc9.2019-10-16T173316.834981Z
```

**Comment by melainalegaspi** [comment]
duplicate of #2563

**Comment by hannes-ucsc** [comment]
@melainalegaspi Please don't close tickets by external collaborators like me in favour of those created internally as that puts the burden of following the ticket chain on the collaborator. It robs the collaborator a chance to express their (dis)satisfaction with the resolution. I sometimes get the impression this team creates the follow-ons with the specific purpose of evading scrutiny by the initial reporter of a ticket which I think is unprofessional.

**Comment by chmreid** [comment]
Closed #2563 and re-opened #2508

**Comment by chmreid** [comment]
#2599 attempted to address this issue, please let us know if [the new v2 readme](https://github.com/HumanCellAtlas/data-store/tree/master/daemons/dss-notify-v2) suits your needs.

**Comment by hannes-ucsc** [comment]
I think it does. Thanks, @chmreid.
