### ISSUE TITLE
v2 subscriptions don't allow filtering by bundle UUID prefix

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-store#2513]
This ~was~ is possible in v1 and we need it for Azul.

The problem is that neither the bundle manifest nor the overarching ["bundle metadata document"](https://github.com/HumanCellAtlas/data-store/blob/23d38f7ded20f0581ee822cecaeb0a69006093a2/dss/events/__init__.py#L109) contain the actual bundle UUID.

**Comment by xbrianh** [comment]
We'll add the bundle UUID to the bundle metadata document.
