### ISSUE TITLE
Endpoint for providing associated graph based on "links.json".

### ISSUE THREAD

**Issue by DailyDreaming** [HumanCellAtlas/data-store#2543]
This ticket is to provide an endpoint to take some of the burden of custom associations made by ingest and stored in mongoDB and have the DSS do most of the heavy lifting.

This means, provided a links.json file with uuids and versions, the DSS would return a metadata graph designed for use by ingest.  This is currently done with their internal mongoDB table, and the aim is to greatly reduce this use internally, or replace it entirely.

**Comment by xbrianh** [comment]
The DSS should not provide this endpoint as part of our API.

Functionality to transform experimental graphs into bundles, and the reverse, should be added to [dcp-lib](https://github.com/HumanCellAtlas/dcplib). New transformation commands should be added to the [cli](https://github.com/HumanCellAtlas/dcp-cli)

**Comment by DailyDreaming** [comment]
Aye, that makes a lot more sense.  Closing this in favor of https://github.com/HumanCellAtlas/dcplib/issues/63.
