### ISSUE TITLE
DSS cleanup in integration

### ISSUE THREAD

**Issue by danielsotirhos** [HumanCellAtlas/data-store#2558]
Please repeat the process to delete all bundles on `integration` save for the ones listed in the attached whitelist as previously done for https://github.com/HumanCellAtlas/data-store/issues/2294

All related parties (Matrix, Data Wranglers, etc) have been notified and signed off on this new whitelist.

[integration-bundles-whitelist.txt](https://github.com/HumanCellAtlas/data-store/files/3790612/integration-bundles-whitelist.txt)

**Comment by danielsotirhos** [comment]
Blocking https://github.com/DataBiosphere/azul/issues/1315

**Comment by theathorn** [comment]
@kozbo @melainalegaspi Please schedule this for Q4, if possible.

**Comment by amarjandu** [comment]
Secondary Analysis requested new bundles to be added to this list : 
```
b1d7cbc3-179d-44e1-8c6f-cbdb44f94ac9.2019-11-20T220640.158388Z
4b735dfa-7a2d-4d08-930c-8dbce0810dba.2019-11-20T220107.998749Z
```

Added to the txt
[integration-bundles-whitelist.txt](https://github.com/HumanCellAtlas/data-store/files/3871763/integration-bundles-whitelist.txt)

**Comment by amarjandu** [comment]
Collisions Detected for the following project with redacted GDPR data:
```
project abe1a013-af7a-45ed-8c26-f3793c24a1f4:
bundles/a0a78a4e-7891-4ef2-a22d-1bfab43ffe47.2019-08-14T102354.928677Z
bundles/ea25386a-dc17-453d-9312-b61995f2c3f6.2019-08-21T110750.639681Z
bundles/7b4fd692-c38d-43c6-bb5b-bf3dcbc837eb.2019-08-14T102354.916002Z
bundles/5c4bb0a6-705e-43a1-9714-fc7a60334bed.2019-08-22T005001.029171Z
bundles/3b17e3c9-5f1c-49c6-b4fc-e3d658e7b731.2019-08-22T011147.980970Z
bundles/8cd7c4db-675b-4412-bb60-df0340245828.2019-08-14T102354.893522Z
bundles/c99ea041-0daf-4b25-bee9-d9691af11a5e.2019-08-14T102354.895912Z
bundles/6ff1a6f0-f214-45bc-878a-f8919cb3e581.2019-08-22T060017.593244Z
```
Please do not attempt to migrate any of the bundles listed in
 https://github.com/HumanCellAtlas/data-store/issues/2528

I can give you time if you want to change the whitelist for this project.

**Comment by amarjandu** [comment]
Browser Group requests that projects remain consistent between stages, this shall be complete when physical deletion occurs through to `prod`

**Comment by danielsotirhos** [comment]
Updated bundle whitelist with redacted CDPR collisions removed: 
[integration-bundles-whitelist-collisions-removed.txt](https://github.com/HumanCellAtlas/data-store/files/3881222/integration-bundles-whitelist-collisions-removed.txt)

**Comment by amarjandu** [comment]
Deletion is complete in `integration`, re-indexing was done in the `aws` replica
