### ISSUE TITLE
`GET /bundles/all` crashes for certain prefixes

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-store#2562]
```
$ http 'https://dss.integration.data.humancellatlas.org/v1/bundles/all?prefix=05&replica=aws&per_page=500'
HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Headers: Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 387
Content-Type: application/problem+json
Date: Tue, 05 Nov 2019 20:10:23 GMT
Retry-After: 10
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-AWS-REQUEST-ID: 69eaf842-afb7-49b7-85c6-84ca927b572b
X-Amzn-Trace-Id: Root=1-5dc1d72e-8480da3fbb79e70e8cc979ec;Sampled=0
x-amz-apigw-id: Cs6PUHnboAMF03Q=
x-amzn-RequestId: 19908db7-550c-44ba-aacf-03e6f6079372

{
    "detail": "None is not of type 'string'\n\nFailed validating 'type' in schema['properties']['token']:\n    {'description': 'Internal reference for enumeration, should not be '\n                    'changed by user.',\n     'type': 'string'}\n\nOn instance['token']:\n    None",
    "status": 500,
    "title": "Response body does not conform to specification",
    "type": "about:blank"
}
```

**Comment by hannes-ucsc** [comment]
The urgency of this depends on whether this is limited to `integration` (which would lower the urgency) or whether it could also happen in other deployments (which would mean we need a fix ASAP in all deployments). Could you please spike this to determine that?

**Comment by hannes-ucsc** [comment]
Prefix `0e` is also affected.

**Comment by kozbo** [comment]
Lon: can you triage this?

**Comment by DailyDreaming** [comment]
@kozbo Yes, will address this today.

**Comment by DailyDreaming** [comment]
@hannes-ucsc Why are you using `http` instead of the CLI?

**Comment by DailyDreaming** [comment]
This appears to only be a problem in integration.  Cherry-picking fixes in from `dev` now.

**Comment by hannes-ucsc** [comment]
I'd like to see a reference to the commit that fixes this issue.

**Comment by xbrianh** [comment]
@hannes-ucsc It may be good practice to link the bug fix commit to this issue. If that is the reason for your request, please communicate it (this helps the team improve). Otherwise, please provide contextual information.

**Comment by hannes-ucsc** [comment]
I'm sure the team knows what I mean. Thanks.

**Comment by DailyDreaming** [comment]
This is fixed now for `integration`.  Closing this issue.

**Comment by hannes-ucsc** [comment]
Can I please have a reference to the commit that resolves this issue or a description what the problem was and how it was resolved? 

@kozbo, @theathorn

**Comment by xbrianh** [comment]
Typically we should indicate the solution when closing an issue, and I'm sure we'll do that in the future. Unless there's information indicating that this issue has not been resolved, it's not clear that it should be reopened. Your concerns have been communicated to the managers in either case.

**Comment by hannes-ucsc** [comment]
Can I please have a reference to the commit that resolves this issue or a description what the problem was and how it was resolved?

**Comment by hannes-ucsc** [comment]
What's the harm in providing that information? If not by reopening the ticket how else should we track that insufficient evidence for the resolution was given?

**Comment by xbrianh** [comment]
There is no harm. We'd like to provide it.

@DailyDreaming indicated that the issue has been resolved. Unless you believe otherwise I think the issue should be closed.

**Comment by DailyDreaming** [comment]
@hannes-ucsc Here is the commit that fixed the issue: https://github.com/HumanCellAtlas/data-store/commit/4062e38d5892b93aa8320427b96a56b946c866a1

This was taken from fixes currently merged into `master`: https://github.com/HumanCellAtlas/data-store/pull/2494

**Comment by hannes-ucsc** [comment]
@DailyDreaming, this was discussed in tech arch today. @briandoconnor would like us follow the general best practice of providing evidence for resolution of issues when closing them.

**Comment by hannes-ucsc** [comment]
Thank you, @DailyDreaming.
