### ISSUE TITLE
Improve JMESpath documentation.

### ISSUE THREAD

**Issue by DailyDreaming** [HumanCellAtlas/data-store#2563]
Based on comments from @hannes-ucsc 

 - [x] Document what the manifest looks like. Just saying `{bundle_manifest}` is insufficient.
 - [x] `{file_name_1}` is extremely confusing (Hannes). It doesn't mention that the file undergoes this transformation: https://github.com/HumanCellAtlas/data-store/blob/23d38f7ded20f0581ee822cecaeb0a69006093a2/dss/events/__init__.py#L115
 - [ ] Ensure that the bundle metadata document provided in the example has all required fields.
 - [x] Don't use `{}` for interpolation in JSON (Hannes). This is a nit, I'm not certain of the value this adds.

**Comment by chmreid** [comment]
See #2508 instead
