### ISSUE TITLE
Tombstone Tissue sensitivity project

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/data-store#2567]
Please tombstone all bundles associated with the Tissue sensitivity project at:
https://data.humancellatlas.org/explore/projects/c4077b3c-5c98-4d26-a614-246d12c2e5d7

This is so that we can re-use the uuid for the new submission at: https://ui.ingest.data.humancellatlas.org/submissions/detail/5dc4081771fe4a0008e54859/overview

@HumanCellAtlas/data-ops should there be some process where the project page gets replaced with placeholder page in between when the data disappears and the new data reappears? similar to what was done with the Ben Stewart dataset so that no one goes to the old project page and gets a 404.

pinging @MightyAx

**Comment by amarjandu** [comment]
@mshadbolt what stages do you need this for? just prod?

**Comment by amarjandu** [comment]
Does this look correct? i found 14 bundles:
```
['ffa9e38f-2b2a-48ff-98d2-8c36b3f4b323.2019-07-28T064426.601282Z',
'fcadd52b-9824-4271-a478-2b29e3e46c47.2019-05-15T202438.811000Z',
'e44ab8ad-5e87-42c3-89f8-0fc18aa098d3.2019-07-28T072824.210781Z',
'bb264d3f-b01f-46b4-98e1-6c37a122c376.2019-05-15T202438.811000Z',
'b1786e9c-ee59-483d-b711-8c5e55788629.2019-05-15T202438.811000Z',
'ae7ba6e6-fc25-447f-82a4-17cbb47e0868.2019-05-15T202438.811000Z',
'7478cf95-b4c1-4376-858f-78a34f20ee58.2019-07-28T065613.587310Z',
'5de5633f-1d79-449d-8c0f-65425c695996.2019-05-15T202438.811000Z',
'55b26bf9-ba05-49df-b34e-7d03aa82afcd.2019-07-28T073701.283224Z',
'3d20777c-4471-4873-8485-8c94f35f175b.2019-07-28T061638.503761Z',
'37acb7ea-ac3d-4caa-b204-100f0fe727d0.2019-05-15T202438.811000Z',
'37118220-e727-4358-ab4e-558c7b32a007.2019-07-30T222658.026120Z',
'20fe3336-1dcc-4ee6-851a-3a6748015afb.2019-05-15T202438.811000Z',
'0a4fa584-febd-487a-877c-c89eeeba6e3e.2019-07-28T063413.508141Z']
```

**Comment by amarjandu** [comment]
https://gist.github.com/amarjandu/5ed8936442fbe7ef3e67fe4a39d059fb

**Comment by jlzamanian** [comment]
The tombstoning is only in prod.

The bundles match our list, but please hold off from running the tombstoning script until the remaining issue in https://github.com/HumanCellAtlas/ingest-central/issues/595 is resolved.

**Comment by jlzamanian** [comment]
Re-ingestion is ready to go. Please proceed with tombstone script approval.

**Comment by amarjandu** [comment]
tombstone complete.

**Comment by mshadbolt** [comment]
I'm confused, I thought we were waiting until the other issue was solved? 

Also @HumanCellAtlas/data-ops I don't think it is great that if you go to the project page it is blank at the moment. Can we have a better process for this in the future?
