### ISSUE TITLE
DSS Infra: Check TF Version on Make Commands

### ISSUE THREAD

**Issue by amarjandu** [HumanCellAtlas/data-store#2636]
We should ensure that at deployment the correct version of TF is being used to avoid accidentally updating statefiles, this can be done in the `common.mk` file.

**Comment by chmreid** [comment]
It looks like this was closed by accident. If not, please link in the PR/change that closed this issue.

**Comment by amarjandu** [comment]
https://github.com/HumanCellAtlas/data-store/pull/2672
