### ISSUE TITLE
Replace generic test placeholders (email@email.com) with test-specific names

### ISSUE THREAD

**Issue by chmreid** [HumanCellAtlas/data-store#2665]
There are still some generic placeholders in our tests (e.g., example.com or email@email.com) that would be difficult to trace if we saw them appear in the real system. This ticket is to remove these generic placeholders and replace them with something that indicates they are from DSS tests (and which test in the test suite).

Specifically:
- `test_subscriptions.py` creates subscriptions using the email `email@email.com`
- `test_utils.py` uses `email@email.com` to test DSS security utilities
- `test_indexer.py` uses example.com as a notification endpoint
- `test_notify_v2.py` uses example.com as a notification callback url
- `test_prod_smoketest.py` uses example.com as a subscription endpoint
- `test_subscriptions.py` uses example.com as a subscription endpoint

**Comment by natanlao** [comment]
Plus, a lot of these email addresses (`ack '\S+@\S+' tests/`) use addresses at domains that exist (e.g. `email.com`, `claim.com`, `test.com`). It would be better practice to use addresses `@example.com` that have no chance of ever being a valid address.

**Comment by chmreid** [comment]
To clarify: we would replace generic placeholder emails/domains like `example@email.com` with test-specific emails/domains that make it easier to track down which tests are responsible, like `test-v2-notifier@data.humancellatlas.org`
