### ISSUE TITLE
Documentation is wrong for HEAD /files endpoint

### ISSUE THREAD

**Issue by jessebrennan** [HumanCellAtlas/data-store#2679]
The documentation:

> hca dss get-file --uuid UUID --replica aws &gt; result.txt

is clearly wrong since it's talking about `get-file`.

**Comment by amarjandu** [comment]
can you provide a link to the documentation?

**Comment by jessebrennan** [comment]
Sorry, yes. https://dss.data.humancellatlas.org/

**Comment by chmreid** [comment]
Hi @jessebrennan, can you clarify a bit more? What do you mean by "wrong"? What are you expecting to happen, and what actually happens? Also, it's not clear how the CLI tool is related to the swagger API you linked to, can you be more specific?

**Comment by chmreid** [comment]
Got some clarification on what this issue is about from @amarjandu, there is a docstring that is in the HEAD /file endpoint of the swagger page but should have been in the GET /file endpoint. Should be fixed by #2682.
