### ISSUE TITLE
Airbrake: Received CloudWatch event for a task with no known handler

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#2686]
301K occurrences
/aws/lambda/dss-events-scribe-integration Received CloudWatch event for a task with no known handler: DomovoiException Traceback (most recent call last): File "/var/task/domovoi/app.py", 
line 186, in __call__ raise DomovoiException("Received CloudWatch event for a task with no known handler") 
domovoi.app.DomovoiException: Received CloudWatch event for a task with no known handler '@log_stream': 
2019/12/07/[$LATEST]d72b3b53a32644939a6daccbee03631f

see https://humancellatlas.airbrake.io/projects/179579/groups/2231748620012991770?dur=90d%2F1d&last_n=30&filters=%7B%22order%22%3A%22notice_count%22%2C%22resolved%22%3A%22false%22%7D&tab=overview

**Comment by xbrianh** [comment]
This was caused by incomplete cleanup after refactoring `daemons/dss-events-scribe`. The cloudwatch rule `flashflood_journal_and_update` has been deleted, and this issue should be resolved.
