### ISSUE TITLE
Tombstone 3 Integration Tests in prod

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-store#2718]
Tombstone all the bundles associated with the following project_uuids:
c11034ed-52ae-4d8b-b58f-5e63c517fdb6
a81bae1a-555d-4a5d-bf7f-da0d9206abcb
cffac622-739d-4ad0-8b73-355e8d67c060

**Comment by amarjandu** [comment]
bundles found
```
['8eec8a2f-f91b-44e4-8a88-99d452d2391f.2020-03-09T143139.918348Z',
'248310e5-b228-4f00-a06a-c8a1ae44284a.2020-03-09T143736.362668Z',
'12883c30-acda-4481-81d4-41924700f38f.2020-03-08T142254.750891Z',
'e0fc70d2-5215-4a1f-8419-448b9a0740d3.2020-03-11T125651.148235Z']
```

**Comment by amarjandu** [comment]
see https://gist.github.com/amarjandu/68cc966f83f1e9ec7a31e8365c1c77ce

**Comment by amarjandu** [comment]
tombstone complete
