### ISSUE TITLE
Update Tech Team Task Tracking Worksheet

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#281]
Bring spreadsheet up to date after the June sprint
https://docs.google.com/spreadsheets/d/1JPd-4ZzZlClm4TbDJumUooxINt5ZP7C2xmh0EE9FD_s/edit#gid=0

**Comment by Mackey22** [comment]
Hey Kevin, 

Wanna add a column for "Prototype: Slack Bot to query and register for notifications”? 

Thanks, 
James

**Comment by kozbo** [comment]
Done, thanks. 
Do you have a github issue for this task?

**Comment by Mackey22** [comment]
Yeah, they’re located here: https://github.com/HumanCellAtlas/data-store-slack-bot/issues <https://github.com/HumanCellAtlas/data-store-slack-bot/issues>

James
