### ISSUE TITLE
Native indexing support for Google

### ISSUE THREAD

**Issue by mikebaumann** [HumanCellAtlas/data-store#340]
Add indexing support for the Google replica.

Receive/handle Google Pub/Sub events.
Assume indexer will run in AWS Lambda (for now, and maybe longer term)

Tasks:
Change indexer to use blobstore abstractions and add GS indexer tests (1-2 days)
Decide where Google index will be located (for now, and maybe longer term):
    . AWS (in same instance with a different set of indexes, or different ES instance)
    . GS (ES service) 
Change to store the index data according to the replica: (1 day)
    . If same AWS ES instance, parameterize index names
    . If different AWS ES instance, parameterize ES instance (using a different, GS ES env var)
Deployment testing (manual, <= 1 day)

**Comment by Bento007** [comment]
GS index data will be in the same elasticsearch domain/instance as AWS. It will be placed in index "hca_{replica_name}", for example "hca_gcp"

**Comment by ttung** [comment]
> GS index data will be in the same elasticsearch domain/instance as AWS. It will be placed in index "hca_{replica_name}", for example "hca_gcp"

Why?  Is there any advantage in putting them in the same instance?  I would just federate it.

**Comment by kislyuk** [comment]
I would prefer to have one ES instance with one index per replica. That reduces the overhead of managing instances.

This will change when we decide to deploy the DSS API natively on Google Cloud Functions. Then it will make sense to run an ES cluster (instance) on GCP.

**Comment by ttung** [comment]
Also, an accident would blow fewer things up. :)

**Comment by kozbo** [comment]
I believe that this is done. Is this a dupe? Please update this issue with issue # that actually closed out this work.

**Comment by Bento007** [comment]
Fixed in #380
