### ISSUE TITLE
Simplified search

### ISSUE THREAD

**Issue by mikebaumann** [HumanCellAtlas/data-store#341]
- Define initial simple search language (examples, grammar) (1-2 days)
- Implement translator from simple search language to ES query language (3 days)
- Update search route to support simple search in addition to full ES language (1 day)
- Deployment testing (manual, < 1 day)
- Consult with ES experts, when available (TBD 1-2 days?)

**Comment by kozbo** [comment]
From Andrey: Update regarding the simplified query language. I’m considering adopting JMESPath (http://jmespath.org/specification.html) as a supported metadata query language. Its upsides are that it has sufficient features to formulate queries (as opposed to just pointers into documents), mostly agreeable (intuitive?) syntax, a concise, stable specification, and robust production implementations in many languages, supported/maintained by AWS (http://jmespath.org/libraries.html). Please take a look and tell me what you think.
@mikebaumann @Bento007 @ttung @briandoconnor

**Comment by Bento007** [comment]
It sounds like a great idea. We will need to make it clear what features of jmespath we will and will not support in our documentation to avoid confusing the users. Also Depending on which feature from jmespath we plan to support, implementing the translator maybe a significant amount of work.

**Comment by Bento007** [comment]
connect to #46

**Comment by kozbo** [comment]
Discussion with UCSC staff on 4/18/18, notes to follow.

**Comment by kozbo** [comment]
@kislyuk @mweiden please add notes

**Comment by kislyuk** [comment]
Possibly useful resource for GraphQL: https://gist.github.com/swalkinshaw/3a33e2d292b60e68fcebe12b62bbb3e2

**Comment by mweiden** [comment]
With the addition of the Query Module, this is not out of scope of the DSS. Closing this.
