### ISSUE TITLE
Enable parameterized ES index names for test-specific indices

### ISSUE THREAD

**Issue by mikebaumann** [HumanCellAtlas/data-store#355]
Description from Andrey:
... I want us to commit to refactoring the codebase to make it easy to parameterize the index names on the fly, so that each test ends up initializing and using a unique index instead of launching multiple heavyweight instances of ES (which might have other exciting interactions among themselves!)

This will enable faster, reliable execution of ES-related tests.

**Comment by Bento007** [comment]
By appending the name of the test module with the index we can created test specific indexes.  This is currently in progress but is dependent on several PRs ahead of it.

**Comment by kozbo** [comment]
From Tony: you may need to change the timeout

**Comment by Bento007** [comment]
This issue has been fixed in the associated PRs. Once those are accepted this issues will be closed.
