### ISSUE TITLE
Full pagination support for search

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#376]
In order to handle large search results, pagination is necessary to retrieve all results. The DSS search API pagination will use the [GitHub API ](https://developer.github.com/v3/guides/traversing-with-pagination/) pagination pattern recommended by @kislyuk. The HCA search CLI will need to updated to support paginated search.

**Pagination shall support:**
- first - refers the first page
- last - refers to the last page
- next - refers to next page after the current page.
- prev - refers to the previous page before current page. 
- page# -  for jump to a page
- results per page - modify the number of results per page

**Useful resources:**
https://github.com/elastic/elasticsearch-dsl-py/issues/126 - issue regarding pagination using elasticsearch-dsl
https://github.com/elastic/elasticsearch-dsl-py/issues/429 - issues regarding pagination

**Notes on elasticsearch pagination:**
- scroll
-- Expensive operations
-- Allows slicing
-- Easy to move back and forth between search results
-- Requires a persistent session to track scroll_id for navigating results.
-- We could return the search_id so users can use the search based off their previous search.

Depreciated in Elastic Search 2.x, use scroll instead.
~~- Scan
-- Iterates through all results.
-- One direction
-- Can’t go back
-- Generates a generator
-- Requires multiple calls to the server for each call to scan.
-- Returns a search_id~~

**Comment by Bento007** [comment]
@kozbo What is the maximum number of queries we should allow to be returned in a single request?
@tburdett Data-store CLI will need to handle the search_ids for requesting additional search results when a query results in more results than can be returned in a single request.

**Comment by kozbo** [comment]
@Bento007 Pagination for buffering is a different problem than pagination for UI display in my mind. The number of entrants returned in a buffer is dependent on how large an entry is. The limit on the buffer size is usually the amount of memory one can reasonably assume that the client can allocate. I would think that a buffer size up to 32MB is not unreasonable. Is it possible to make it user configurable up to a max size? @kislyuk and @mikebaumann are handling the architecture so I defer to them.

**Comment by Bento007** [comment]
> Pagination for buffering is a different problem than pagination for UI display in my mind.
We will need to determine the solution for both problems and possibly break this Issues into two separate issues. My concern is that large queries will break the client or the server if limits are not imposed.
> Is it possible to make it user configurable up to a max size?
It is possible to make it user configurable. It can be a parameter from the user in their query.

**Comment by kislyuk** [comment]
@kozbo, actually, pagination in this context is intended primarily to reduce the amount of data per response, and the latency of the response, not the memory that the client can allocate.

Whether or not the client uses the same pagination scheme for displaying results as it does for querying the API is an implementation detail of the client, but we should try to make it flexible enough to have a reasonable chance of a 1:1 mapping between the API and the UI.

To that end I would agree that letting the client specify the page size between 10 and 500 seems reasonable.

@Bento007 did you mean to at-mention someone else? I don't think @tburdett is involved in this design discussion. As to your point, the reason I suggested the GitHub API is that it standardizes pagination and abstracts away the specific parameters to supply to the API. The client should not need to know which parameters to supply for pagination; that is an implementation detail of the server. The server should provide URLs embedding all necessary parameters in the query string, using the `Link: <https://api.example.com/route?params>; rel="next",
  <https://api.example.com/route?params>; rel="last"` header. (Unfortunately this scheme is not covered in standards literature other than http://www.rfc-editor.org/rfc/rfc5988.txt, but it's being increasingly adopted as a best practice.)

**Comment by Bento007** [comment]
> @Bento007 did you mean to at-mention someone else? I don't think @tburdett is involved in this design discussion.

wrong Tony.

**Comment by Bento007** [comment]
Sounds like we need to add some additional Parameters to our search implementation.
