### ISSUE TITLE
Compete Data Index & Event Notification Update 2017 Q3

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#385]
see (updated link)  https://docs.google.com/document/d/14DM2ef63_qIv8EwrDnh-sw89nKsqi397-EG1yhnsFLY/edit#heading=h.290zqebo1w11

**Comment by mikebaumann** [comment]
To be available for review on 9/28/17.

**Comment by kislyuk** [comment]
This appears to be complete, moving to done.

**Comment by Bento007** [comment]
I beleive this the document mentioned https://docs.google.com/document/d/1t8Q3gWHZRJzKApLip7esjy6K44ZeCdIH5j-4wE4O7K4/edit?ts=59e10d01#heading=h.ibz0osa14k96
