### ISSUE TITLE
Ask Jim about new metadata files in data bundle example repo

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#400]
Bundles will be updated. Spec coming soon from Clay, with bundles to follow. I will leave this open to remind me to bug Clay until we get the spec and bundles.

**Comment by briandoconnor** [comment]
I'll check in with Clay on this for 1) to make sure they do a release and 2) make sure the schemas are released as well.

**Comment by kozbo** [comment]
Another v3 release is in the Develop branch here: https://github.com/HumanCellAtlas/data-bundle-examples
But I don't see a schema release yet.
