### ISSUE TITLE
Load sample data bundles

### ISSUE THREAD

**Issue by kislyuk** [HumanCellAtlas/data-store#43]
Integration test to load bundles from https://github.com/HumanCellAtlas/data-bundle-examples and exercise the entire producer & consumer API using them

**Comment by briandoconnor** [comment]
Hey, just FYI we're expecting the sample data bundles to be on a feature branch by Jim by next Tues 6/13 and hoping to get Laura's feedback and tag as a release on 6/16.

https://github.com/HumanCellAtlas/data-bundle-examples

**Comment by sampierson** [comment]
Done, to a certain approximation.
Most of the 19,000 bundles were loaded into the dev data-store.
There were some errors, but these are now covered in separate issues, e.g. #399
