### ISSUE TITLE
Subscribe returns current query results after registering

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#450]
Currently after a subscription is registered the subscriber has to wait for a new creation event before getting their results.

Suggestion: After a subscriptions is registered the results of that query should be returned to the subscriber. 

Current work around: the subscriber runs a search using their query and collects the results. Then they subscribe their query, and will receive the results after a creation event if their query matches.

**Comment by ttung** [comment]
This should be a front-end abstraction.

**Comment by Bento007** [comment]
connect to #540
