### ISSUE TITLE
Use fault tolerance strategy for S3 and ES internal errors

### ISSUE THREAD

**Issue by kislyuk** [HumanCellAtlas/data-store#456]
The attached error log was recorded by Travis during the following S3 outage:

> 11:58 AM PDT We are investigating increased error rates for Amazon S3 requests in the US-EAST-1 Region.
> 12:21 PM PDT We can confirm that some customers are receiving throttling errors accessing S3. We are currently investigating the root cause.
> 12:38 PM PDT We continue to work towards resolving the increased throttling errors for Amazon S3 requests in the US-EAST-1 Region. We have identified the subsystem responsible for the errors, identified root cause and are now working to resolve the issue.
> 12:49 PM PDT We are now seeing recovery in the throttle error rates accessing Amazon S3. We have identified the root cause and have taken actions to prevent recurrence.
> 1:05 PM PDT Between 11:40 AM and 12:56 PM PDT we experienced throttling errors accessing Amazon S3 in the US-EAST-1 Region. This issue is resolved and the service is operating normally.

[travis-ci-275603450.log.txt](https://github.com/HumanCellAtlas/data-store/files/1304576/travis-ci-275603450.log.txt)

This issue is about introducing retry logic with exponential back-off where appropriate, deferring to a higher level fault tolerance strategy where appropriate, and, where possible, instrumenting our tests with mock services that inject errors.

**Comment by ttung** [comment]
http://docs.aws.amazon.com/general/latest/gr/api-retries.html

it's claimed here that there's already exponential backoff.

It looks like we could twiddle the number of retries but it's quite likely that if we increased the # of retries, we would exceed API gateway's timeout.

I'd say we leave this alone and have the client deal with it.

**Comment by kislyuk** [comment]
Hm, I think you're right. The tracebacks say "reached max retries: 4". I assume boto3 is smart enough to configure urllib3 with exponential backoff for those retries. In that case there's nothing to do other than DLQ-based fault tolerance in the daemons.
