### ISSUE TITLE
Manifest response should include file size

### ISSUE THREAD

**Issue by caaespin** [HumanCellAtlas/data-store#471]
I think the current manifest response should include the file sizes of the files in the bundle. This would be really helpful when calling the system and creating an index for various purposes.

**Comment by ttung** [comment]
That sounds fine to me. Send me a PR and I can approve.

**Comment by xbrianh** [comment]
Including size in manifests requires population of a size metadata fields in dcp-cli and staging-service.

**Comment by kislyuk** [comment]
Update from sprint review: need to decide which code path is responsible for injecting size into the file metadata in the blue box. Consider possible solutions with @ttung
