### ISSUE TITLE
GET /bundles/<bundle_uuid> often results in HTTP Error 504: Gateway Timeout

### ISSUE THREAD

**Issue by caaespin** [HumanCellAtlas/data-store#485]
Getting a Timeout error when calling GET `<staging_url>/v1/bundles/<bundle_uuid>`: 

`HTTP Error 504: Gateway Timeout`

20 calls were threaded for the blue box, and many timed out. Will include a test script shortly.

**Comment by Bento007** [comment]
any update on this?

**Comment by ttung** [comment]
THERE, UPDATES. :)
