### ISSUE TITLE
Build 4 more queries for uses cases

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#521]
work with Clay, Chris, and Jonathan to build queries/indexes for 4 more query use cases from the use case details spreadsheet.

**Comment by briandoconnor** [comment]
Connects to #577

**Comment by briandoconnor** [comment]
See https://docs.google.com/document/d/1WVd5R_sWzLlxP7lev90WXCxG58TyBxrixkwrD1vs_Io/edit# for the current 7

**Comment by briandoconnor** [comment]
See spreadsheet: https://docs.google.com/spreadsheets/d/1PBMrc0oql4gPpH_cQMqlf7ASNMwePRQZNCutxeSFze8/edit#gid=0
