### ISSUE TITLE
Minimal Viable Implementation List

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#529]
**Minimal viable implementation** of data store ready for testing: In addition to core functionality, this includes auth integration, administrative delete, and release tooling.

1. “Must haves” from use case list
2. Make a formal list of what is the “MVP” -KO, SS
3. What does Query look like
4. API demands

This will result in additional issues being created for Q4. We should complete this ASAP

**Comment by Bento007** [comment]
Here is the doc [Data Store MVP and Roadmap](https://docs.google.com/document/d/1RQkPJ4FdDt5bohGwpVo4HvKmOTFVpAJsRbnQ4-e1o6U/edit?usp=sharing)

**Comment by kozbo** [comment]
Since the MVP document captures the entire quarter then the doc will suffice to complete this epic. We have other Epics/stories that capture the work
