### ISSUE TITLE
Identify requirements for index data change management

### ISSUE THREAD

**Issue by mikebaumann** [HumanCellAtlas/data-store#530]

**Comment by kislyuk** [comment]
Update from sprint review on Oct 16:
- Research use of "one index per metadata schema" rule
- Research strategies for handling data outside the schema, such as excluding it from the index altogether
- Consider using other databases
@mikebaumann can you please provide an update and link to working docs?

**Comment by Bento007** [comment]
https://docs.google.com/document/d/1qjb6mm4wyl1dveuRqC8ZQYaMYSwfF66BbFr9Z4OjCAI/edit#heading=h.mqisjbbjxey3
