### ISSUE TITLE
Create operational goal list

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#535]
@kislyuk and @kozbo Please elaborate

**Comment by kozbo** [comment]
We should have added more detail when we created this ticket! My guess is that this relates to the SLOs and/or the go-live requirements for the Data Store. I am not sure what else this could be. We have both of those covered in other tickets, so unless there are objections I say we close this issue.

**Comment by kislyuk** [comment]
Yes, let's circle back to the burndown chart and go-live requirements, and re-draft specific issues from those lists.
