### ISSUE TITLE
A fast, “smoke test” suite that runs on staging environments of all services

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#543]
This smoke test uses green, blue, and purple boxes to simulate the HCA in operation. There should be similar stories to this for all boxes.
1. Triggered by changes in any of the repos 
2. Also runs on a schedule - nightly (goal)

### Connections
Connects to #495 
Connects to #467

**Comment by Bento007** [comment]
This may be a duplicate of #544

**Comment by sampierson** [comment]
Closing as dup of #544
