### ISSUE TITLE
Enable cross-team CI: first DCP integration test

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#544]
Please elaborate.

**Comment by kislyuk** [comment]
See https://docs.google.com/document/d/18sVBW4m_G_HPbi-42CxP-6aGtnhdmIFkTNGbF0mg4XA

**Comment by sampierson** [comment]
Blocked pending:
* staging deployment of secondary analysis service
* HCA CLI that can download from the staging DSS deployment

**Comment by kislyuk** [comment]
Update from sprint review: Waiting on these two blockers to resolve. Mint team and @kislyuk to resolve.

**Comment by sampierson** [comment]
This smoke test uses green, blue, and purple boxes to simulate the HCA in operation. There should be similar stories to this for all boxes.

Triggered by changes in any of the repos
Also runs on a schedule - nightly (goal)

**Comment by sampierson** [comment]
In progress.

**Comment by kozbo** [comment]
This is done, thanks!
