### ISSUE TITLE
Transformed query language

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#546]
Allow users the ability to store snippets of code. That code can take parameters, and outputs an ES query (or a query in a different language).

**Comment by Bento007** [comment]
Should this be moved to Data-store-cli?

**Comment by ttung** [comment]
No, this would be core blue box functionality if we build it.

**Comment by Bento007** [comment]
What behavior would qualify this story as being done?

**Comment by kozbo** [comment]
closing, obsolete
