### ISSUE TITLE
Unexpected S3 events from wrong bucket cause error in domovoi

### ISSUE THREAD

**Issue by mikebaumann** [HumanCellAtlas/data-store#549]
Many occurrences of the following error are seen in the CloudWatch logs for the dss-dev-indexer Lambda in the dev deployment https://dss.dev.data.humancellatlas.org:

> 19:45:58
Domovoi dispatch of event {'Records': [{'EventSource': 'aws:sns', 'EventVersion': '1.0', 'EventSubscriptionArn': 'arn:aws:sns:us-east-1:861229788715:domovoi-s3-bucket-events-org-humancellatlas-dss-test:8d31dcd6-abfc-4be2-9107-15932f1e8734', 'Sns': {'Type': 'Notification', 'MessageId': '4cfce122-0377-57ad-9a51-b37526c17c08', 'TopicArn': 'arn:aws:sns:us-east-1:861229788715:domovoi-s3-bucket-events-o
Domovoi dispatch of event {'Records': [{'EventSource': 'aws:sns', 'EventVersion': '1.0', 'EventSubscriptionArn': 'arn:aws:sns:us-east-1:861229788715:domovoi-s3-bucket-events-org-humancellatlas-dss-test:8d31dcd6-abfc-4be2-9107-15932f1e8734', 'Sns': {'Type': 'Notification', 'MessageId': '4cfce122-0377-57ad-9a51-b37526c17c08', 'TopicArn': 'arn:aws:sns:us-east-1:861229788715:domovoi-s3-bucket-events-org-humancellatlas-dss-test', 'Subject': 'Amazon S3 Notification', 'Message': '{"Records":[{"eventVersion":"2.0","eventSource":"aws:s3","awsRegion":"us-east-1","eventTime":"2017-10-10T19:45:58.174Z","eventName":"ObjectCreated:Put","userIdentity":{"principalId":"AWS:AIDAICWUAENV524KQFJ24"},"requestParameters":{"sourceIPAddress":"10.12.6.109"},"responseElements":{"x-amz-request-id":"0C465FCD99D98221","x-amz-id-2":"e5edQP8oiKuaj3b6h21AylHJYLlIAfzq/lNpDKeqdxlDCEBFN/psYuDDiPHwAWBG9PVuMBiyya8="},"s3":{"s3SchemaVersion":"1.0","configurationId":"NTJiMWFiMTMtMTY1Yy00YTJmLTlkNmMtZTdmYjEzZmUxM2Q2","bucket":{"name":"org-humancellatlas-dss-test","ownerIdentity":{"principalId":"A29PZ5XRQWJUUM"},"arn":"arn:aws:s3:::org-humancellatlas-dss-test"},"object":{"key":"files/3923986f-7343-4638-828c-723a4a59d28e.2017-10-10T194557.961752Z","size":367,"eTag":"dd239588f2dff17a9afe53eda6a8ccaa","sequencer":"0059DD23761CB576D6"}}}]}', 'Timestamp': '2017-10-10T19:45:58.232Z', 'SignatureVersion': '1', 'Signature': 'EAzMTGHUw4+FYYYpeDBERAhhpndjzvusTAJDAOHy56VZv+MyAFvro/alUA4A+/+gWQocblFI0L/mqgeu+K/IBJ2B0hfwqIoNNWjscIkW1qxIYz+WjerVAjH67DMA7f/WErp/rj/5D7bx96ZbCllyE/P94kszxDBkq3OTV7ofjqPg8CbNU8RUIcI3oql6vTk4ZK7p4117PaYcAHRbUPjHngpEeytiZ7pGM7759ooQ6OAcyKDSizcdUcZkrsSj7yQh+0kFrvB2CSUQHUBCOQlUPlTIBTs6Ic3LnL+yK5JMXLEMd+uDPgSK40NV6cHNqifVOfLcsw8RUmJWCxzmacIvYQ==', 'SigningCertUrl': 'https://sns.us-east-1.amazonaws.com/SimpleNotificationService-433026a4050d206028891664da859041.pem', 'UnsubscribeUrl': 'https://sns.us-east-1.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:us-east-1:861229788715:domovoi-s3-bucket-events-org-humancellatlas-dss-test:8d31dcd6-abfc-4be2-9107-15932f1e8734', 'MessageAttributes': {}}}]}

19:45:58
'NoneType' object is not callable: TypeError Traceback (most recent call last): File "/var/task/domovoi/app.py", line 89, in __call__ result = handler(event, context) TypeError: 'NoneType' object is not callable
'NoneType' object is not callable: TypeError
Traceback (most recent call last):
File "/var/task/domovoi/app.py", line 89, in __call__
result = handler(event, context)
TypeError: 'NoneType' object is not callable

In all cases I have seen, this error occurs when the event bucket name is "org-humancellatlas-dss-test". My understanding is the S3 source bucket for the "dev" deployment is "org-humancellatlas-dss-dev", so it is not clear why test bucket events are coming into "dss-index-dev". It may be a historical remnant of SNS configuration, as I recall, "org-humancellatlas-dss-test" was used as the S3 source bucket for the dev deployment early on.

It appears the current dss-index/app.py code is setup correctly to only listen to the appropriate bucket:
```
dss.Config.set_config(dss.DeploymentStage.NORMAL)

s3_bucket = dss.Config.get_s3_bucket()

@app.s3_event_handler(bucket=s3_bucket, events=["s3:ObjectCreated:*"])
def dispatch_s3_indexer_event(event, context) -> None:
    app.log.setLevel(logging.DEBUG)
    if event.get("Event") == "s3:TestEvent":
        app.log.info("DSS index daemon received S3 test event")
    else:
        process_new_s3_indexable_object(event, app.log)

```

Yet, domovoi/app.py `__call__` tries to call a handler with value None:
```
    def __call__(self, event, context):
        context.log("Domovoi dispatch of event {}".format(event))
        if "task_name" in event:
            if event["task_name"] not in self.cloudwatch_events_rules:
                raise DomovoiException("Received CloudWatch event for a task with no known handler")
            handler = self.cloudwatch_events_rules[event["task_name"]]["func"]
            event = event["event"]
        elif "Records" in event and "s3" in event["Records"][0]:
            s3_bucket_name = event["Records"][0]["s3"]["bucket"]["name"]
            if s3_bucket_name not in self.s3_subscribers:
                raise DomovoiException("Received S3 event for a bucket with no known handler")
            handler = self.s3_subscribers[s3_bucket_name]["func"]
        elif "Records" in event and "Sns" in event["Records"][0]:
            try:
                event, handler = self._find_sns_s3_event_sub(event)
            except Exception:
                sns_topic = ARN(event["Records"][0]["Sns"]["TopicArn"]).resource
                if sns_topic not in self.sns_subscribers:
                    raise DomovoiException("Received SNS or S3-SNS event with no known handler")
                handler = self.sns_subscribers[sns_topic]
        else:
            raise DomovoiException("No handler found for event {}".format(event))
        result = handler(event, context)
        context.log(result)
        return result
```

The current humancellatlas SNS configuration includes topics for both `domovoi-s3-bucket-events-org-humancellatlas-dss-test` and `domovoi-s3-bucket-events-org-humancellatlas-dss-dev` that are both directed to `dss-index-dev` (and to `dss-sync-dev`), which I don't think should be the case.

### On which version of the code did the bug occur? (git hash, date, branch, be specific)
This is occurring on the master branch deployed to "dev" on 10/10/17 as of about noon Pacific time. The commit associated with the travis cron build was  3d124378b4510e1f95e35850aa232f70e6299999.
 
### Expected behavior
The dss-index-dev Lambda should only receive/handle events from a single source bucket, in this case "org-humancellatlas-dss-dev". It should not receive/handle events from other buckets.
In the case where an event from another bucket is received, it should be handled more gracefully (e.g. throwing an appropriate exception) rather than trying to call a null handler.
### Actual behavior
Described above.
### Steps to reproduce the behavior 
This may be a historical remnant of the dev deployment, and I don't know the specific series of actions that lead to its current state. It may be possible to recreate this state by:

1. Deploying DSS with `DSS_S3_BUCKET` set to a given bucket name
2. Setting `DSS_S3_BUCKET` to a different bucket name and deploying again
3. Add objects to the original bucket name used in step 1.

**Comment by ttung** [comment]
There's a subscription on the dss-test event that fires dss-index-dev. 

https://console.aws.amazon.com/sns/v2/home?region=us-east-1#/subscriptions.

<img width="908" alt="screen shot 2017-10-11 at 9 34 42 pm" src="https://user-images.githubusercontent.com/280924/31474981-1bdb3bf0-aecc-11e7-805a-30b9f69becda.png">

**Comment by ttung** [comment]
I removed it.
