### ISSUE TITLE
organize all HCA CLI commands to be under the hca command

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#579]
We currently have a few different CLI programs. This would organize all of the commands under the hca command.

**Comment by briandoconnor** [comment]
Reassigning to Kevin so it can be correctly assigned

**Comment by sampierson** [comment]
It would be useful if someone could provide a list of all the CLI programs in use that are not currently a part of the HCA CLI.

**Comment by kislyuk** [comment]
We don't have any other CLI clients, as far as I know. Closing. Please reopen if you have details about what CLI clients you'd like to have incorporated.
