### ISSUE TITLE
Bug: do not return _source when output_format != raw

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#582]
### Expected behavior
When output_format != raw don't return the source field from Elasticsearch. This can fixed by add `"_source": false` to the query. Example:
```
{
    "_source": false,
    "query" : {
        "term" : { "user" : "kimchy" }
    }
}
```

This will require inspecting the query for "_source" if it is not present and output_format != raw then add `"_source": false`.

* Test user defined _source is used when defined and output_format is summary
* Test _source is not returned when output_format is summary and no user defined _source in query.
* Test Error is returned when output_format is raw and user defines `"_source": false`

See for more details on [source filtering](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-source-filtering.html)

### Actual behavior
When a query is performed `_sources` is returned even when it's not used. This is a waste of resources.

**Comment by mweiden** [comment]
https://github.com/HumanCellAtlas/data-store/pull/661
