### ISSUE TITLE
Hungarian Notation Investigation

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#588]
Prototype the hungarian notation idea for our schema less data store.

relates to #530

**Comment by ttung** [comment]
https://github.com/elastic/elasticsearch/tree/master/docs/reference/query-dsl

I don't know if this is super complete, but maybe this is enough information to do query transformation.

**Comment by ttung** [comment]
There's also the possibility of extracting the parser from https://github.com/elastic/elasticsearch/tree/master/core/src/main/java/org/elasticsearch/index/query

**Comment by Bento007** [comment]
I think it would be easier to extract is from the python wrappers https://github.com/elastic/elasticsearch-py or https://github.com/elastic/elasticsearch-dsl-py

**Comment by ttung** [comment]
For inserting documents, we should manipulate the document ourself before sending it to the ES library.

The issue is parsing the query and rewriting the query to account for the field names, which are allowed all over the place in the query.
