### ISSUE TITLE
Index bundles according to set of schema major versions

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#594]
Place the index document representing the metadata for a bundle in an index specific to the set of schema major versions the bundle contains.

see epic #289

**Comment by mikebaumann** [comment]
This should ensure that the bundle metadata conforming to the schemas is able to be written to the ES index without field type conflicts occurring. This is based on the assumption/commitment that a change to the field type of a given field name would cause the major semantic version number of that schema and all containing schemas to be incremented. 
The bundle metadata may contain additional data not currently defined by the schemas, and this could still potentially conflict, and there will still need to be a way to handle these conflicts, which may include use of ES `ignore_malformed` and/or removing conflicting data from indexing, but it seems much more acceptable to omit searching for data not defined by the schema than it does to omit search of data that is defined by the schema.
The associated index could be identified an index name consisting of an ordered list of the schema names and major numbers the bundle contains. This would be a good first pass. If schema major numbers change rarely, this may be sufficient. If instead this results in excessive proliferation of indexes, the indexes could  be consolidated (e.g. an index with a smaller set of schema major numbers could be merged be merged into another index with a larger set of the same schema name and major numbers) at the time of indexing or reindexing.

**Comment by mikebaumann** [comment]
This approach is compatible with a variety of ways of setting the ES mappings appropriate for DSS use. Hopefully, a small set of common index settings and default mapping templates will be sufficient and can be applied consistently to all DSS indexes. Yet, the indexing approach described above is also amenable to using the schema to setup the indexes if that were to become necessary for some reason. In any case, setting-up the index mappings is a different issue/story that needs to be done and is not covered here.
