### ISSUE TITLE
Complete log management spec

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#595]
https://docs.google.com/document/d/15RUEodhwS8wtgkIpoJ_6uI9eCErzAw2YXzY6MwwUcG4/edit#

**Comment by Bento007** [comment]
Pass of to Matt

**Comment by kozbo** [comment]
initial doc done, waiting  for comments
Comment period closes 11/30

**Comment by kozbo** [comment]
waiting for review
