### ISSUE TITLE
Validate and constrain metadata files to schema when indexing

### ISSUE THREAD

**Issue by mikebaumann** [HumanCellAtlas/data-store#609]
As advocated by @briandoconnor and @ttung, to ensure bundle metadata is reliably indexed and searchable, enhance the indexer to validate the metadata files according to the schema it provides, and to remove any portions of the index document that do not conform to the schema before it is indexed.

see epic #289

**Comment by mweiden** [comment]
@mikebaumann @Bento007 I'm starting to look into this and have a clarifying question.

I see that the bundle manifest is uploaded to the store before the indexer even touches it.

1. Manifest upload https://github.com/HumanCellAtlas/data-store/blob/master/dss/api/bundles.py#L179-L182
2. Manifest read https://github.com/HumanCellAtlas/data-store/blob/master/dss/events/handlers/index.py#L50 (both AWS & GCP)

Would it be better to validate the manifest before uploading it to storage and warning the user up front? The benefit here would be preventing the upload of data in the system that we can't use.

Further, if we validated at this point we could warn the user that non-conforming portions of the index document will not be used.

**Comment by Bento007** [comment]
keep dynamic mapping.
strip everything that is not in the official schema.

**Comment by ttung** [comment]
@mweiden Once the purple box is up and running, we should not be rejecting anything that lands here.

**Comment by Bento007** [comment]
Looking for a solution for caching the json schema from git. We should not rely on git to retrieve the schema every time a document is indexed. 

We need to investigate if minor version changes of the schema will affect validation.
