### ISSUE TITLE
Reindexing: Design reindexing functionality

### ISSUE THREAD

**Issue by mikebaumann** [HumanCellAtlas/data-store#610]
Minimal/essential design for the reindexing service. This should include:

- How the reindexing system is invoked (e.g. API)
- Key elements/components of the reindexing system
- Flow through the system

This should be sufficient for a design review and providing a basic guide to implementation.

see epic #539

**Comment by hannes-ucsc** [comment]
https://docs.google.com/document/d/1qZhI7xrhfnSA5-npgsvfJPpBPgPCd3NNCldCgv4C-6I/edit#
