### ISSUE TITLE
Post notification does not include replica

### ISSUE THREAD

**Issue by emikoifish** [HumanCellAtlas/data-store#612]
Blue Box post notifications to subscribers should include which replica (AWS, GoogleCloud... etc) the subscribers should use, because the replica parameter is required to get files and bundles.

**Comment by ttung** [comment]
Subscribers should be aware which replica they're subscribing to, since the subscription API is replica-specific.

**Comment by emikoifish** [comment]
If external indexers subscribe to multiple replicas it is difficult to tell which replica the notification came from. My use case is: I have one endpoint subscribe to different replicas, then it can determine which replica to download from without having to hard code the replica. Then I will be able to display data from both replicas.

**Comment by Bento007** [comment]
This can be determined by the subscription_id returned in the notification.
