### ISSUE TITLE
Build 4 more queries and 2 alternative index views for testing

### ISSUE THREAD

**Issue by briandoconnor** [HumanCellAtlas/data-store#615]
Have 7 now:

https://docs.google.com/document/d/1WVd5R_sWzLlxP7lev90WXCxG58TyBxrixkwrD1vs_Io/edit#

Want to write queries for 4 more

Also, write at least 2 alternative index (secondary indexes) to answer at least 2 queries directly rather than partially as with current queries.

**Comment by briandoconnor** [comment]
Connects to #577

**Comment by briandoconnor** [comment]
Blocked by #289 and #539

**Comment by briandoconnor** [comment]
Carlos is coming to CZI tomorrow (11/14), I will be working on handing this off to him at the time.  Will reassign the ticket to him then.

**Comment by briandoconnor** [comment]
Looks like Carlos added 4 new queries, brought the total to 11

**Comment by caaespin** [comment]
UPDATE:
- Wrote 1 query.
- Started refactoring indexer code.
- Working on strategy for writing other indexes.

**Comment by caaespin** [comment]
UPDATE Dec 4th 2017:
- Wrote 5 queries
- Still working on refactoring the indexer code.

**Comment by mjkrause** [comment]
UPDATE
- [x] wrote one query (#16) with help from @caaespin 
- [ ] working on alternative index views for testing

**Comment by briandoconnor** [comment]
We need to push forward on mockups of transformative indexes from here as well: https://docs.google.com/document/d/1WVd5R_sWzLlxP7lev90WXCxG58TyBxrixkwrD1vs_Io/edit#heading=h.o3k4p0jctvf0 . Are you both close to wrapping the work in this ticket?

**Comment by caaespin** [comment]
UPDATE Monday Dec 11 2017:

- Wrote module making use of the HCA CLI to:
   - Receive event notification
   - Communicate with the BB to get the contents of the bundle
   - Retrieve the metadata files from the BB
   - Separate the metadata from the data files so they can be presented to the various indexers

- Working on refactoring the Indexing portion of the code:
   - Working on creating a base indexer class.
   - Rewriting the file indexer as subclass of the `Indexer` class
