### ISSUE TITLE
Ability to use unmanaged buckets by checkout service

### ISSUE THREAD

**Issue by amork** [HumanCellAtlas/data-store#640]
## Need (user story)
As a user of the DSS's consumer API
I want to be able to check out a bundle into an AWS or GCP cloud storage bucket that I manage
so that I can compute on the data in my own account.

**Comment by amork** [comment]
Document how users should configure S3 bucket permissions
Sample policy
Set up a bucket in CZI to test

**Comment by amork** [comment]
Put documentation in the swagger file

**Comment by Bento007** [comment]
should be supported but has not been tested

**Comment by kozbo** [comment]
internally tested, closing
