### ISSUE TITLE
Parallel deployments of dss lambdas might cause AWS conflicting operations

### ISSUE THREAD

**Issue by ttung** [HumanCellAtlas/data-store#668]
See https://travis-ci.org/HumanCellAtlas/data-store/builds/306906529#L6504

Three possible solutions: 

1. domovoi script should identify the conflicting operation error message and retry.  it needs to a bigger loop that encompasses the read-modify-write loop.  This is the best solution since parallelism can come from multiple people running the deploy script.
2. daemons/Makefile should use a lock to avoid the conflict.  Cleanup is tricky with makefiles though.
3. Turn off parallelism for deployment.

**Comment by kislyuk** [comment]
I will look into using an optimistic retry loop in domovoi first.

**Comment by kislyuk** [comment]
I can certainly catch and retry on `botocore.exceptions.ClientError: An error occurred (OperationAborted) when calling the PutBucketNotificationConfiguration operation: A conflicting conditional operation is currently in progress against this resource`, but I'm not sure if the underlying S3 API can protect against all race conditions ("conditional operation" hints that it should, but I don't see any sort of nonce or generation condition in the API call input). I'll take another look later, but we may be SOL and require serial operation :(
