### ISSUE TITLE
Verbose logging when sending notifications to Green Box

### ISSUE THREAD

**Issue by rexwangcc** [HumanCellAtlas/data-store#694]
Currently, the AWS's Cloud Watch is monitoring activities for us, but it would be really great if there is more verbose and trackable logging, for example, the notification content, when Blue Box is sending notifications to the listener. 

Green Box also created a ticket to add verbose logging to the listener, having logs on both sides would be really helpful for development and debugging.

**Comment by kozbo** [comment]
@hannes-ucsc is this something you can do along with your notification work?

**Comment by hannes-ucsc** [comment]
PR #1100 *should* address this. Let's revisit this after that lands.

**Comment by mweiden** [comment]
@hannes-ucsc what is the status of this?

**Comment by hannes-ucsc** [comment]
I believe #1100, addresses this. For every relevant event in the life-time of a notification, we log the subscription_id, the notification_id and the endpoint URL. We can't easily log the notification payload as it could include substantial amounts of custom fields aka attachments. When a notification is created, we log the fields above *and* the bundle_id so it is possible to correlate the two.

If this is not sufficient please reopen this ticket.

**Comment by mweiden** [comment]
@hannes-ucsc thanks!
