### ISSUE TITLE
Reindexing: Test REPAIR and VERIFY

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-store#696]
Implement unit tests and integration tests that cover repair of an index in place

**Comment by hannes-ucsc** [comment]
Related to #670

**Comment by briandoconnor** [comment]
@hannes-ucsc Should be reassigned to you, right?

**Comment by hannes-ucsc** [comment]
Actually, Brian H volunteered during the last planning.

**Comment by hannes-ucsc** [comment]
b7fa52199493c603f4d2884c59ee4f5818320755 e7112e48bea1b8ec39c2ed5324dcd9db4d3a5884 address this.
