### ISSUE TITLE
Verify with steering committee deletion policy/process

### ISSUE THREAD

**Issue by briandoconnor** [HumanCellAtlas/data-store#697]
* we need a mechanism to determine which bundles contain a given piece of data (metadata/IDs), correct? Can just be a query
* we need a tool to identified derived bundles from these bundles so the curators can determine if they need to be admin deleted.  Can just be a query.
* we can have curators ultimately use the tools above to create a list of bundles/versions that need to be "admin deleted"
* this list of bundles/versions is handed off to admin for admin delete.

**Comment by kozbo** [comment]
see https://docs.google.com/document/d/1PZI2I2-fgka110K7IlkVcf0CJgc8W6LhyFHQNoh6XV0/edit#heading=h.jksxojlpa1fd

**Comment by briandoconnor** [comment]
We're having a steering committee meeting on 20171211 and we will follow up with the issues raised above.

**Comment by briandoconnor** [comment]
Update https://docs.google.com/document/d/1PZI2I2-fgka110K7IlkVcf0CJgc8W6LhyFHQNoh6XV0/edit# with their answers.. collected in Evernote during the meeting today
