### ISSUE TITLE
Standardize bundle identifier and reference naming

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/data-store#721]
In parts of the indexing modules `bundle_key` has been used to refer to bundle files in AWS and GCP. This breaks convention with the `BlobStore` interface which refers to them with a `object_name`. For comparison, AWS identifies files in storage with a `(bucket, object key)` and GCP uses `(bucket, name)`. We should normalized this naming to the common interface.

Further, the term `bundle_id` has popped up for referring to the combination of `<bundle_uuid>.<bundle_version>`. We should choose a common term for this. The suggested term is Fully Qualified Bundle ID or `bundle_fqid`.

**Comment by mweiden** [comment]
https://github.com/HumanCellAtlas/data-store/pull/745

**Comment by Bento007** [comment]
@mweiden has this issue been resolved?
