### ISSUE TITLE
Indexer to obtain metadata schema type and version via schema URL

### ISSUE THREAD

**Issue by mikebaumann** [HumanCellAtlas/data-store#740]
### Expected behavior
The indexer should access the metadata schema type and version from the metadata schema via the schema URL.

### Actual behavior
Currently the indexer obtains the schema type and version directly from the metadata file.

### Notes
The representation of version information is described [HCA Metadata schema structure specification](https://docs.google.com/document/d/1pxQj7BfM8HHgD4ilm4dlvZuZATfJkNC5s_-TUoA4lYA).
There is considerable variation from the specification in the metadata schemas and example metadata bundles that have been released to date.

**Comment by Bento007** [comment]
Fixed by #945
