### ISSUE TITLE
Admin support for setting-up Elasticsearch instance for DSS

### ISSUE THREAD

**Issue by mikebaumann** [HumanCellAtlas/data-store#798]
Setting-up a new Elasticsearch instance for the DSS should be easy and reliable.
There should be a simple, reliable script to setup a new AWS Elasticsearch instance, and the use of this script should be clearly documented (e.g. in the data-store readme, for now, which already contains some ES setup info). This script should not be run as part of DSS deployment process per se.

There is an existing script, `data-store/daemons/deploy_aws_elasticsearch.sh` that could be simplified and updated for this purpose.

**Comment by Bento007** [comment]
This has been handle using terraform
