### ISSUE TITLE
Prevent visitation state overflow or detect early 

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-store#819]
At the end of a Parallel state, the step function machinery concatenates the final state from all branches. This introduces the possibility of the concatenated state becoming too big. If this happens, the state machinery stops the execution and puts the state machine into a Fail state. The way the visitation state machine is laid out, this happens rather late during the execution.

10c6be3 addresses this by preventing the concatenation. The concatenation is a useful feature to have for small amounts of state so #814 enables the concatenation again but for a explicit sub-tree of the state.

There should be a explicit check that guards against state overflow and makes the failure more obvious and/or happen earlier. I personally am unsure how to implement this but this was brought up by @xbrianh during review of #814.

**Comment by xbrianh** [comment]
Revisit if state consumption grows larger.
