### ISSUE TITLE
Run index REPAIR in dev and staging (after #833)

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#847]
# Deployment instructions & migrations
After #833 fix
- [x] Run reindex on dev after merge.
- [ ] Run reindex after deploying to staging

This is to added the bundles that previous failed to index, back into the index.

**Comment by hannes-ucsc** [comment]
Just did this on dev but currently #913 prevents me from doing it on staging.

**Comment by Bento007** [comment]
ran on 02/28/2018 on staging.
