### ISSUE TITLE
Streamline deployment process

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#856]
# User Story (Why?)
1. As DSS operator
I want to easily and reliably deploy DSS and its infrastructure into different AWS accounts
so that we can deploy to production.

2. As user of DSS
I want to easily and reliably deploy DSS and its infrastructure into my AWS account
so that I can have my own deployment

# DoD
- [x] Have an automated deployment process.
- [x] Document the setup process.

## Suggested tools.
* TerraForm
* Script
* Dockerized script
* Installation script

**Comment by hannes-ucsc** [comment]
Brian volunteered ;-)

**Comment by mweiden** [comment]
@xbrianh can you please document the infrastructure setup process?

The goal here would be to come to the repo as a total n00b and be able to follow instructions to deploy.
