### ISSUE TITLE
Manage load on logs ELK cluster

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#885]
The logs elasticsearch cluster is overloaded for two reasons.

- [x] we have not found an appropriate size for the cluster; it needs to be scaled to the right storage size and instance type
- [x] old indices are not deleted automatically after some time window

Depends on https://github.com/HumanCellAtlas/logs/issues/6
Depends on https://github.com/HumanCellAtlas/logs/issues/7
Connects to on https://github.com/HumanCellAtlas/logs/issues/4

**Comment by mweiden** [comment]
Dependencies have been resolved... for now (current load).
