### ISSUE TITLE
Implement and document service-to-service authentication

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#889]
## Need (user-story)
As user of the Ingestion service
my requests should be authenticated against the DSS uploaders whitelist
so that I can be approved (or denied) to upload files.

## Definition of done
Integrate with the following services
- [ ] upload service 
- [x] green box

**Comment by Bento007** [comment]
Design stage is mostly complete. Implementation stage will start soon.

**Comment by kozbo** [comment]
@kislyuk was there progress made on this ticket during the Boston developer F2F?

**Comment by Bento007** [comment]
From David Bernick on slack/HumanCellAtlast/dcp-security 
> all “service to service” auth is going to use Google Service Account keys generating access_tokens and passing them to each other’s

**Comment by mweiden** [comment]
I'm going to close this ticket. I've broken it down in to the tickets below.
* 1 - #1487
* 2, 3, 4 - #1480
* 5 - #1488
