### ISSUE TITLE
CLI for data store admin tools

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#900]
Define Admin tool kit requirements

**Comment by Bento007** [comment]
@hannes-ucsc Please update with the design.

**Comment by Bento007** [comment]
Should implement tools to verify buckets are in sync #667

**Comment by hannes-ucsc** [comment]
The admin CLI exists already. It was added in https://github.com/HumanCellAtlas/data-store/commit/6b95f55ab74f649a359497204a7eeb5bbdbe7480.

@kislyuk and I agreed to keep it as is for the time being and only consider changing the mechanism (bare-bones CLI script talking to dss-admin lambda using AWS credentials) when more actual admin tasks are added and it proves to be unwieldy. He thinks that some tasks would be better implemented without this indirection. However, the admin feature in #667 strikes me as another candidate for parallelizing using step functions, just like reindexing, and integrates well with the current approach.

I would like to close this ticket as done. New admin tasks should be added as separate tickets. Feel free to reopen if anyone disagrees.
