### ISSUE TITLE
Define Service Level Objectives

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#904]

**Comment by mweiden** [comment]
Guidelines [Minimum Viable SLOs](https://docs.google.com/document/d/1u7Xr4ibG4XympmVvIdYNxBkb2np1CMNy5X-rqHMq14Q/edit#) have been provided.

*For the pilot phase, It is more important to have visibility on errors in your system and be able to recover from errors than it is to optimize for these availability numbers.*
