### ISSUE TITLE
Description for the put file uuid is incorrect

### ISSUE THREAD

**Issue by mikebaumann** [HumanCellAtlas/data-store#910]
### Expected behavior
The Swagger description for the put file uuid parameter should be something like:
`A RFC4122-compliant ID for the file.`

### Actual behavior
Currently the Swagger description for the put file uuid parameter is:
`A RFC4122-compliant ID for the bundle.`

### Steps to reproduce the behavior -->
View the Swagger spec for the put file operation.
This may be seen on the current master branch, currently at commit 8c6e9e0b4699c1ace1c8e44ebb9739bbf57532b0

**Comment by ttung** [comment]
For bugs like this, it's probably easier just to submit a PR than to file a bug.
