### ISSUE TITLE
Add ability to re-issue permanently missed notifications

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#932]
As a subscription user I would like to be able to ask the blue box to list any callbacks I may have missed while being off line.

**Comment by hannes-ucsc** [comment]
Note that this is different from #931 which is about retrying a notification. This is about re-issuing a batch of permanently failed notification, given a certain date.

**Comment by hannes-ucsc** [comment]
I don't think this is either necessary or easy. A consumer could simply query Blue, iterate over the results and do whatever they need on their end.
