### ISSUE TITLE
Epic: add reliability to the event handoff to Green Box

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#934]

**Comment by hannes-ucsc** [comment]
The current subscription mechanism is inherently tied to Elasticsearch while Blue Box is moving to support multiple indexing backends. We should therefore decouple the notification system from the indexing backend.

We should change the  notification system to use queues. One queue per subscription with long-polling for efficiency. The obvious choice for the queues would be SQS. The notification clients should not use SQS directly but access their queues via the BlueBox REST API. We can still use web hooks, but only as a hinting mechanism for clients to alert them that they should poll their queues.

The convenient feature that ES provides is reducing the scope of notification to a subset of bundles matching a certain ES query. However, I feel that this mechanism is clunky, especially in the presence of multi-schema support. We can either ask the clients to implement the filtering client side, or, if there really are clients who want notifications for a very narrowly filtered subset, we apply server-side filtering using JMESPath or any other JSON query language soup of the day.

Having said that, the sub tasks created today jump the gun a bit by assuming that we stick with percolate and webhooks.

**Comment by kozbo** [comment]
moving to backlog as all Pilot Phase issues are complete

**Comment by kozbo** [comment]
moving to bottom of epic list as all Pilot Phase issues are complete
