### ISSUE TITLE
Update indexer metadata schema access for HCA metadata v5

### ISSUE THREAD

**Issue by mikebaumann** [HumanCellAtlas/data-store#945]
In HCA metadata v5, the format for representing schema information in the metadata files has changed, as described below. The indexer code needs to be updated to use this new format to process metadata v5.

Update indexer metadata schema access for HCA metadata v5

Previously (e.g. in metadata v4) schema information was represented as follows, at the top-level of the metadata files:
```{
  "core": {
    "type": "sample_bundle",
    "schema_url": "https://raw.githubusercontent.com/HumanCellAtlas/metadata-schema/4.6.1/json_schema/sample_bundle.json",
    "schema_version": "4.6.1"
  },
  "samples": [...]
}
```
In light of us now having “core” entities, we (HCA metadata team) did away with this core block and simply moved the three fields out one level. (Also sample is now called biomaterial. )Thus, the new files/chunks will look like this:
```{
"schema_type": "biomaterial_bundle",
"$schema": "/path/to/schema/5.0.0/biomaterial_bundle.json",
"schema_version": "5.0.0"
"biomaterials": [...]
}
```
We’ve changed `schema_url` to `$schema` which is the conventional JSON way to identify a schema URL. We will change `type` to `schema_type` to avoid confusion with the Type entities. We’ve kept schema_version for now, but are fine with taking it out if there are strong opinions to. 
Note that in the `biomaterials` array, each biomaterial entry/schema will also have the trio of `schema_type`, `$schema`, and `schema_version`.

**Comment by hannes-ucsc** [comment]
Strongly recommend that the `schema_version` field is removed. Redundancy leads to ambiguity, ambiguity leads to misinterpretation, misinterpretation leads to error. Having the version in the URL, and only the URL, sends a strong conceptual message that the content at the URL be immutable: changing the schema requires changing the version which requires changing the URL.

**Comment by mikebaumann** [comment]
Yes, I have asked the HCA metadata team to remove the `schema_version` field before metadata 5.0 is released.

**Comment by Bento007** [comment]
I think we should ignore v3 data, no sense in supporting something that was never and will never be used.

**Comment by Bento007** [comment]
connect to #740
