### ISSUE TITLE
Overly restrictive UUID regex pattern prevents valid bundles from being indexed

### ISSUE THREAD

**Issue by mikebaumann** [HumanCellAtlas/data-store#962]
### Expected behavior
If/when a bundle is successful put in the DSS, it should not fail to be indexed due to the format of its UUID.
### Actual behavior
A bundle is successful put in the DSS may fail to be indexed due to the format of its UUID.

### On which version of the code did the bug occur?
This was found in a deployment of the data-store master branch at commit 30c7cf1371a9edf2de16f93a3f1b22ed640b8b31

A recent change to the DSS indexing code introduced a more specific UUID regex pattern in the indexer than is used to validate the put bundle UUID. Thus, a bundle may be successfully put into the DSS, yet fail to be indexed due to the overly restrictive UUID regex.
Specifically, the UUID regex used to validate the UUID for put bundle is:
```
"[A-Za-z0-9]{8}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{12}"
```
yet the regex to check for a valid bundle UUID in the indexer code is now:
```
"[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}"
```
which matches only one sub-type of the UUIDs specified in RFC 4122.

### Steps to reproduce the behavior
Put a bundle into the DSS using a UUID that is RFC 4122 compliant yet the hex character after the second `-` is not `4` (e.g. is instead '5') and observe that the bundle is not indexed.

**Comment by hannes-ucsc** [comment]
Nit pick: The spec is probably silent on what types of UUID are supported by the system. I don't think this should be interpreted as "the system supports all types of UUID" as that would be insecure (types 1, 2 and 3 are either weak or leaky). The spec should say "the system supports type 4 and higher". In that sense this is not a bug. I want to be conservative with assigning the "bug" label so as to not desensitize the team to it.
