### ISSUE TITLE
Validate metadata files according to their declared schema

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-store#982]
Technically, the indexer currently validates all incoming metadata files but it is using a validator that is stripped of all validation aspects except for the detection of additional properties (so it can remove them).

The indexing of a file that declares schema compliance by referencing a particular schema but that is in fact in violation of that schema, could prevent subsequent indexing of files that are truly valid against that schema. A invalid field type, for example, in the offending file could mislead ES' dynamic mapping (aka inferred schema), causing subsequent files with a correctly typed value in that field to be rejected by ES.

We discussed offloading the validation responsibility to ingest (purple box) but important assumptions made by a system, especially assumptions like "all submitted files are valid according to their declared schema" that, if they don't hold, cause severe degradation of service ("subsequent valid files won't be indexed") should be verified by that very system. System is being defined here a set of closely coupled components that are deployed as a whole. In that sense BlueBox is such a system and HCA is not.

This is merely a pragmatic response to technical limitations in ES. Ideally BlueBox should be agnostic to the schema of the indexed metadata files and should be able to index any well-formed JSON. Unfortunately, that schema-agnostic indexer has not been found or implemented yet. Allowing for multiple indexer backends will help explore other indexing technology and get closer to fulfilling the declared goal of schema agnosticism. Until then, we should validate schema compliance of indexed files.

**Comment by mweiden** [comment]
Given that we are moving towards migrating the ES infrastructure out of the DSS, this is now out of scope. Closing this.
