### ISSUE TITLE
test_checkout fails sporadically

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-store#990]
https://travis-ci.org/HumanCellAtlas/data-store/builds/342457422#L1003
https://travis-ci.org/HumanCellAtlas/data-store/builds/342480357#L936
https://travis-ci.org/HumanCellAtlas/data-store/builds/342501683#L1005

**Comment by amork** [comment]
There is a tombstone handling code in the bundles.py that may be contributing to this. I'm going to review this with @mweiden

**Comment by hannes-ucsc** [comment]
Looks like this was caused by the messed up fixtures bucket. It wasn't actually sporadic. Once it started occurring, it occurred in every build and since the fixtures were fixed, it stopped. Feel free to reopen if you disagree.
